<?xml version="1.0" encoding="utf-8"?>
<testsuite failures="1" name="monitoring_with_simulated_messages" skipped="0" tests="1" time="4.58" timestamp="2022-04-25T21:16:50">
	<testcase classname="MonitoringWithSimulatedMessages" name="monitoring_with_simulated_messages">
		<failure message="BLOCKED: TypeError: 'int' object is not subscriptable" type="BLOCKED"/>
		<system-out>21:16:45 INFO  ==============================================================
21:16:45 INFO  Id:    monitoring_with_simulated_messages
21:16:45 INFO  Dir:   monitoring/
21:16:45 INFO  Title: Validate the tedge dm agent messages that are produced from the simulated collectd messages
21:16:45 INFO  ==============================================================
21:16:46 INFO  Executed sudo&lt;collectd&gt;, exit status 0
21:16:47 INFO  Executed sudo&lt;collectd_mapper&gt;, exit status 0
21:16:47 INFO  Started sudo&lt;tedge_sub&gt; with process id 16299
21:16:47 INFO  Executed sudo&lt;tedge_temp&gt;, exit status 0
21:16:48 INFO  Executed sudo&lt;tedge_pres&gt;, exit status 0
21:16:49 INFO  Executed sudo&lt;kill_out&gt;, exit status 0
21:16:49 INFO  0

21:16:49 WARN  TypeError occurred while running test - 'int' object is not subscriptable
Traceback (most recent call last):
  File &quot;/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py&quot;, line 1296, in __call__
    self.testObj.validate()
  File &quot;/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/monitoring/monitoring_with_simulated_messages/run.py&quot;, line 98, in validate
    collectd_msg_validation_result=self.validate_json(),
  File &quot;/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/monitoring/monitoring_with_simulated_messages/run.py&quot;, line 108, in validate_json
    if not self.validate_time():
  File &quot;/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/monitoring/monitoring_with_simulated_messages/run.py&quot;, line 127, in validate_time
    if self.js_msg[&quot;time&quot;]:
TypeError: 'int' object is not subscriptable
21:16:49 WARN  TypeError: 'int' object is not subscriptable ... blocked 
21:16:49 INFO  
21:16:49 INFO  cleanup:
21:16:49 INFO  monitoring_cleanup
21:16:50 INFO  Executed sudo&lt;collectd_mapper&gt;, exit status 0
21:16:50 INFO  
21:16:50 INFO  Test duration: 4.58 secs
21:16:50 INFO  Test final outcome:  BLOCKED
21:16:50 INFO  Test outcome reason: TypeError: 'int' object is not subscriptable
21:16:50 INFO  
</system-out>
	</testcase>
</testsuite>
