<?xml version="1.0" encoding="utf-8"?>
<testsuite failures="1" name="tedge_software_update" skipped="0" tests="1" time="2.52" timestamp="2022-04-27T10:30:46">
	<testcase classname="PySysTest" name="tedge_software_update">
		<failure message="BLOCKED: sudo&lt;tedge_connect_c8y&gt; returned non-zero exit code 1" type="BLOCKED"/>
		<system-out>10:30:44 INFO  ==============================================================
10:30:44 INFO  Id:    tedge_software_update
10:30:44 INFO  Dir:   tedge/
10:30:44 INFO  Title: Software install from download path
10:30:44 INFO  ==============================================================
10:30:44 INFO  EnvironmentC8y Setup
10:30:44 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
10:30:45 WARN  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 1
10:30:45 INFO  Contents of tedge_connect_c8y.err: 
  Error: failed to connect Cumulocity cloud.
  Caused by:
      A value for `c8y.url` is missing.
          A value can be set with `tedge config set c8y.url &lt;value&gt;`
  -----

10:30:45 WARN  sudo&lt;tedge_connect_c8y&gt; returned non-zero exit code 1 ... blocked 
10:30:45 WARN  Aborted test due to BLOCKED outcome
10:30:45 INFO  
10:30:45 INFO  cleanup:
10:30:46 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
10:30:46 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
10:30:46 INFO  
10:30:46 INFO  Test duration: 2.52 secs
10:30:46 INFO  Test final outcome:  BLOCKED
10:30:46 INFO  Test outcome reason: sudo&lt;tedge_connect_c8y&gt; returned non-zero exit code 1
10:30:46 INFO  
</system-out>
	</testcase>
</testsuite>
