<?xml version="1.0" encoding="utf-8"?>
<testsuite failures="1" name="tedge_mapper_c8y_packet_threshold_size" skipped="0" tests="1" time="2.96" timestamp="2022-04-25T21:33:04">
	<testcase classname="TedgeMapperC8yThresholdPacketSize" name="tedge_mapper_c8y_packet_threshold_size">
		<failure message="FAILED: Grep on tedge_sub.out contains &quot;The size of the message received on tedge/measurements is 20489 which is greater than the threshold size of 16184.&quot;" type="FAILED"/>
		<system-out>21:33:01 INFO  ==============================================================
21:33:01 INFO  Id:    tedge_mapper_c8y_packet_threshold_size
21:33:01 INFO  Dir:   tedge_mapper_c8y/
21:33:01 INFO  Title: Validate the Cumulocity Mapper accepted threshold packet size when it receives a message on tedge/measurements
21:33:01 INFO  ==============================================================
21:33:01 INFO  Executed sudo&lt;tedge_mapper_c8y&gt;, exit status 0
21:33:01 INFO  Started sudo&lt;tedge_sub&gt; with process id 13251
21:33:02 INFO  Executed sudo&lt;tedge_msg&gt;, exit status 0
21:33:03 INFO  Executed sudo&lt;tedge_pub&gt;, exit status 0
21:33:03 INFO  Executed sudo&lt;kill_out&gt;, exit status 0
21:33:03 WARN  Grep on tedge_sub.out contains &quot;The size of the message received on tedge/measurements is 20489 which is greater than the threshold size of 16184.&quot; ... failed [run.py:88]
21:33:03 INFO  
21:33:03 INFO  cleanup:
21:33:03 INFO  mapper_cleanup
21:33:04 INFO  Executed sudo&lt;tedge_mapper_c8y&gt;, exit status 0
21:33:04 INFO  
21:33:04 INFO  Test duration: 2.96 secs
21:33:04 INFO  Test final outcome:  FAILED
21:33:04 INFO  Test outcome reason: Grep on tedge_sub.out contains &quot;The size of the message received on tedge/measurements is 20489 which is greater than the threshold size of 16184.&quot;
21:33:04 INFO  
</system-out>
	</testcase>
</testsuite>
