<?xml version="1.0" encoding="utf-8"?>
<testsuite failures="1" name="custom_init_system" skipped="0" tests="1" time="2.83" timestamp="2022-04-27T10:29:00">
	<testcase classname="CustomInitSystem" name="custom_init_system">
		<failure message="BLOCKED: sudo&lt;tedge_connect&gt; returned non-zero exit code 1" type="BLOCKED"/>
		<system-out>10:28:57 INFO  ==============================================================
10:28:57 INFO  Id:    custom_init_system
10:28:57 INFO  Dir:   misc_features/
10:28:57 INFO  Title: Custom init system test
10:28:57 INFO  ==============================================================
10:28:58 INFO  Executed sudo&lt;copy_system_config&gt;, exit status 0
10:28:58 INFO  Executed sudo&lt;copy_dummy_init&gt;, exit status 0
10:28:59 WARN  Executed sudo&lt;tedge_connect&gt;, exit status 1
10:28:59 INFO  Contents of tedge_connect.err: 
  Error: failed to connect Cumulocity cloud.
  Caused by:
      A value for `c8y.url` is missing.
          A value can be set with `tedge config set c8y.url &lt;value&gt;`
  -----

10:28:59 WARN  sudo&lt;tedge_connect&gt; returned non-zero exit code 1 ... blocked [run.py:53]
10:28:59 WARN  Aborted test due to BLOCKED outcome
10:28:59 INFO  
10:28:59 INFO  cleanup:
10:28:59 INFO  Executed sudo&lt;remove_system_config&gt;, exit status 0
10:29:00 INFO  Executed sudo&lt;remove_dummy_init&gt;, exit status 0
10:29:00 INFO  
10:29:00 INFO  Test duration: 2.83 secs
10:29:00 INFO  Test final outcome:  BLOCKED
10:29:00 INFO  Test outcome reason: sudo&lt;tedge_connect&gt; returned non-zero exit code 1
10:29:00 INFO  
</system-out>
	</testcase>
</testsuite>
