<?xml version="1.0" encoding="utf-8"?>
<testsuite failures="1" name="SoftwareManagement.sm_apt_install_fail" skipped="0" tests="1" time="77.05" timestamp="2022-04-27T09:13:40">
	<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_fail">
		<failure message="BLOCKED: TypeError: 'NoneType' object is not iterable" type="BLOCKED"/>
		<system-out>09:12:22 INFO  ==============================================================
09:12:22 INFO  Id:    SoftwareManagement.sm_apt_install_fail
09:12:22 INFO  Dir:   software_management_end_to_end/
09:12:22 INFO  Title: Validate end to end behaviour for a failing installation
09:12:22 INFO  ==============================================================
09:12:22 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
09:12:22 INFO  EnvironmentC8y Setup
09:12:23 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
09:12:23 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 4 seconds
09:12:23 INFO  Delaying execution by 7 seconds
09:12:44 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 13 secs
09:12:45 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
09:12:45 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
09:12:46 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
09:12:48 INFO  State of current operation: SUCCESSFUL
09:12:48 INFO  Response status: 201
09:12:48 INFO  Response to action: {
    &quot;delivery&quot;: {
        &quot;time&quot;: &quot;2022-04-27T09:12:48.601Z&quot;,
        &quot;log&quot;: [],
        &quot;status&quot;: &quot;PENDING&quot;
    },
    &quot;creationTime&quot;: &quot;2022-04-27T09:12:48.591Z&quot;,
    &quot;deviceName&quot;: &quot;m32sd10a&quot;,
    &quot;deviceId&quot;: &quot;17748287&quot;,
    &quot;self&quot;: &quot;https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17757476&quot;,
    &quot;id&quot;: &quot;17757476&quot;,
    &quot;status&quot;: &quot;PENDING&quot;,
    &quot;description&quot;: &quot;Apply software changes, triggered from PySys: [{'name': 'does_not_exist', 'id': '5446165', 'version': '::apt', 'url': '', 'action': 'install'}]&quot;,
    &quot;c8y_SoftwareUpdate&quot;: [
        {
            &quot;name&quot;: &quot;does_not_exist&quot;,
            &quot;action&quot;: &quot;install&quot;,
            &quot;id&quot;: &quot;5446165&quot;,
            &quot;version&quot;: &quot;::apt&quot;,
            &quot;url&quot;: &quot;&quot;
        }
    ]
}
09:12:48 INFO  Started operation: {'delivery': {'time': '2022-04-27T09:12:48.601Z', 'log': [], 'status': 'PENDING'}, 'creationTime': '2022-04-27T09:12:48.591Z', 'deviceName': 'm32sd10a', 'deviceId': '17748287', 'self': 'https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17757476', 'id': '17757476', 'status': 'PENDING', 'description': &quot;Apply software changes, triggered from PySys: [{'name': 'does_not_exist', 'id': '5446165', 'version': '::apt', 'url': '', 'action': 'install'}]&quot;, 'c8y_SoftwareUpdate': [{'name': 'does_not_exist', 'action': 'install', 'id': '5446165', 'version': '::apt', 'url': ''}]}
09:12:50 INFO  State of operation 17757476 : PENDING
09:12:53 INFO  State of operation 17757476 : EXECUTING
09:12:55 INFO  State of operation 17757476 : EXECUTING
09:12:57 INFO  State of operation 17757476 : EXECUTING
09:12:59 INFO  State of operation 17757476 : EXECUTING
09:13:02 INFO  State of operation 17757476 : EXECUTING
09:13:04 INFO  State of operation 17757476 : EXECUTING
09:13:07 INFO  State of operation 17757476 : EXECUTING
09:13:09 INFO  State of operation 17757476 : EXECUTING
09:13:12 INFO  State of operation 17757476 : EXECUTING
09:13:14 INFO  State of operation 17757476 : EXECUTING
09:13:16 INFO  State of operation 17757476 : EXECUTING
09:13:18 INFO  State of operation 17757476 : EXECUTING
09:13:20 INFO  State of operation 17757476 : EXECUTING
09:13:23 INFO  State of operation 17757476 : EXECUTING
09:13:25 INFO  State of operation 17757476 : EXECUTING
09:13:28 INFO  State of operation 17757476 : EXECUTING
09:13:30 INFO  State of operation 17757476 : EXECUTING
09:13:33 INFO  State of operation 17757476 : EXECUTING
09:13:35 INFO  State of operation 17757476 : FAILED
09:13:35 WARN  TypeError occurred while running test - 'NoneType' object is not iterable
Traceback (most recent call last):
  File &quot;/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py&quot;, line 1296, in __call__
    self.testObj.validate()
  File &quot;/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_fail/run.py&quot;, line 31, in validate
    &quot;False == value&quot;, value=self.check_is_installed(&quot;does_not_exist&quot;)
  File &quot;/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py&quot;, line 398, in check_is_installed
    for package in package_list:
TypeError: 'NoneType' object is not iterable
09:13:35 WARN  TypeError: 'NoneType' object is not iterable ... blocked 
09:13:35 INFO  
09:13:35 INFO  cleanup:
09:13:39 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
09:13:40 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
09:13:40 INFO  
09:13:40 INFO  Test duration: 77.05 secs
09:13:40 INFO  Test final outcome:  BLOCKED
09:13:40 INFO  Test outcome reason: TypeError: 'NoneType' object is not iterable
09:13:40 INFO  
</system-out>
	</testcase>
</testsuite>
