<?xml version='1.0' encoding='utf-8'?>
<testsuites tests="147" failures="29" errors="0" skipped="45" time="0.0"><testsuite name="SoftwareManagement.Plugin.apama_plugin_install" tests="3" errors="0" failures="0" skipped="1" time="0"><testcase classname="ApamaPluginInstallTest" name="SoftwareManagement.Plugin.apama_plugin_install">
		<skipped message="SKIPPED: Apama plugin tests are disabled by default. Execute `pysys run` with `-XmyPlatform=container` to run these tests" />
		<system-out>11:06:06 INFO  ==============================================================
11:06:06 INFO  Id:    SoftwareManagement.Plugin.apama_plugin_install
11:06:06 INFO  Dir:   plugin_apama/
11:06:06 INFO  Title: Validate apama plugin install
11:06:06 INFO  ==============================================================
11:06:06 INFO  Apama plugin tests are disabled by default. Execute `pysys run` with `-XmyPlatform=container` to run these tests ... skipped
11:06:06 WARN  Aborted test due to SKIPPED outcome
11:06:06 INFO  
11:06:06 INFO  Test duration: 0.05 secs
11:06:06 INFO  Test final outcome:  SKIPPED
11:06:06 INFO  Test outcome reason: Apama plugin tests are disabled by default. Execute `pysys run` with `-XmyPlatform=container` to run these tests
11:06:06 INFO  
</system-out>
	</testcase>
<testcase classname="ApamaPluginInstallTest" name="SoftwareManagement.Plugin.apama_plugin_install" />
<testcase classname="ApamaPluginInstallTest" name="SoftwareManagement.Plugin.apama_plugin_install" />
</testsuite><testsuite name="SoftwareManagement.Plugin.apama_plugin_mon_support" tests="3" errors="0" failures="0" skipped="1" time="0"><testcase classname="ApamaPluginMonSupportTest" name="SoftwareManagement.Plugin.apama_plugin_mon_support">
		<skipped message="SKIPPED: Apama plugin tests are disabled by default. Execute `pysys run` with `-XmyPlatform=container` to run these tests" />
		<system-out>11:06:06 INFO  ==============================================================
11:06:06 INFO  Id:    SoftwareManagement.Plugin.apama_plugin_mon_support
11:06:06 INFO  Dir:   plugin_apama/
11:06:06 INFO  Title: Validate mon file support of apama plugin
11:06:06 INFO  ==============================================================
11:06:06 INFO  Apama plugin tests are disabled by default. Execute `pysys run` with `-XmyPlatform=container` to run these tests ... skipped
11:06:06 WARN  Aborted test due to SKIPPED outcome
11:06:06 INFO  
11:06:06 INFO  Test duration: 0.03 secs
11:06:06 INFO  Test final outcome:  SKIPPED
11:06:06 INFO  Test outcome reason: Apama plugin tests are disabled by default. Execute `pysys run` with `-XmyPlatform=container` to run these tests
11:06:06 INFO  
</system-out>
	</testcase>
<testcase classname="ApamaPluginMonSupportTest" name="SoftwareManagement.Plugin.apama_plugin_mon_support" />
<testcase classname="ApamaPluginMonSupportTest" name="SoftwareManagement.Plugin.apama_plugin_mon_support" />
</testsuite><testsuite name="SoftwareManagement.Plugin.apama_plugin_remove" tests="3" errors="0" failures="0" skipped="1" time="0"><testcase classname="ApamaPluginRemoveTest" name="SoftwareManagement.Plugin.apama_plugin_remove">
		<skipped message="SKIPPED: Apama plugin tests are disabled by default. Execute `pysys run` with `-XmyPlatform=container` to run these tests" />
		<system-out>11:06:06 INFO  ==============================================================
11:06:06 INFO  Id:    SoftwareManagement.Plugin.apama_plugin_remove
11:06:06 INFO  Dir:   plugin_apama/
11:06:06 INFO  Title: Validate apama plugin remove
11:06:06 INFO  ==============================================================
11:06:06 INFO  Apama plugin tests are disabled by default. Execute `pysys run` with `-XmyPlatform=container` to run these tests ... skipped
11:06:06 WARN  Aborted test due to SKIPPED outcome
11:06:06 INFO  
11:06:06 INFO  Test duration: 0.02 secs
11:06:06 INFO  Test final outcome:  SKIPPED
11:06:06 INFO  Test outcome reason: Apama plugin tests are disabled by default. Execute `pysys run` with `-XmyPlatform=container` to run these tests
11:06:06 INFO  
</system-out>
	</testcase>
<testcase classname="ApamaPluginRemoveTest" name="SoftwareManagement.Plugin.apama_plugin_remove" />
<testcase classname="ApamaPluginRemoveTest" name="SoftwareManagement.Plugin.apama_plugin_remove" />
</testsuite><testsuite name="SoftwareManagement.Plugin.apama_plugin_update" tests="3" errors="0" failures="2" skipped="1" time="0"><testcase classname="ApamaPluginUpdateTest" name="SoftwareManagement.Plugin.apama_plugin_update">
		<skipped message="SKIPPED: Apama plugin tests are disabled by default. Execute `pysys run` with `-XmyPlatform=container` to run these tests" />
		<system-out>11:06:06 INFO  ==============================================================
11:06:06 INFO  Id:    SoftwareManagement.Plugin.apama_plugin_update
11:06:06 INFO  Dir:   plugin_apama/
11:06:06 INFO  Title: Validate apama plugin updating one project with another
11:06:06 INFO  ==============================================================
11:06:06 INFO  Apama plugin tests are disabled by default. Execute `pysys run` with `-XmyPlatform=container` to run these tests ... skipped
11:06:06 WARN  Aborted test due to SKIPPED outcome
11:06:06 INFO  
11:06:06 INFO  Test duration: 0.02 secs
11:06:06 INFO  Test final outcome:  SKIPPED
11:06:06 INFO  Test outcome reason: Apama plugin tests are disabled by default. Execute `pysys run` with `-XmyPlatform=container` to run these tests
11:06:06 INFO  
</system-out>
	</testcase>
<testcase classname="ApamaPluginUpdateTest" name="SoftwareManagement.Plugin.apama_plugin_update">
		<failure message="BLOCKED: sudo&lt;plugin_install&gt; returned non-zero exit code 2" type="BLOCKED" />
		<system-out>11:45:12 INFO  ==============================================================
11:45:12 INFO  Id:    SoftwareManagement.Plugin.apama_plugin_update
11:45:12 INFO  Dir:   plugin_apama/
11:45:12 INFO  Title: Validate apama plugin updating one project with another
11:45:12 INFO  ==============================================================
11:45:12 INFO  Assertion that path exists=False for "/etc/tedge/apama/project" ... passed
11:45:12 INFO  Executed sudo&lt;create_project_dir&gt;, exit status 0
11:45:13 INFO  Executed sudo&lt;unzip_apama_project&gt;, exit status 0
11:45:13 INFO  Executed sudo&lt;move_apama_project&gt;, exit status 0
11:45:14 INFO  Executed sudo&lt;restart_apama_service&gt;, exit status 0
11:45:15 INFO  Executed sudo&lt;apama_correlator_wait&gt;, exit status 0
11:45:15 INFO  Assertion that path exists=True for "/etc/tedge/apama/project" ... passed
11:45:16 INFO  Executed sudo&lt;apama_list_monitors&gt;, exit status 0
11:45:16 INFO  Grep on file /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apama/apama_plugin_update/Output/linux/apama_list_monitors.out ... passed
11:45:16 WARN  Executed sudo&lt;plugin_install&gt;, exit status 2
11:45:16 INFO  Contents of plugin_install.err: 
  ERROR: Directory not empty (os error 39)
  -----

11:45:17 WARN  sudo&lt;plugin_install&gt; returned non-zero exit code 2 ... blocked [run.py:35]
11:45:17 WARN  Aborted test due to BLOCKED outcome
11:45:17 INFO  
11:45:17 INFO  cleanup:
11:45:17 INFO  Removing apama project
11:45:32 INFO  Executed sudo&lt;stop_apama_service&gt;, exit status 0, duration 15 secs
11:45:33 INFO  Executed sudo&lt;remove_apama_project&gt;, exit status 0
11:45:33 INFO  Executed sudo&lt;remove_apama_tmp_dir&gt;, exit status 0
11:45:33 INFO  
11:45:33 INFO  Test duration: 21.28 secs
11:45:33 INFO  Test final outcome:  BLOCKED
11:45:33 INFO  Test outcome reason: sudo&lt;plugin_install&gt; returned non-zero exit code 2
11:45:33 INFO  
</system-out>
	</testcase>
<testcase classname="ApamaPluginUpdateTest" name="SoftwareManagement.Plugin.apama_plugin_update">
		<failure message="BLOCKED: sudo&lt;plugin_install&gt; returned non-zero exit code 2" type="BLOCKED" />
		<system-out>11:50:57 INFO  ==============================================================
11:50:57 INFO  Id:    SoftwareManagement.Plugin.apama_plugin_update
11:50:57 INFO  Dir:   plugin_apama/
11:50:57 INFO  Title: Validate apama plugin updating one project with another
11:50:57 INFO  ==============================================================
11:50:57 INFO  Assertion that path exists=False for "/etc/tedge/apama/project" ... passed
11:50:58 INFO  Executed sudo&lt;create_project_dir&gt;, exit status 0
11:50:58 INFO  Executed sudo&lt;unzip_apama_project&gt;, exit status 0
11:50:59 INFO  Executed sudo&lt;move_apama_project&gt;, exit status 0
11:51:00 INFO  Executed sudo&lt;restart_apama_service&gt;, exit status 0
11:51:00 INFO  Executed sudo&lt;apama_correlator_wait&gt;, exit status 0
11:51:00 INFO  Assertion that path exists=True for "/etc/tedge/apama/project" ... passed
11:51:01 INFO  Executed sudo&lt;apama_list_monitors&gt;, exit status 0
11:51:01 INFO  Grep on file /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apama/apama_plugin_update/Output/linux/apama_list_monitors.out ... passed
11:51:02 WARN  Executed sudo&lt;plugin_install&gt;, exit status 2
11:51:02 INFO  Contents of plugin_install.err: 
  ERROR: Directory not empty (os error 39)
  -----

11:51:02 WARN  sudo&lt;plugin_install&gt; returned non-zero exit code 2 ... blocked [run.py:35]
11:51:02 WARN  Aborted test due to BLOCKED outcome
11:51:02 INFO  
11:51:02 INFO  cleanup:
11:51:02 INFO  Removing apama project
11:51:17 INFO  Executed sudo&lt;stop_apama_service&gt;, exit status 0, duration 15 secs
11:51:18 INFO  Executed sudo&lt;remove_apama_project&gt;, exit status 0
11:51:18 INFO  Executed sudo&lt;remove_apama_tmp_dir&gt;, exit status 0
11:51:18 INFO  
11:51:18 INFO  Test duration: 21.12 secs
11:51:18 INFO  Test final outcome:  BLOCKED
11:51:18 INFO  Test outcome reason: sudo&lt;plugin_install&gt; returned non-zero exit code 2
11:51:18 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="SoftwareManagement.sm_apt_install_download_path" tests="3" errors="0" failures="2" skipped="1" time="0"><testcase classname="AptInstallWithDownloadPath" name="SoftwareManagement.sm_apt_install_download_path">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it" />
		<system-out>11:15:44 INFO  ==============================================================
11:15:44 INFO  Id:    SoftwareManagement.sm_apt_install_download_path
11:15:44 INFO  Dir:   software_management_end_to_end/
11:15:44 INFO  Title: Install package to directory specified in tedge config set tmp.path
11:15:44 INFO  ==============================================================
11:15:44 INFO  Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it ... skipped
11:15:44 WARN  Aborted test due to SKIPPED outcome
11:15:44 INFO  
11:15:44 INFO  Test duration: 0.06 secs
11:15:44 INFO  Test final outcome:  SKIPPED
11:15:44 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it
11:15:44 INFO  
</system-out>
	</testcase>
<testcase classname="AptInstallWithDownloadPath" name="SoftwareManagement.sm_apt_install_download_path">
		<failure message="BLOCKED: SystemError: The Sofware list is empty !!!" type="BLOCKED" />
		<system-out>11:39:13 INFO  ==============================================================
11:39:13 INFO  Id:    SoftwareManagement.sm_apt_install_download_path
11:39:13 INFO  Dir:   software_management_end_to_end/
11:39:13 INFO  Title: Install package to directory specified in tedge config set tmp.path
11:39:13 INFO  ==============================================================
11:39:13 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
11:39:13 INFO  EnvironmentC8y Setup
11:39:14 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
11:39:29 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
11:39:30 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
11:39:31 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
11:39:32 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
11:39:34 INFO  State of current operation: SUCCESSFUL
11:39:35 WARN  SystemError occurred while running test - The Sofware list is empty !!!
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1292, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_download_path/run.py", line 49, in setup
    self.assertThat("False == value", value=self.check_is_installed("rolldice"))
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 399, in check_is_installed
    raise SystemError("The Sofware list is empty !!!")
SystemError: The Sofware list is empty !!!
11:39:35 WARN  SystemError: The Sofware list is empty !!! ... blocked 
11:39:35 INFO  
11:39:35 INFO  cleanup:
11:39:36 INFO  Executed sudo, exit status 0
11:39:36 INFO  Executed sudo, exit status 0
11:39:40 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
11:39:40 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 3 seconds
11:39:40 INFO  Delaying execution by 8 seconds
11:40:02 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 13 secs
11:40:07 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
11:40:07 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
11:40:07 INFO  
11:40:07 INFO  Test duration: 54.07 secs
11:40:07 INFO  Test final outcome:  BLOCKED
11:40:07 INFO  Test outcome reason: SystemError: The Sofware list is empty !!!
11:40:07 INFO  
</system-out>
	</testcase>
<testcase classname="AptInstallWithDownloadPath" name="SoftwareManagement.sm_apt_install_download_path">
		<failure message="BLOCKED: SystemError: The Sofware list is empty !!!" type="BLOCKED" />
		<system-out>11:51:18 INFO  ==============================================================
11:51:18 INFO  Id:    SoftwareManagement.sm_apt_install_download_path
11:51:18 INFO  Dir:   software_management_end_to_end/
11:51:18 INFO  Title: Install package to directory specified in tedge config set tmp.path
11:51:18 INFO  ==============================================================
11:51:20 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
11:51:20 INFO  EnvironmentC8y Setup
11:51:20 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
11:51:34 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
11:51:35 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
11:51:36 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
11:51:36 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
11:51:38 INFO  State of current operation: FAILED
11:51:39 WARN  SystemError occurred while running test - The Sofware list is empty !!!
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1292, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_download_path/run.py", line 49, in setup
    self.assertThat("False == value", value=self.check_is_installed("rolldice"))
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 399, in check_is_installed
    raise SystemError("The Sofware list is empty !!!")
SystemError: The Sofware list is empty !!!
11:51:39 WARN  SystemError: The Sofware list is empty !!! ... blocked 
11:51:39 INFO  
11:51:39 INFO  cleanup:
11:51:39 INFO  Executed sudo, exit status 0
11:51:40 INFO  Executed sudo, exit status 0
11:51:44 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
11:51:44 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 3 seconds
11:51:44 INFO  Delaying execution by 8 seconds
11:52:06 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
11:52:11 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
11:52:11 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
11:52:11 INFO  
11:52:11 INFO  Test duration: 52.86 secs
11:52:11 INFO  Test final outcome:  BLOCKED
11:52:11 INFO  Test outcome reason: SystemError: The Sofware list is empty !!!
11:52:11 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="SoftwareManagement.sm_apt_install_fail" tests="3" errors="0" failures="2" skipped="1" time="0"><testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_fail">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it" />
		<system-out>11:15:44 INFO  ==============================================================
11:15:44 INFO  Id:    SoftwareManagement.sm_apt_install_fail
11:15:44 INFO  Dir:   software_management_end_to_end/
11:15:44 INFO  Title: Validate end to end behaviour for a failing installation
11:15:44 INFO  ==============================================================
11:15:44 INFO  Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it ... skipped
11:15:44 WARN  Aborted test due to SKIPPED outcome
11:15:44 INFO  
11:15:44 INFO  Test duration: 0.02 secs
11:15:44 INFO  Test final outcome:  SKIPPED
11:15:44 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it
11:15:44 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_fail">
		<failure message="BLOCKED: SystemError: The Sofware list is empty !!!" type="BLOCKED" />
		<system-out>11:40:07 INFO  ==============================================================
11:40:07 INFO  Id:    SoftwareManagement.sm_apt_install_fail
11:40:07 INFO  Dir:   software_management_end_to_end/
11:40:07 INFO  Title: Validate end to end behaviour for a failing installation
11:40:07 INFO  ==============================================================
11:40:07 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
11:40:07 INFO  EnvironmentC8y Setup
11:40:08 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
11:40:08 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 4 seconds
11:40:08 INFO  Delaying execution by 7 seconds
11:40:29 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
11:40:30 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
11:40:30 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
11:40:31 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
11:40:33 INFO  State of current operation: SUCCESSFUL
11:40:33 INFO  Response status: 201
11:40:33 INFO  Response to action: {
    "creationTime": "2022-05-13T11:40:33.553Z",
    "deviceId": "19000396",
    "deviceName": "m32sd10b",
    "self": "https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/19028668",
    "id": "19028668",
    "status": "PENDING",
    "description": "Apply software changes, triggered from PySys: [{'name': 'does_not_exist', 'id': '5446165', 'version': '::apt', 'url': '', 'action': 'install'}]",
    "c8y_SoftwareUpdate": [
        {
            "name": "does_not_exist",
            "action": "install",
            "id": "5446165",
            "version": "::apt",
            "url": ""
        }
    ]
}
11:40:33 INFO  Started operation: {'creationTime': '2022-05-13T11:40:33.553Z', 'deviceId': '19000396', 'deviceName': 'm32sd10b', 'self': 'https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/19028668', 'id': '19028668', 'status': 'PENDING', 'description': "Apply software changes, triggered from PySys: [{'name': 'does_not_exist', 'id': '5446165', 'version': '::apt', 'url': '', 'action': 'install'}]", 'c8y_SoftwareUpdate': [{'name': 'does_not_exist', 'action': 'install', 'id': '5446165', 'version': '::apt', 'url': ''}]}
11:40:35 INFO  State of operation 19028668 : PENDING
11:40:38 INFO  State of operation 19028668 : EXECUTING
11:40:40 INFO  State of operation 19028668 : EXECUTING
11:40:42 INFO  State of operation 19028668 : EXECUTING
11:40:44 INFO  State of operation 19028668 : EXECUTING
11:40:46 INFO  State of operation 19028668 : EXECUTING
11:40:49 INFO  State of operation 19028668 : EXECUTING
11:40:52 INFO  State of operation 19028668 : EXECUTING
11:40:54 INFO  State of operation 19028668 : EXECUTING
11:40:56 INFO  State of operation 19028668 : EXECUTING
11:40:59 INFO  State of operation 19028668 : EXECUTING
11:41:01 INFO  State of operation 19028668 : EXECUTING
11:41:03 INFO  State of operation 19028668 : EXECUTING
11:41:05 INFO  State of operation 19028668 : EXECUTING
11:41:08 INFO  State of operation 19028668 : EXECUTING
11:41:10 INFO  State of operation 19028668 : EXECUTING
11:41:13 INFO  State of operation 19028668 : EXECUTING
11:41:16 INFO  State of operation 19028668 : EXECUTING
11:41:18 INFO  State of operation 19028668 : EXECUTING
11:41:20 INFO  State of operation 19028668 : FAILED
11:41:20 WARN  SystemError occurred while running test - The Sofware list is empty !!!
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1296, in __call__
    self.testObj.validate()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_fail/run.py", line 31, in validate
    "False == value", value=self.check_is_installed("does_not_exist")
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 399, in check_is_installed
    raise SystemError("The Sofware list is empty !!!")
SystemError: The Sofware list is empty !!!
11:41:21 WARN  SystemError: The Sofware list is empty !!! ... blocked 
11:41:21 INFO  
11:41:21 INFO  cleanup:
11:41:24 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
11:41:25 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
11:41:25 INFO  
11:41:25 INFO  Test duration: 77.86 secs
11:41:25 INFO  Test final outcome:  BLOCKED
11:41:25 INFO  Test outcome reason: SystemError: The Sofware list is empty !!!
11:41:25 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_fail">
		<failure message="BLOCKED: SystemError: The Sofware list is empty !!!" type="BLOCKED" />
		<system-out>11:52:11 INFO  ==============================================================
11:52:11 INFO  Id:    SoftwareManagement.sm_apt_install_fail
11:52:11 INFO  Dir:   software_management_end_to_end/
11:52:11 INFO  Title: Validate end to end behaviour for a failing installation
11:52:11 INFO  ==============================================================
11:52:11 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
11:52:11 INFO  EnvironmentC8y Setup
11:52:12 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
11:52:12 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 4 seconds
11:52:12 INFO  Delaying execution by 7 seconds
11:52:33 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 13 secs
11:52:34 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
11:52:34 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
11:52:34 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
11:52:37 INFO  State of current operation: FAILED
11:52:37 INFO  Response status: 201
11:52:37 INFO  Response to action: {
    "creationTime": "2022-05-13T11:52:37.395Z",
    "deviceId": "19000396",
    "deviceName": "m32sd10b",
    "self": "https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/19028749",
    "id": "19028749",
    "status": "PENDING",
    "description": "Apply software changes, triggered from PySys: [{'name': 'does_not_exist', 'id': '5446165', 'version': '::apt', 'url': '', 'action': 'install'}]",
    "c8y_SoftwareUpdate": [
        {
            "name": "does_not_exist",
            "action": "install",
            "id": "5446165",
            "version": "::apt",
            "url": ""
        }
    ]
}
11:52:37 INFO  Started operation: {'creationTime': '2022-05-13T11:52:37.395Z', 'deviceId': '19000396', 'deviceName': 'm32sd10b', 'self': 'https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/19028749', 'id': '19028749', 'status': 'PENDING', 'description': "Apply software changes, triggered from PySys: [{'name': 'does_not_exist', 'id': '5446165', 'version': '::apt', 'url': '', 'action': 'install'}]", 'c8y_SoftwareUpdate': [{'name': 'does_not_exist', 'action': 'install', 'id': '5446165', 'version': '::apt', 'url': ''}]}
11:52:39 INFO  State of operation 19028749 : PENDING
11:52:41 INFO  State of operation 19028749 : EXECUTING
11:52:44 INFO  State of operation 19028749 : EXECUTING
11:52:46 INFO  State of operation 19028749 : EXECUTING
11:52:48 INFO  State of operation 19028749 : EXECUTING
11:52:50 INFO  State of operation 19028749 : EXECUTING
11:52:53 INFO  State of operation 19028749 : EXECUTING
11:52:56 INFO  State of operation 19028749 : EXECUTING
11:52:58 INFO  State of operation 19028749 : EXECUTING
11:53:01 INFO  State of operation 19028749 : EXECUTING
11:53:03 INFO  State of operation 19028749 : EXECUTING
11:53:05 INFO  State of operation 19028749 : EXECUTING
11:53:07 INFO  State of operation 19028749 : EXECUTING
11:53:09 INFO  State of operation 19028749 : EXECUTING
11:53:12 INFO  State of operation 19028749 : EXECUTING
11:53:14 INFO  State of operation 19028749 : FAILED
11:53:14 WARN  SystemError occurred while running test - The Sofware list is empty !!!
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1296, in __call__
    self.testObj.validate()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_fail/run.py", line 31, in validate
    "False == value", value=self.check_is_installed("does_not_exist")
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 399, in check_is_installed
    raise SystemError("The Sofware list is empty !!!")
SystemError: The Sofware list is empty !!!
11:53:14 WARN  SystemError: The Sofware list is empty !!! ... blocked 
11:53:14 INFO  
11:53:14 INFO  cleanup:
11:53:18 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
11:53:19 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
11:53:19 INFO  
11:53:19 INFO  Test duration: 67.41 secs
11:53:19 INFO  Test final outcome:  BLOCKED
11:53:19 INFO  Test outcome reason: SystemError: The Sofware list is empty !!!
11:53:19 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="SoftwareManagement.sm_apt_install_remove" tests="3" errors="0" failures="2" skipped="1" time="0"><testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it" />
		<system-out>11:15:44 INFO  ==============================================================
11:15:44 INFO  Id:    SoftwareManagement.sm_apt_install_remove
11:15:44 INFO  Dir:   software_management_end_to_end/
11:15:44 INFO  Title: Validate end to end behaviour for the apt plugin for installation and removal of packages
11:15:44 INFO  ==============================================================
11:15:44 INFO  Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it ... skipped
11:15:44 WARN  Aborted test due to SKIPPED outcome
11:15:44 INFO  
11:15:44 INFO  Test duration: 0.02 secs
11:15:44 INFO  Test final outcome:  SKIPPED
11:15:44 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it
11:15:44 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove">
		<failure message="BLOCKED: SystemError: The Sofware list is empty !!!" type="BLOCKED" />
		<system-out>11:41:25 INFO  ==============================================================
11:41:25 INFO  Id:    SoftwareManagement.sm_apt_install_remove
11:41:25 INFO  Dir:   software_management_end_to_end/
11:41:25 INFO  Title: Validate end to end behaviour for the apt plugin for installation and removal of packages
11:41:25 INFO  ==============================================================
11:41:25 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
11:41:25 INFO  EnvironmentC8y Setup
11:41:26 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
11:41:26 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 4 seconds
11:41:26 INFO  Delaying execution by 7 seconds
11:41:47 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
11:41:47 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
11:41:48 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
11:41:48 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
11:41:51 INFO  State of current operation: FAILED
11:41:51 WARN  SystemError occurred while running test - The Sofware list is empty !!!
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1292, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove/run.py", line 28, in setup
    if self.check_is_installed("rolldice"):
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 399, in check_is_installed
    raise SystemError("The Sofware list is empty !!!")
SystemError: The Sofware list is empty !!!
11:41:51 WARN  SystemError: The Sofware list is empty !!! ... blocked 
11:41:51 INFO  
11:41:51 INFO  cleanup:
11:41:55 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
11:41:55 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
11:41:55 INFO  
11:41:55 INFO  Test duration: 30.14 secs
11:41:55 INFO  Test final outcome:  BLOCKED
11:41:55 INFO  Test outcome reason: SystemError: The Sofware list is empty !!!
11:41:55 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove">
		<failure message="BLOCKED: SystemError: The Sofware list is empty !!!" type="BLOCKED" />
		<system-out>11:53:19 INFO  ==============================================================
11:53:19 INFO  Id:    SoftwareManagement.sm_apt_install_remove
11:53:19 INFO  Dir:   software_management_end_to_end/
11:53:19 INFO  Title: Validate end to end behaviour for the apt plugin for installation and removal of packages
11:53:19 INFO  ==============================================================
11:53:19 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
11:53:19 INFO  EnvironmentC8y Setup
11:53:19 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
11:53:19 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 5 seconds
11:53:19 INFO  Delaying execution by 6 seconds
11:53:40 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
11:53:40 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
11:53:41 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
11:53:41 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
11:53:43 INFO  State of current operation: FAILED
11:53:44 WARN  SystemError occurred while running test - The Sofware list is empty !!!
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1292, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove/run.py", line 28, in setup
    if self.check_is_installed("rolldice"):
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 399, in check_is_installed
    raise SystemError("The Sofware list is empty !!!")
SystemError: The Sofware list is empty !!!
11:53:44 WARN  SystemError: The Sofware list is empty !!! ... blocked 
11:53:44 INFO  
11:53:44 INFO  cleanup:
11:53:47 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
11:53:48 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
11:53:48 INFO  
11:53:48 INFO  Test duration: 29.21 secs
11:53:48 INFO  Test final outcome:  BLOCKED
11:53:48 INFO  Test outcome reason: SystemError: The Sofware list is empty !!!
11:53:48 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="SoftwareManagement.sm_apt_install_remove_default" tests="3" errors="0" failures="2" skipped="1" time="0"><testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove_default">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it" />
		<system-out>11:15:44 INFO  ==============================================================
11:15:44 INFO  Id:    SoftwareManagement.sm_apt_install_remove_default
11:15:44 INFO  Dir:   software_management_end_to_end/
11:15:44 INFO  Title: Validate end to end behaviour for the default plugin for installation and removal of packages
11:15:44 INFO  ==============================================================
11:15:44 INFO  Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it ... skipped
11:15:44 WARN  Aborted test due to SKIPPED outcome
11:15:44 INFO  
11:15:44 INFO  Test duration: 0.02 secs
11:15:44 INFO  Test final outcome:  SKIPPED
11:15:44 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it
11:15:44 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove_default">
		<failure message="BLOCKED: SystemError: The Sofware list is empty !!!" type="BLOCKED" />
		<system-out>11:41:55 INFO  ==============================================================
11:41:55 INFO  Id:    SoftwareManagement.sm_apt_install_remove_default
11:41:55 INFO  Dir:   software_management_end_to_end/
11:41:55 INFO  Title: Validate end to end behaviour for the default plugin for installation and removal of packages
11:41:55 INFO  ==============================================================
11:41:55 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
11:41:55 INFO  EnvironmentC8y Setup
11:41:56 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
11:41:56 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 5 seconds
11:41:56 INFO  Delaying execution by 6 seconds
11:42:16 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 13 secs
11:42:17 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
11:42:17 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
11:42:18 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
11:42:20 INFO  State of current operation: FAILED
11:42:20 WARN  SystemError occurred while running test - The Sofware list is empty !!!
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1292, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_default/run.py", line 27, in setup
    self.assertThat("False == value", value=self.check_is_installed("rolldice"))
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 399, in check_is_installed
    raise SystemError("The Sofware list is empty !!!")
SystemError: The Sofware list is empty !!!
11:42:20 WARN  SystemError: The Sofware list is empty !!! ... blocked 
11:42:20 INFO  
11:42:20 INFO  cleanup:
11:42:24 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
11:42:25 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
11:42:25 INFO  
11:42:25 INFO  Test duration: 29.34 secs
11:42:25 INFO  Test final outcome:  BLOCKED
11:42:25 INFO  Test outcome reason: SystemError: The Sofware list is empty !!!
11:42:25 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove_default">
		<failure message="BLOCKED: SystemError: The Sofware list is empty !!!" type="BLOCKED" />
		<system-out>11:53:48 INFO  ==============================================================
11:53:48 INFO  Id:    SoftwareManagement.sm_apt_install_remove_default
11:53:48 INFO  Dir:   software_management_end_to_end/
11:53:48 INFO  Title: Validate end to end behaviour for the default plugin for installation and removal of packages
11:53:48 INFO  ==============================================================
11:53:48 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
11:53:48 INFO  EnvironmentC8y Setup
11:53:49 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
11:53:49 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 4 seconds
11:53:49 INFO  Delaying execution by 7 seconds
11:54:10 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 13 secs
11:54:10 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
11:54:11 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
11:54:11 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
11:54:13 INFO  State of current operation: FAILED
11:54:14 WARN  SystemError occurred while running test - The Sofware list is empty !!!
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1292, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_default/run.py", line 27, in setup
    self.assertThat("False == value", value=self.check_is_installed("rolldice"))
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 399, in check_is_installed
    raise SystemError("The Sofware list is empty !!!")
SystemError: The Sofware list is empty !!!
11:54:14 WARN  SystemError: The Sofware list is empty !!! ... blocked 
11:54:14 INFO  
11:54:14 INFO  cleanup:
11:54:18 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
11:54:18 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
11:54:18 INFO  
11:54:18 INFO  Test duration: 30.12 secs
11:54:18 INFO  Test final outcome:  BLOCKED
11:54:18 INFO  Test outcome reason: SystemError: The Sofware list is empty !!!
11:54:18 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="SoftwareManagement.sm_apt_install_remove_multiple" tests="3" errors="0" failures="2" skipped="1" time="0"><testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove_multiple">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it" />
		<system-out>11:15:44 INFO  ==============================================================
11:15:44 INFO  Id:    SoftwareManagement.sm_apt_install_remove_multiple
11:15:44 INFO  Dir:   software_management_end_to_end/
11:15:44 INFO  Title: Validate end to end behaviour for the apt plugin for multiple packages
11:15:44 INFO  ==============================================================
11:15:44 INFO  Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it ... skipped
11:15:44 WARN  Aborted test due to SKIPPED outcome
11:15:44 INFO  
11:15:44 INFO  Test duration: 0.02 secs
11:15:44 INFO  Test final outcome:  SKIPPED
11:15:44 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it
11:15:44 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove_multiple">
		<failure message="BLOCKED: SystemError: The Sofware list is empty !!!" type="BLOCKED" />
		<system-out>11:42:25 INFO  ==============================================================
11:42:25 INFO  Id:    SoftwareManagement.sm_apt_install_remove_multiple
11:42:25 INFO  Dir:   software_management_end_to_end/
11:42:25 INFO  Title: Validate end to end behaviour for the apt plugin for multiple packages
11:42:25 INFO  ==============================================================
11:42:25 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
11:42:25 INFO  EnvironmentC8y Setup
11:42:25 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
11:42:25 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 5 seconds
11:42:25 INFO  Delaying execution by 6 seconds
11:42:45 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 13 secs
11:42:46 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
11:42:46 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
11:42:47 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
11:42:49 INFO  State of current operation: FAILED
11:42:49 WARN  SystemError occurred while running test - The Sofware list is empty !!!
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1292, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/run.py", line 54, in setup
    self.assertThat("False == value", value=self.check_is_installed("rolldice"))
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 399, in check_is_installed
    raise SystemError("The Sofware list is empty !!!")
SystemError: The Sofware list is empty !!!
11:42:49 WARN  SystemError: The Sofware list is empty !!! ... blocked 
11:42:49 INFO  
11:42:49 INFO  cleanup:
11:42:53 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
11:42:54 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
11:42:54 INFO  
11:42:54 INFO  Test duration: 29.05 secs
11:42:54 INFO  Test final outcome:  BLOCKED
11:42:54 INFO  Test outcome reason: SystemError: The Sofware list is empty !!!
11:42:54 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove_multiple">
		<failure message="BLOCKED: SystemError: The Sofware list is empty !!!" type="BLOCKED" />
		<system-out>11:54:18 INFO  ==============================================================
11:54:18 INFO  Id:    SoftwareManagement.sm_apt_install_remove_multiple
11:54:18 INFO  Dir:   software_management_end_to_end/
11:54:18 INFO  Title: Validate end to end behaviour for the apt plugin for multiple packages
11:54:18 INFO  ==============================================================
11:54:18 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
11:54:18 INFO  EnvironmentC8y Setup
11:54:19 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
11:54:19 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 4 seconds
11:54:19 INFO  Delaying execution by 7 seconds
11:54:40 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
11:54:41 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
11:54:41 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
11:54:42 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
11:54:44 INFO  State of current operation: FAILED
11:54:44 WARN  SystemError occurred while running test - The Sofware list is empty !!!
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1292, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/run.py", line 54, in setup
    self.assertThat("False == value", value=self.check_is_installed("rolldice"))
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 399, in check_is_installed
    raise SystemError("The Sofware list is empty !!!")
SystemError: The Sofware list is empty !!!
11:54:44 WARN  SystemError: The Sofware list is empty !!! ... blocked 
11:54:44 INFO  
11:54:44 INFO  cleanup:
11:54:48 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
11:54:49 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
11:54:49 INFO  
11:54:49 INFO  Test duration: 30.55 secs
11:54:49 INFO  Test final outcome:  BLOCKED
11:54:49 INFO  Test outcome reason: SystemError: The Sofware list is empty !!!
11:54:49 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="SoftwareManagement.sm_apt_install_remove_multiple_mixed" tests="3" errors="0" failures="2" skipped="1" time="0"><testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove_multiple_mixed">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it" />
		<system-out>11:15:44 INFO  ==============================================================
11:15:44 INFO  Id:    SoftwareManagement.sm_apt_install_remove_multiple_mixed
11:15:44 INFO  Dir:   software_management_end_to_end/
11:15:44 INFO  Title: Validate end to end behaviour for the apt plugin for multiple packages with mixed versions
11:15:44 INFO  ==============================================================
11:15:44 INFO  Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it ... skipped
11:15:44 WARN  Aborted test due to SKIPPED outcome
11:15:44 INFO  
11:15:44 INFO  Test duration: 0.02 secs
11:15:44 INFO  Test final outcome:  SKIPPED
11:15:44 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it
11:15:44 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove_multiple_mixed">
		<failure message="BLOCKED: SystemError: The Sofware list is empty !!!" type="BLOCKED" />
		<system-out>11:42:54 INFO  ==============================================================
11:42:54 INFO  Id:    SoftwareManagement.sm_apt_install_remove_multiple_mixed
11:42:54 INFO  Dir:   software_management_end_to_end/
11:42:54 INFO  Title: Validate end to end behaviour for the apt plugin for multiple packages with mixed versions
11:42:54 INFO  ==============================================================
11:42:54 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
11:42:54 INFO  EnvironmentC8y Setup
11:42:54 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
11:42:54 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 4 seconds
11:42:54 INFO  Delaying execution by 7 seconds
11:43:15 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
11:43:16 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
11:43:17 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
11:43:17 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
11:43:19 INFO  State of current operation: FAILED
11:43:19 WARN  SystemError occurred while running test - The Sofware list is empty !!!
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1292, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple_mixed/run.py", line 75, in setup
    self.assertThat("False == value", value=self.check_is_installed("asciijump"))
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 399, in check_is_installed
    raise SystemError("The Sofware list is empty !!!")
SystemError: The Sofware list is empty !!!
11:43:19 WARN  SystemError: The Sofware list is empty !!! ... blocked 
11:43:19 INFO  
11:43:19 INFO  cleanup:
11:43:23 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
11:43:24 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
11:43:24 INFO  
11:43:24 INFO  Test duration: 30.18 secs
11:43:24 INFO  Test final outcome:  BLOCKED
11:43:24 INFO  Test outcome reason: SystemError: The Sofware list is empty !!!
11:43:24 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove_multiple_mixed">
		<failure message="BLOCKED: SystemError: The Sofware list is empty !!!" type="BLOCKED" />
		<system-out>11:54:49 INFO  ==============================================================
11:54:49 INFO  Id:    SoftwareManagement.sm_apt_install_remove_multiple_mixed
11:54:49 INFO  Dir:   software_management_end_to_end/
11:54:49 INFO  Title: Validate end to end behaviour for the apt plugin for multiple packages with mixed versions
11:54:49 INFO  ==============================================================
11:54:49 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
11:54:49 INFO  EnvironmentC8y Setup
11:54:49 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
11:54:50 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 5 seconds
11:54:50 INFO  Delaying execution by 6 seconds
11:55:09 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 13 secs
11:55:10 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
11:55:10 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
11:55:11 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
11:55:13 INFO  State of current operation: FAILED
11:55:13 WARN  SystemError occurred while running test - The Sofware list is empty !!!
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1292, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple_mixed/run.py", line 75, in setup
    self.assertThat("False == value", value=self.check_is_installed("asciijump"))
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 399, in check_is_installed
    raise SystemError("The Sofware list is empty !!!")
SystemError: The Sofware list is empty !!!
11:55:13 WARN  SystemError: The Sofware list is empty !!! ... blocked 
11:55:13 INFO  
11:55:13 INFO  cleanup:
11:55:17 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
11:55:18 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
11:55:18 INFO  
11:55:18 INFO  Test duration: 29.22 secs
11:55:18 INFO  Test final outcome:  BLOCKED
11:55:18 INFO  Test outcome reason: SystemError: The Sofware list is empty !!!
11:55:18 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="SoftwareManagement.sm_apt_install_remove_with_version" tests="3" errors="0" failures="2" skipped="1" time="0"><testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove_with_version">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it" />
		<system-out>11:15:44 INFO  ==============================================================
11:15:44 INFO  Id:    SoftwareManagement.sm_apt_install_remove_with_version
11:15:44 INFO  Dir:   software_management_end_to_end/
11:15:44 INFO  Title: Validate end to end behaviour for the apt plugin for packages with version
11:15:44 INFO  ==============================================================
11:15:44 INFO  Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it ... skipped
11:15:44 WARN  Aborted test due to SKIPPED outcome
11:15:44 INFO  
11:15:44 INFO  Test duration: 0.02 secs
11:15:44 INFO  Test final outcome:  SKIPPED
11:15:44 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it
11:15:44 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove_with_version">
		<failure message="BLOCKED: SystemError: The Sofware list is empty !!!" type="BLOCKED" />
		<system-out>11:43:24 INFO  ==============================================================
11:43:24 INFO  Id:    SoftwareManagement.sm_apt_install_remove_with_version
11:43:24 INFO  Dir:   software_management_end_to_end/
11:43:24 INFO  Title: Validate end to end behaviour for the apt plugin for packages with version
11:43:24 INFO  ==============================================================
11:43:24 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
11:43:24 INFO  EnvironmentC8y Setup
11:43:25 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
11:43:25 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 4 seconds
11:43:25 INFO  Delaying execution by 7 seconds
11:43:46 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 13 secs
11:43:46 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
11:43:47 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
11:43:47 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
11:43:49 INFO  State of current operation: FAILED
11:43:50 WARN  SystemError occurred while running test - The Sofware list is empty !!!
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1292, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_with_version/run.py", line 29, in setup
    self.assertThat("False == value", value=self.check_is_installed("rolldice"))
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 399, in check_is_installed
    raise SystemError("The Sofware list is empty !!!")
SystemError: The Sofware list is empty !!!
11:43:50 WARN  SystemError: The Sofware list is empty !!! ... blocked 
11:43:50 INFO  
11:43:50 INFO  cleanup:
11:43:54 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
11:43:54 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
11:43:54 INFO  
11:43:54 INFO  Test duration: 30.21 secs
11:43:54 INFO  Test final outcome:  BLOCKED
11:43:54 INFO  Test outcome reason: SystemError: The Sofware list is empty !!!
11:43:54 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove_with_version">
		<failure message="BLOCKED: SystemError: The Sofware list is empty !!!" type="BLOCKED" />
		<system-out>11:55:18 INFO  ==============================================================
11:55:18 INFO  Id:    SoftwareManagement.sm_apt_install_remove_with_version
11:55:18 INFO  Dir:   software_management_end_to_end/
11:55:18 INFO  Title: Validate end to end behaviour for the apt plugin for packages with version
11:55:18 INFO  ==============================================================
11:55:18 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
11:55:18 INFO  EnvironmentC8y Setup
11:55:19 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
11:55:19 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 4 seconds
11:55:19 INFO  Delaying execution by 7 seconds
11:55:40 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
11:55:41 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
11:55:41 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
11:55:42 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
11:55:44 INFO  State of current operation: FAILED
11:55:44 WARN  SystemError occurred while running test - The Sofware list is empty !!!
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1292, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_with_version/run.py", line 29, in setup
    self.assertThat("False == value", value=self.check_is_installed("rolldice"))
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 399, in check_is_installed
    raise SystemError("The Sofware list is empty !!!")
SystemError: The Sofware list is empty !!!
11:55:44 WARN  SystemError: The Sofware list is empty !!! ... blocked 
11:55:44 INFO  
11:55:44 INFO  cleanup:
11:55:48 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
11:55:48 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
11:55:48 INFO  
11:55:48 INFO  Test duration: 30.44 secs
11:55:48 INFO  Test final outcome:  BLOCKED
11:55:48 INFO  Test outcome reason: SystemError: The Sofware list is empty !!!
11:55:48 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="SoftwareManagement.sm_docker_install_remove_multiple" tests="3" errors="0" failures="2" skipped="1" time="0"><testcase classname="SMDockerInstallRemove" name="SoftwareManagement.sm_docker_install_remove_multiple">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it" />
		<system-out>11:15:45 INFO  ==============================================================
11:15:45 INFO  Id:    SoftwareManagement.sm_docker_install_remove_multiple
11:15:45 INFO  Dir:   software_management_end_to_end/
11:15:45 INFO  Title: Validate end to end behaviour for the docker plugin for multiple docker images with mixed versions
11:15:45 INFO  ==============================================================
11:15:45 INFO  Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it ... skipped
11:15:45 WARN  Aborted test due to SKIPPED outcome
11:15:45 INFO  
11:15:45 INFO  Test duration: 0.02 secs
11:15:45 INFO  Test final outcome:  SKIPPED
11:15:45 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it
11:15:45 INFO  
</system-out>
	</testcase>
<testcase classname="SMDockerInstallRemove" name="SoftwareManagement.sm_docker_install_remove_multiple">
		<failure message="BLOCKED: SystemError: The operation has failed" type="BLOCKED" />
		<system-out>11:48:30 INFO  ==============================================================
11:48:30 INFO  Id:    SoftwareManagement.sm_docker_install_remove_multiple
11:48:30 INFO  Dir:   software_management_end_to_end/
11:48:30 INFO  Title: Validate end to end behaviour for the docker plugin for multiple docker images with mixed versions
11:48:30 INFO  ==============================================================
11:48:32 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
11:48:32 INFO  EnvironmentC8y Setup
11:48:32 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
11:48:48 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 15 secs
11:48:48 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
11:48:49 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
11:48:49 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
11:48:52 INFO  State of current operation: FAILED
11:48:52 INFO  Response status: 201
11:48:52 INFO  Response to action: {
    "creationTime": "2022-05-13T11:48:52.386Z",
    "deviceId": "19000396",
    "deviceName": "m32sd10b",
    "self": "https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/19028735",
    "id": "19028735",
    "status": "PENDING",
    "description": "Apply software changes, triggered from PySys: [{'action': 'install', 'id': '8021526', 'name': 'hello-world', 'url': '', 'version': '::docker'}, {'action': 'install', 'id': '8018911', 'name': 'registry', 'url': '', 'version': '2.6.2::docker'}]",
    "c8y_SoftwareUpdate": [
        {
            "name": "hello-world",
            "action": "install",
            "id": "8021526",
            "version": "::docker",
            "url": ""
        },
        {
            "name": "registry",
            "action": "install",
            "id": "8018911",
            "version": "2.6.2::docker",
            "url": ""
        }
    ]
}
11:48:52 INFO  Started operation: {'creationTime': '2022-05-13T11:48:52.386Z', 'deviceId': '19000396', 'deviceName': 'm32sd10b', 'self': 'https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/19028735', 'id': '19028735', 'status': 'PENDING', 'description': "Apply software changes, triggered from PySys: [{'action': 'install', 'id': '8021526', 'name': 'hello-world', 'url': '', 'version': '::docker'}, {'action': 'install', 'id': '8018911', 'name': 'registry', 'url': '', 'version': '2.6.2::docker'}]", 'c8y_SoftwareUpdate': [{'name': 'hello-world', 'action': 'install', 'id': '8021526', 'version': '::docker', 'url': ''}, {'name': 'registry', 'action': 'install', 'id': '8018911', 'version': '2.6.2::docker', 'url': ''}]}
11:48:54 INFO  State of operation 19028735 : PENDING
11:48:56 INFO  State of operation 19028735 : EXECUTING
11:48:59 INFO  State of operation 19028735 : EXECUTING
11:49:01 INFO  State of operation 19028735 : EXECUTING
11:49:03 INFO  State of operation 19028735 : FAILED
11:49:03 ERROR Stopping as the operation has failed
11:49:03 WARN  SystemError occurred while running test - The operation has failed
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1292, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_docker_install_remove_multiple/run.py", line 55, in setup
    self.wait_until_succcess()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 324, in wait_until_succcess
    self.wait_until_status("SUCCESSFUL")
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 361, in wait_until_status
    raise SystemError("The operation has failed")
SystemError: The operation has failed
11:49:03 WARN  SystemError: The operation has failed ... blocked 
11:49:03 INFO  
11:49:03 INFO  cleanup:
11:49:07 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
11:49:08 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
11:49:08 INFO  
11:49:08 INFO  Test duration: 37.57 secs
11:49:08 INFO  Test final outcome:  BLOCKED
11:49:08 INFO  Test outcome reason: SystemError: The operation has failed
11:49:08 INFO  
</system-out>
	</testcase>
<testcase classname="SMDockerInstallRemove" name="SoftwareManagement.sm_docker_install_remove_multiple">
		<failure message="BLOCKED: SystemError: The operation has failed" type="BLOCKED" />
		<system-out>11:55:49 INFO  ==============================================================
11:55:49 INFO  Id:    SoftwareManagement.sm_docker_install_remove_multiple
11:55:49 INFO  Dir:   software_management_end_to_end/
11:55:49 INFO  Title: Validate end to end behaviour for the docker plugin for multiple docker images with mixed versions
11:55:49 INFO  ==============================================================
11:55:49 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
11:55:49 INFO  EnvironmentC8y Setup
11:55:50 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
11:55:50 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 5 seconds
11:55:50 INFO  Delaying execution by 6 seconds
11:56:10 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
11:56:11 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
11:56:11 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
11:56:12 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
11:56:14 INFO  State of current operation: FAILED
11:56:14 INFO  Response status: 201
11:56:14 INFO  Response to action: {
    "creationTime": "2022-05-13T11:56:14.797Z",
    "deviceId": "19000396",
    "deviceName": "m32sd10b",
    "self": "https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/19028769",
    "id": "19028769",
    "status": "PENDING",
    "description": "Apply software changes, triggered from PySys: [{'action': 'install', 'id': '8021526', 'name': 'hello-world', 'url': '', 'version': '::docker'}, {'action': 'install', 'id': '8018911', 'name': 'registry', 'url': '', 'version': '2.6.2::docker'}]",
    "c8y_SoftwareUpdate": [
        {
            "name": "hello-world",
            "action": "install",
            "id": "8021526",
            "version": "::docker",
            "url": ""
        },
        {
            "name": "registry",
            "action": "install",
            "id": "8018911",
            "version": "2.6.2::docker",
            "url": ""
        }
    ]
}
11:56:14 INFO  Started operation: {'creationTime': '2022-05-13T11:56:14.797Z', 'deviceId': '19000396', 'deviceName': 'm32sd10b', 'self': 'https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/19028769', 'id': '19028769', 'status': 'PENDING', 'description': "Apply software changes, triggered from PySys: [{'action': 'install', 'id': '8021526', 'name': 'hello-world', 'url': '', 'version': '::docker'}, {'action': 'install', 'id': '8018911', 'name': 'registry', 'url': '', 'version': '2.6.2::docker'}]", 'c8y_SoftwareUpdate': [{'name': 'hello-world', 'action': 'install', 'id': '8021526', 'version': '::docker', 'url': ''}, {'name': 'registry', 'action': 'install', 'id': '8018911', 'version': '2.6.2::docker', 'url': ''}]}
11:56:17 INFO  State of operation 19028769 : PENDING
11:56:19 INFO  State of operation 19028769 : EXECUTING
11:56:21 INFO  State of operation 19028769 : EXECUTING
11:56:23 INFO  State of operation 19028769 : EXECUTING
11:56:25 INFO  State of operation 19028769 : FAILED
11:56:25 ERROR Stopping as the operation has failed
11:56:25 WARN  SystemError occurred while running test - The operation has failed
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1292, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_docker_install_remove_multiple/run.py", line 55, in setup
    self.wait_until_succcess()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 324, in wait_until_succcess
    self.wait_until_status("SUCCESSFUL")
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 361, in wait_until_status
    raise SystemError("The operation has failed")
SystemError: The operation has failed
11:56:25 WARN  SystemError: The operation has failed ... blocked 
11:56:25 INFO  
11:56:25 INFO  cleanup:
11:56:29 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
11:56:30 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
11:56:30 INFO  
11:56:30 INFO  Test duration: 41.46 secs
11:56:30 INFO  Test final outcome:  BLOCKED
11:56:30 INFO  Test outcome reason: SystemError: The operation has failed
11:56:30 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="SoftwareManagement.sm_fake_install_remove" tests="2" errors="0" failures="1" skipped="1" time="0"><testcase classname="PySysTest" name="SoftwareManagement.sm_fake_install_remove">
		<skipped message="SKIPPED: Testing the fake plugin is not enabled.Use parameter -Xfakeplugin=fakeplugin to enable it" />
		<system-out>11:15:45 INFO  ==============================================================
11:15:45 INFO  Id:    SoftwareManagement.sm_fake_install_remove
11:15:45 INFO  Dir:   software_management_end_to_end/
11:15:45 INFO  Title: Validate end to end behaviour for the dummy plugin for installation and removal of packages
11:15:45 INFO  ==============================================================
11:15:45 INFO  Testing the fake plugin is not enabled.Use parameter -Xfakeplugin=fakeplugin to enable it ... skipped
11:15:45 WARN  Aborted test due to SKIPPED outcome
11:15:45 INFO  
11:15:45 INFO  Test duration: 0.02 secs
11:15:45 INFO  Test final outcome:  SKIPPED
11:15:45 INFO  Test outcome reason: Testing the fake plugin is not enabled.Use parameter -Xfakeplugin=fakeplugin to enable it
11:15:45 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_fake_install_remove">
		<failure message="BLOCKED: SystemError: The Sofware list is empty !!!" type="BLOCKED" />
		<system-out>11:56:30 INFO  ==============================================================
11:56:30 INFO  Id:    SoftwareManagement.sm_fake_install_remove
11:56:30 INFO  Dir:   software_management_end_to_end/
11:56:30 INFO  Title: Validate end to end behaviour for the dummy plugin for installation and removal of packages
11:56:30 INFO  ==============================================================
11:56:30 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
11:56:30 INFO  EnvironmentC8y Setup
11:56:31 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
11:56:31 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 4 seconds
11:56:31 INFO  Delaying execution by 7 seconds
11:56:52 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 13 secs
11:56:52 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
11:56:53 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
11:56:53 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
11:56:56 INFO  State of current operation: FAILED
11:56:56 WARN  SystemError occurred while running test - The Sofware list is empty !!!
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1292, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_fake_install_remove/run.py", line 41, in setup
    self.assertThat("False == value", value=self.check_is_installed("tomatoooo"))
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 399, in check_is_installed
    raise SystemError("The Sofware list is empty !!!")
SystemError: The Sofware list is empty !!!
11:56:56 WARN  SystemError: The Sofware list is empty !!! ... blocked 
11:56:56 INFO  
11:56:56 INFO  cleanup:
11:57:00 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
11:57:00 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
11:57:00 INFO  
11:57:00 INFO  Test duration: 30.28 secs
11:57:00 INFO  Test final outcome:  BLOCKED
11:57:00 INFO  Test outcome reason: SystemError: The Sofware list is empty !!!
11:57:00 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="SoftwareManagement.sm_fake_install_remove_multiple" tests="2" errors="0" failures="1" skipped="1" time="0"><testcase classname="PySysTest" name="SoftwareManagement.sm_fake_install_remove_multiple">
		<skipped message="SKIPPED: Testing the fake plugin is not enabled.Use parameter -Xfakeplugin=fakeplugin to enable it" />
		<system-out>11:15:45 INFO  ==============================================================
11:15:45 INFO  Id:    SoftwareManagement.sm_fake_install_remove_multiple
11:15:45 INFO  Dir:   software_management_end_to_end/
11:15:45 INFO  Title: Validate end to end behaviour for the dummy-plugin for multiple packages
11:15:45 INFO  ==============================================================
11:15:45 INFO  Testing the fake plugin is not enabled.Use parameter -Xfakeplugin=fakeplugin to enable it ... skipped
11:15:45 WARN  Aborted test due to SKIPPED outcome
11:15:45 INFO  
11:15:45 INFO  Test duration: 0.03 secs
11:15:45 INFO  Test final outcome:  SKIPPED
11:15:45 INFO  Test outcome reason: Testing the fake plugin is not enabled.Use parameter -Xfakeplugin=fakeplugin to enable it
11:15:45 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_fake_install_remove_multiple">
		<failure message="BLOCKED: SystemError: The Sofware list is empty !!!" type="BLOCKED" />
		<system-out>11:57:00 INFO  ==============================================================
11:57:00 INFO  Id:    SoftwareManagement.sm_fake_install_remove_multiple
11:57:00 INFO  Dir:   software_management_end_to_end/
11:57:00 INFO  Title: Validate end to end behaviour for the dummy-plugin for multiple packages
11:57:00 INFO  ==============================================================
11:57:00 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
11:57:00 INFO  EnvironmentC8y Setup
11:57:01 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
11:57:01 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 5 seconds
11:57:01 INFO  Delaying execution by 6 seconds
11:57:21 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
11:57:22 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
11:57:22 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
11:57:23 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
11:57:25 INFO  State of current operation: FAILED
11:57:25 WARN  SystemError occurred while running test - The Sofware list is empty !!!
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1292, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_fake_install_remove_multiple/run.py", line 71, in setup
    self.assertThat("True == value", value=self.check_is_installed("apple"))
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 399, in check_is_installed
    raise SystemError("The Sofware list is empty !!!")
SystemError: The Sofware list is empty !!!
11:57:25 WARN  SystemError: The Sofware list is empty !!! ... blocked 
11:57:25 INFO  
11:57:25 INFO  cleanup:
11:57:29 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
11:57:30 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
11:57:30 INFO  
11:57:30 INFO  Test duration: 29.68 secs
11:57:30 INFO  Test final outcome:  BLOCKED
11:57:30 INFO  Test outcome reason: SystemError: The Sofware list is empty !!!
11:57:30 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="SoftwareManagement.sm_mapper_fail_and_reconnect" tests="2" errors="0" failures="0" skipped="2" time="0"><testcase classname="MapperC8yReceiveLastMessageOnRestart" name="SoftwareManagement.sm_mapper_fail_and_reconnect">
		<skipped message="SKIPPED: instable https://github.com/thin-edge/thin-edge.io/issues/752" />
		<system-out>11:15:45 INFO  ==============================================================
11:15:45 INFO  Id:    SoftwareManagement.sm_mapper_fail_and_reconnect
11:15:45 INFO  Dir:   software_management_end_to_end/
11:15:45 INFO  Title: Validate the tedge-mapper-sm-c8y for receiving the last message on restart
11:15:45 INFO  ==============================================================
11:15:45 INFO  instable https://github.com/thin-edge/thin-edge.io/issues/752 ... skipped
11:15:45 INFO  
11:15:45 INFO  Test duration: 0.02 secs
11:15:45 INFO  Test final outcome:  SKIPPED
11:15:45 INFO  Test outcome reason: instable https://github.com/thin-edge/thin-edge.io/issues/752
11:15:45 INFO  
</system-out>
	</testcase>
<testcase classname="MapperC8yReceiveLastMessageOnRestart" name="SoftwareManagement.sm_mapper_fail_and_reconnect">
		<skipped message="SKIPPED: instable https://github.com/thin-edge/thin-edge.io/issues/752" />
		<system-out>11:57:30 INFO  ==============================================================
11:57:30 INFO  Id:    SoftwareManagement.sm_mapper_fail_and_reconnect
11:57:30 INFO  Dir:   software_management_end_to_end/
11:57:30 INFO  Title: Validate the tedge-mapper-sm-c8y for receiving the last message on restart
11:57:30 INFO  ==============================================================
11:57:30 INFO  instable https://github.com/thin-edge/thin-edge.io/issues/752 ... skipped
11:57:30 INFO  
11:57:30 INFO  Test duration: 0.07 secs
11:57:30 INFO  Test final outcome:  SKIPPED
11:57:30 INFO  Test outcome reason: instable https://github.com/thin-edge/thin-edge.io/issues/752
11:57:30 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="SoftwareManagement.sm_mixed_install_remove_multiple" tests="2" errors="0" failures="1" skipped="1" time="0"><testcase classname="PySysTest" name="SoftwareManagement.sm_mixed_install_remove_multiple">
		<skipped message="SKIPPED: Testing the fake plugin is not enabled.Use parameter -Xfakeplugin=fakeplugin to enable it" />
		<system-out>11:15:45 INFO  ==============================================================
11:15:45 INFO  Id:    SoftwareManagement.sm_mixed_install_remove_multiple
11:15:45 INFO  Dir:   software_management_end_to_end/
11:15:45 INFO  Title: Validate end to end behaviour for the dummy-plugin for multiple packages with mixed versions
11:15:45 INFO  ==============================================================
11:15:45 INFO  Testing the fake plugin is not enabled.Use parameter -Xfakeplugin=fakeplugin to enable it ... skipped
11:15:45 WARN  Aborted test due to SKIPPED outcome
11:15:45 INFO  
11:15:45 INFO  Test duration: 0.03 secs
11:15:45 INFO  Test final outcome:  SKIPPED
11:15:45 INFO  Test outcome reason: Testing the fake plugin is not enabled.Use parameter -Xfakeplugin=fakeplugin to enable it
11:15:45 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_mixed_install_remove_multiple">
		<failure message="BLOCKED: SystemError: The Sofware list is empty !!!" type="BLOCKED" />
		<system-out>11:57:30 INFO  ==============================================================
11:57:30 INFO  Id:    SoftwareManagement.sm_mixed_install_remove_multiple
11:57:30 INFO  Dir:   software_management_end_to_end/
11:57:30 INFO  Title: Validate end to end behaviour for the dummy-plugin for multiple packages with mixed versions
11:57:30 INFO  ==============================================================
11:57:30 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
11:57:30 INFO  EnvironmentC8y Setup
11:57:31 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
11:57:31 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 4 seconds
11:57:31 INFO  Delaying execution by 7 seconds
11:57:52 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 13 secs
11:57:52 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
11:57:53 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
11:57:53 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
11:57:56 INFO  State of current operation: FAILED
11:57:56 WARN  SystemError occurred while running test - The Sofware list is empty !!!
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1292, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_mixed_install_remove_multiple/run.py", line 85, in setup
    self.assertThat("True == value", value=self.check_is_installed("apple"))
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 399, in check_is_installed
    raise SystemError("The Sofware list is empty !!!")
SystemError: The Sofware list is empty !!!
11:57:56 WARN  SystemError: The Sofware list is empty !!! ... blocked 
11:57:56 INFO  
11:57:56 INFO  cleanup:
11:58:00 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
11:58:00 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
11:58:00 INFO  
11:58:00 INFO  Test duration: 30.30 secs
11:58:00 INFO  Test final outcome:  BLOCKED
11:58:00 INFO  Test outcome reason: SystemError: The Sofware list is empty !!!
11:58:00 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="agent_init_session" tests="1" errors="0" failures="1" skipped="0" time="0"><testcase classname="AgentInitSession" name="agent_init_session">
		<failure message="FAILED: Grep on sub_resp.out contains &quot;Ld3KgqpcLDlrYH6sfpG7w&quot;" type="FAILED" />
		<system-out>11:16:37 INFO  ==============================================================
11:16:37 INFO  Id:    agent_init_session
11:16:37 INFO  Dir:   tedge_agent/
11:16:37 INFO  Title: Validate tedge agent init session feature
11:16:37 INFO  ==============================================================
11:16:37 INFO  Executed sudo&lt;remove_lock&gt;, exit status 0
11:16:38 INFO  Executed sudo&lt;agent_clear&gt;, exit status 0
11:16:39 INFO  Executed sudo&lt;agent_init&gt;, exit status 0
11:16:39 INFO  Executed sudo&lt;pub_req&gt;, exit status 0
11:16:39 INFO  Started sudo&lt;sub_resp&gt; with process id 22986
11:16:40 INFO  Executed sudo&lt;agent_start&gt;, exit status 0
11:16:40 INFO  Waiting for 2.0 seconds
11:16:42 INFO  Executed sudo&lt;agent_stop&gt;, exit status 0
11:16:43 INFO  Executed sudo&lt;sub_stop&gt;, exit status 0
11:16:43 WARN  Grep on sub_resp.out contains "Ld3KgqpcLDlrYH6sfpG7w" ... failed [run.py:87]
11:16:43 INFO  
11:16:43 INFO  Test duration: 5.98 secs
11:16:43 INFO  Test final outcome:  FAILED
11:16:43 INFO  Test outcome reason: Grep on sub_resp.out contains "Ld3KgqpcLDlrYH6sfpG7w"
11:16:43 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="apt_fail_noarg" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="AptPluginFailNoArg" name="apt_fail_noarg">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'" />
		<system-out>11:06:06 INFO  ==============================================================
11:06:06 INFO  Id:    apt_fail_noarg
11:06:06 INFO  Dir:   plugin_apt/
11:06:06 INFO  Title: Validate apt plugin fetures(prepare, list, install, remove finalize) without arguments
11:06:06 INFO  ==============================================================
11:06:06 INFO  Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container' ... skipped
11:06:06 WARN  Aborted test due to SKIPPED outcome
11:06:06 INFO  
11:06:06 INFO  Test duration: 0.07 secs
11:06:06 INFO  Test final outcome:  SKIPPED
11:06:06 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'
11:06:06 INFO  
</system-out>
	</testcase>
<testcase classname="AptPluginFailNoArg" name="apt_fail_noarg" />
</testsuite><testsuite name="apt_finalize" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="AptPluginFinalize" name="apt_finalize">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'" />
		<system-out>11:06:06 INFO  ==============================================================
11:06:06 INFO  Id:    apt_finalize
11:06:06 INFO  Dir:   plugin_apt/
11:06:06 INFO  Title: Validate apt plugin finalize - dense version
11:06:06 INFO  ==============================================================
11:06:06 INFO  Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container' ... skipped
11:06:06 WARN  Aborted test due to SKIPPED outcome
11:06:06 INFO  
11:06:06 INFO  Test duration: 0.03 secs
11:06:06 INFO  Test final outcome:  SKIPPED
11:06:06 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'
11:06:06 INFO  
</system-out>
	</testcase>
<testcase classname="AptPluginFinalize" name="apt_finalize" />
</testsuite><testsuite name="apt_install" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="AptPluginInstallDense" name="apt_install">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'" />
		<system-out>11:06:06 INFO  ==============================================================
11:06:06 INFO  Id:    apt_install
11:06:06 INFO  Dir:   plugin_apt/
11:06:06 INFO  Title: Validate apt plugin prepare - dense version
11:06:06 INFO  ==============================================================
11:06:06 INFO  Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container' ... skipped
11:06:06 WARN  Aborted test due to SKIPPED outcome
11:06:06 INFO  
11:06:06 INFO  Test duration: 0.02 secs
11:06:06 INFO  Test final outcome:  SKIPPED
11:06:06 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'
11:06:06 INFO  
</system-out>
	</testcase>
<testcase classname="AptPluginInstallDense" name="apt_install" />
</testsuite><testsuite name="apt_install_fail" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="AptPluginInstallFail" name="apt_install_fail">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'" />
		<system-out>11:06:06 INFO  ==============================================================
11:06:06 INFO  Id:    apt_install_fail
11:06:06 INFO  Dir:   plugin_apt/
11:06:06 INFO  Title: Validate apt plugin prepare - failing
11:06:06 INFO  ==============================================================
11:06:06 INFO  Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container' ... skipped
11:06:06 WARN  Aborted test due to SKIPPED outcome
11:06:06 INFO  
11:06:06 INFO  Test duration: 0.02 secs
11:06:06 INFO  Test final outcome:  SKIPPED
11:06:06 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'
11:06:06 INFO  
</system-out>
	</testcase>
<testcase classname="AptPluginInstallFail" name="apt_install_fail" />
</testsuite><testsuite name="apt_install_local_file" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="AptPluginInstallFromLocalFile" name="apt_install_local_file">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'" />
		<system-out>11:06:06 INFO  ==============================================================
11:06:06 INFO  Id:    apt_install_local_file
11:06:06 INFO  Dir:   plugin_apt/
11:06:06 INFO  Title: Validate apt plugin install from local file - SUCCESS case
11:06:06 INFO  ==============================================================
11:06:06 INFO  Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container' ... skipped
11:06:06 WARN  Aborted test due to SKIPPED outcome
11:06:06 INFO  
11:06:06 INFO  Test duration: 0.03 secs
11:06:06 INFO  Test final outcome:  SKIPPED
11:06:06 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'
11:06:06 INFO  
</system-out>
	</testcase>
<testcase classname="AptPluginInstallFromLocalFile" name="apt_install_local_file" />
</testsuite><testsuite name="apt_install_local_file_fail" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="AptPluginInstallFromLocalFileFail" name="apt_install_local_file_fail">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'" />
		<system-out>11:06:06 INFO  ==============================================================
11:06:06 INFO  Id:    apt_install_local_file_fail
11:06:06 INFO  Dir:   plugin_apt/
11:06:06 INFO  Title: Validate apt plugin install from local file - FAIL case
11:06:06 INFO  ==============================================================
11:06:06 INFO  Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container' ... skipped
11:06:06 WARN  Aborted test due to SKIPPED outcome
11:06:06 INFO  
11:06:06 INFO  Test duration: 0.02 secs
11:06:06 INFO  Test final outcome:  SKIPPED
11:06:06 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'
11:06:06 INFO  
</system-out>
	</testcase>
<testcase classname="AptPluginInstallFromLocalFileFail" name="apt_install_local_file_fail" />
</testsuite><testsuite name="apt_install_local_file_with_version" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="AptPluginInstallFromLocalFileWithVersion" name="apt_install_local_file_with_version">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'" />
		<system-out>11:06:06 INFO  ==============================================================
11:06:06 INFO  Id:    apt_install_local_file_with_version
11:06:06 INFO  Dir:   plugin_apt/
11:06:06 INFO  Title: Validate apt plugin install from local file AND with a version - SUCCESS case
11:06:06 INFO  ==============================================================
11:06:06 INFO  Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container' ... skipped
11:06:06 WARN  Aborted test due to SKIPPED outcome
11:06:06 INFO  
11:06:06 INFO  Test duration: 0.02 secs
11:06:06 INFO  Test final outcome:  SKIPPED
11:06:06 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'
11:06:06 INFO  
</system-out>
	</testcase>
<testcase classname="AptPluginInstallFromLocalFileWithVersion" name="apt_install_local_file_with_version" />
</testsuite><testsuite name="apt_install_local_file_with_version_fail" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="AptPluginInstallFromLocalFileWithVersionFail" name="apt_install_local_file_with_version_fail">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'" />
		<system-out>11:06:06 INFO  ==============================================================
11:06:06 INFO  Id:    apt_install_local_file_with_version_fail
11:06:06 INFO  Dir:   plugin_apt/
11:06:06 INFO  Title: Validate apt plugin install from local file AND with a version - FAIL case
11:06:06 INFO  ==============================================================
11:06:06 INFO  Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container' ... skipped
11:06:06 WARN  Aborted test due to SKIPPED outcome
11:06:06 INFO  
11:06:06 INFO  Test duration: 0.02 secs
11:06:06 INFO  Test final outcome:  SKIPPED
11:06:06 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'
11:06:06 INFO  
</system-out>
	</testcase>
<testcase classname="AptPluginInstallFromLocalFileWithVersionFail" name="apt_install_local_file_with_version_fail" />
</testsuite><testsuite name="apt_list_format" tests="2" errors="0" failures="0" skipped="0" time="0"><testcase classname="AptPluginListFormat" name="apt_list_format" />
<testcase classname="AptPluginListFormat" name="apt_list_format" />
</testsuite><testsuite name="apt_prepare" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="AptPluginPrepare" name="apt_prepare">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'" />
		<system-out>11:06:10 INFO  ==============================================================
11:06:10 INFO  Id:    apt_prepare
11:06:10 INFO  Dir:   plugin_apt/
11:06:10 INFO  Title: Validate apt plugin install - dense version
11:06:10 INFO  ==============================================================
11:06:10 INFO  Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container' ... skipped
11:06:10 WARN  Aborted test due to SKIPPED outcome
11:06:10 INFO  
11:06:10 INFO  Test duration: 0.02 secs
11:06:10 INFO  Test final outcome:  SKIPPED
11:06:10 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'
11:06:10 INFO  
</system-out>
	</testcase>
<testcase classname="AptPluginPrepare" name="apt_prepare" />
</testsuite><testsuite name="apt_prepare_install_finalize" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="AptPluginPrepareInstallFinalize" name="apt_prepare_install_finalize">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'" />
		<system-out>11:06:10 INFO  ==============================================================
11:06:10 INFO  Id:    apt_prepare_install_finalize
11:06:10 INFO  Dir:   plugin_apt/
11:06:10 INFO  Title: Validate apt plugin install use case
11:06:10 INFO  ==============================================================
11:06:10 INFO  Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container' ... skipped
11:06:10 WARN  Aborted test due to SKIPPED outcome
11:06:10 INFO  
11:06:10 INFO  Test duration: 0.02 secs
11:06:10 INFO  Test final outcome:  SKIPPED
11:06:10 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'
11:06:10 INFO  
</system-out>
	</testcase>
<testcase classname="AptPluginPrepareInstallFinalize" name="apt_prepare_install_finalize" />
</testsuite><testsuite name="apt_remove" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="AptPluginRemoveDense" name="apt_remove">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'" />
		<system-out>11:06:10 INFO  ==============================================================
11:06:10 INFO  Id:    apt_remove
11:06:10 INFO  Dir:   plugin_apt/
11:06:10 INFO  Title: Validate apt plugin prepare - dense version
11:06:10 INFO  ==============================================================
11:06:10 INFO  Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container' ... skipped
11:06:10 WARN  Aborted test due to SKIPPED outcome
11:06:10 INFO  
11:06:10 INFO  Test duration: 0.02 secs
11:06:10 INFO  Test final outcome:  SKIPPED
11:06:10 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'
11:06:10 INFO  
</system-out>
	</testcase>
<testcase classname="AptPluginRemoveDense" name="apt_remove" />
</testsuite><testsuite name="apt_remove_fail" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="AptPluginRemoveFails" name="apt_remove_fail">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'" />
		<system-out>11:06:10 INFO  ==============================================================
11:06:10 INFO  Id:    apt_remove_fail
11:06:10 INFO  Dir:   plugin_apt/
11:06:10 INFO  Title: Validate apt plugin prepare - failing
11:06:10 INFO  ==============================================================
11:06:10 INFO  Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container' ... skipped
11:06:10 WARN  Aborted test due to SKIPPED outcome
11:06:10 INFO  
11:06:10 INFO  Test duration: 0.02 secs
11:06:10 INFO  Test final outcome:  SKIPPED
11:06:10 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'
11:06:10 INFO  
</system-out>
	</testcase>
<testcase classname="AptPluginRemoveFails" name="apt_remove_fail" />
</testsuite><testsuite name="apt_sequence_install_with_version" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="AptPluginPrepInstallWithVersionFinalize" name="apt_sequence_install_with_version">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'" />
		<system-out>11:06:10 INFO  ==============================================================
11:06:10 INFO  Id:    apt_sequence_install_with_version
11:06:10 INFO  Dir:   plugin_apt/
11:06:10 INFO  Title: Validate apt plugin install with version use case
11:06:10 INFO  ==============================================================
11:06:10 INFO  Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container' ... skipped
11:06:10 WARN  Aborted test due to SKIPPED outcome
11:06:10 INFO  
11:06:10 INFO  Test duration: 0.02 secs
11:06:10 INFO  Test final outcome:  SKIPPED
11:06:10 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'
11:06:10 INFO  
</system-out>
	</testcase>
<testcase classname="AptPluginPrepInstallWithVersionFinalize" name="apt_sequence_install_with_version" />
</testsuite><testsuite name="apt_sequence_install_with_version_fail" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="AptPluginInstallWithVersionFails" name="apt_sequence_install_with_version_fail">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'" />
		<system-out>11:06:10 INFO  ==============================================================
11:06:10 INFO  Id:    apt_sequence_install_with_version_fail
11:06:10 INFO  Dir:   plugin_apt/
11:06:10 INFO  Title: Validate apt plugin install with version fails use case
11:06:10 INFO  ==============================================================
11:06:10 INFO  Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container' ... skipped
11:06:10 WARN  Aborted test due to SKIPPED outcome
11:06:10 INFO  
11:06:10 INFO  Test duration: 0.02 secs
11:06:10 INFO  Test final outcome:  SKIPPED
11:06:10 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'
11:06:10 INFO  
</system-out>
	</testcase>
<testcase classname="AptPluginInstallWithVersionFails" name="apt_sequence_install_with_version_fail" />
</testsuite><testsuite name="apt_sequence_remove" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="AptPluginInstallPrepareRemoveFinalize" name="apt_sequence_remove">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'" />
		<system-out>11:06:10 INFO  ==============================================================
11:06:10 INFO  Id:    apt_sequence_remove
11:06:10 INFO  Dir:   plugin_apt/
11:06:10 INFO  Title: Validate apt plugin prepare install remove finalize use case
11:06:10 INFO  ==============================================================
11:06:10 INFO  Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container' ... skipped
11:06:10 WARN  Aborted test due to SKIPPED outcome
11:06:10 INFO  
11:06:10 INFO  Test duration: 0.02 secs
11:06:10 INFO  Test final outcome:  SKIPPED
11:06:10 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'
11:06:10 INFO  
</system-out>
	</testcase>
<testcase classname="AptPluginInstallPrepareRemoveFinalize" name="apt_sequence_remove" />
</testsuite><testsuite name="apt_sequence_remove_with_version" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="AptPluginRemoveWithVersion" name="apt_sequence_remove_with_version">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'" />
		<system-out>11:06:10 INFO  ==============================================================
11:06:10 INFO  Id:    apt_sequence_remove_with_version
11:06:10 INFO  Dir:   plugin_apt/
11:06:10 INFO  Title: Validate apt plugin remove with version use case
11:06:10 INFO  ==============================================================
11:06:10 INFO  Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container' ... skipped
11:06:10 WARN  Aborted test due to SKIPPED outcome
11:06:10 INFO  
11:06:10 INFO  Test duration: 0.02 secs
11:06:10 INFO  Test final outcome:  SKIPPED
11:06:10 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'
11:06:10 INFO  
</system-out>
	</testcase>
<testcase classname="AptPluginRemoveWithVersion" name="apt_sequence_remove_with_version" />
</testsuite><testsuite name="apt_sequence_remove_with_version_fail" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="AptPluginRemoveWithVersionFails" name="apt_sequence_remove_with_version_fail">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'" />
		<system-out>11:06:10 INFO  ==============================================================
11:06:10 INFO  Id:    apt_sequence_remove_with_version_fail
11:06:10 INFO  Dir:   plugin_apt/
11:06:10 INFO  Title: Validate apt plugin remove with version fails when the version not found
11:06:10 INFO  ==============================================================
11:06:10 INFO  Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container' ... skipped
11:06:10 WARN  Aborted test due to SKIPPED outcome
11:06:10 INFO  
11:06:10 INFO  Test duration: 0.02 secs
11:06:10 INFO  Test final outcome:  SKIPPED
11:06:10 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'
11:06:10 INFO  
</system-out>
	</testcase>
<testcase classname="AptPluginRemoveWithVersionFails" name="apt_sequence_remove_with_version_fail" />
</testsuite><testsuite name="apt_update_list" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="AptPluginUpdateList" name="apt_update_list">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'" />
		<system-out>11:06:10 INFO  ==============================================================
11:06:10 INFO  Id:    apt_update_list
11:06:10 INFO  Dir:   plugin_apt/
11:06:10 INFO  Title: Validate apt plugin update-list command use case
11:06:10 INFO  ==============================================================
11:06:10 INFO  Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container' ... skipped
11:06:10 WARN  Aborted test due to SKIPPED outcome
11:06:10 INFO  
11:06:10 INFO  Test duration: 0.02 secs
11:06:10 INFO  Test final outcome:  SKIPPED
11:06:10 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'
11:06:10 INFO  
</system-out>
	</testcase>
<testcase classname="AptPluginUpdateList" name="apt_update_list" />
</testsuite><testsuite name="apt_wrong_option" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="AptPluginWrongOption" name="apt_wrong_option">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'" />
		<system-out>11:06:10 INFO  ==============================================================
11:06:10 INFO  Id:    apt_wrong_option
11:06:10 INFO  Dir:   plugin_apt/
11:06:10 INFO  Title: Validate apt plugin install
11:06:10 INFO  ==============================================================
11:06:10 INFO  Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container' ... skipped
11:06:10 WARN  Aborted test due to SKIPPED outcome
11:06:10 INFO  
11:06:10 INFO  Test duration: 0.02 secs
11:06:10 INFO  Test final outcome:  SKIPPED
11:06:10 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'
11:06:10 INFO  
</system-out>
	</testcase>
<testcase classname="AptPluginWrongOption" name="apt_wrong_option" />
</testsuite><testsuite name="c8y_jwt_token_retrieval" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="ValidateJWTTokenRetrieval" name="c8y_jwt_token_retrieval" />
</testsuite><testsuite name="c8y_restart_bridge" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="RestartBridge" name="c8y_restart_bridge" />
</testsuite><testsuite name="call_tedge_-V" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="PySysTest" name="call_tedge_-V" />
</testsuite><testsuite name="call_tedge_-h" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="PySysTest" name="call_tedge_-h" />
</testsuite><testsuite name="call_tedge_-h_-V" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="PySysTest" name="call_tedge_-h_-V" />
</testsuite><testsuite name="call_tedge_config_help" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="PySysTest" name="call_tedge_config_help" />
</testsuite><testsuite name="call_tedge_config_list" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="PySysTest" name="call_tedge_config_list" />
</testsuite><testsuite name="custom_init_system" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="CustomInitSystem" name="custom_init_system" />
</testsuite><testsuite name="docker_plugin_finalize" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="DockerPluginFinalizeTest" name="docker_plugin_finalize">
		<skipped message="SKIPPED: Testing the docker plugin is not supported on this platform.To run it, all the test with -XmyPlatform='container'" />
		<system-out>11:06:10 INFO  ==============================================================
11:06:10 INFO  Id:    docker_plugin_finalize
11:06:10 INFO  Dir:   plugin_docker/
11:06:10 INFO  Title: Validate docker plugin finalize command
11:06:10 INFO  ==============================================================
11:06:10 INFO  Testing the docker plugin is not supported on this platform.To run it, all the test with -XmyPlatform='container' ... skipped
11:06:10 WARN  Aborted test due to SKIPPED outcome
11:06:10 INFO  
11:06:10 INFO  Test duration: 0.05 secs
11:06:10 INFO  Test final outcome:  SKIPPED
11:06:10 INFO  Test outcome reason: Testing the docker plugin is not supported on this platform.To run it, all the test with -XmyPlatform='container'
11:06:10 INFO  
</system-out>
	</testcase>
<testcase classname="DockerPluginFinalizeTest" name="docker_plugin_finalize" />
</testsuite><testsuite name="docker_plugin_install" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="DockerPluginInstallTest" name="docker_plugin_install">
		<skipped message="SKIPPED: Testing the docker plugin is not supported on this platform.To run it, all the test with -XmyPlatform='container'" />
		<system-out>11:06:10 INFO  ==============================================================
11:06:10 INFO  Id:    docker_plugin_install
11:06:10 INFO  Dir:   plugin_docker/
11:06:10 INFO  Title: Validate docker plugin install
11:06:10 INFO  ==============================================================
11:06:10 INFO  Testing the docker plugin is not supported on this platform.To run it, all the test with -XmyPlatform='container' ... skipped
11:06:10 WARN  Aborted test due to SKIPPED outcome
11:06:10 INFO  
11:06:10 INFO  Test duration: 0.02 secs
11:06:10 INFO  Test final outcome:  SKIPPED
11:06:10 INFO  Test outcome reason: Testing the docker plugin is not supported on this platform.To run it, all the test with -XmyPlatform='container'
11:06:10 INFO  
</system-out>
	</testcase>
<testcase classname="DockerPluginInstallTest" name="docker_plugin_install" />
</testsuite><testsuite name="docker_plugin_install_with_version" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="DockerPluginInstallWithVersionTest" name="docker_plugin_install_with_version">
		<skipped message="SKIPPED: Testing the docker plugin is not supported on this platform.To run it, all the test with -XmyPlatform='container'" />
		<system-out>11:06:11 INFO  ==============================================================
11:06:11 INFO  Id:    docker_plugin_install_with_version
11:06:11 INFO  Dir:   plugin_docker/
11:06:11 INFO  Title: Validate docker plugin install
11:06:11 INFO  ==============================================================
11:06:11 INFO  Testing the docker plugin is not supported on this platform.To run it, all the test with -XmyPlatform='container' ... skipped
11:06:11 WARN  Aborted test due to SKIPPED outcome
11:06:11 INFO  
11:06:11 INFO  Test duration: 0.02 secs
11:06:11 INFO  Test final outcome:  SKIPPED
11:06:11 INFO  Test outcome reason: Testing the docker plugin is not supported on this platform.To run it, all the test with -XmyPlatform='container'
11:06:11 INFO  
</system-out>
	</testcase>
<testcase classname="DockerPluginInstallWithVersionTest" name="docker_plugin_install_with_version" />
</testsuite><testsuite name="docker_plugin_remove" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="DockerPluginRemoveTest" name="docker_plugin_remove">
		<skipped message="SKIPPED: Testing the docker plugin is not supported on this platform.To run it, all the test with -XmyPlatform='container'" />
		<system-out>11:06:11 INFO  ==============================================================
11:06:11 INFO  Id:    docker_plugin_remove
11:06:11 INFO  Dir:   plugin_docker/
11:06:11 INFO  Title: Validate docker plugin remove
11:06:11 INFO  ==============================================================
11:06:11 INFO  Testing the docker plugin is not supported on this platform.To run it, all the test with -XmyPlatform='container' ... skipped
11:06:11 WARN  Aborted test due to SKIPPED outcome
11:06:11 INFO  
11:06:11 INFO  Test duration: 0.02 secs
11:06:11 INFO  Test final outcome:  SKIPPED
11:06:11 INFO  Test outcome reason: Testing the docker plugin is not supported on this platform.To run it, all the test with -XmyPlatform='container'
11:06:11 INFO  
</system-out>
	</testcase>
<testcase classname="DockerPluginRemoveTest" name="docker_plugin_remove" />
</testsuite><testsuite name="docker_plugin_remove_with_version" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="DockerPluginRemoveWithVersionTest" name="docker_plugin_remove_with_version">
		<skipped message="SKIPPED: Testing the docker plugin is not supported on this platform.To run it, all the test with -XmyPlatform='container'" />
		<system-out>11:06:11 INFO  ==============================================================
11:06:11 INFO  Id:    docker_plugin_remove_with_version
11:06:11 INFO  Dir:   plugin_docker/
11:06:11 INFO  Title: Validate docker plugin remove with version
11:06:11 INFO  ==============================================================
11:06:11 INFO  Testing the docker plugin is not supported on this platform.To run it, all the test with -XmyPlatform='container' ... skipped
11:06:11 WARN  Aborted test due to SKIPPED outcome
11:06:11 INFO  
11:06:11 INFO  Test duration: 0.02 secs
11:06:11 INFO  Test final outcome:  SKIPPED
11:06:11 INFO  Test outcome reason: Testing the docker plugin is not supported on this platform.To run it, all the test with -XmyPlatform='container'
11:06:11 INFO  
</system-out>
	</testcase>
<testcase classname="DockerPluginRemoveWithVersionTest" name="docker_plugin_remove_with_version" />
</testsuite><testsuite name="docker_plugin_update" tests="2" errors="0" failures="1" skipped="1" time="0"><testcase classname="DockerPluginUpdateTest" name="docker_plugin_update">
		<skipped message="SKIPPED: Testing the docker plugin is not supported on this platform.To run it, all the test with -XmyPlatform='container'" />
		<system-out>11:06:11 INFO  ==============================================================
11:06:11 INFO  Id:    docker_plugin_update
11:06:11 INFO  Dir:   plugin_docker/
11:06:11 INFO  Title: Validate docker plugin install updates existing containers
11:06:11 INFO  ==============================================================
11:06:11 INFO  Testing the docker plugin is not supported on this platform.To run it, all the test with -XmyPlatform='container' ... skipped
11:06:11 WARN  Aborted test due to SKIPPED outcome
11:06:11 INFO  
11:06:11 INFO  Test duration: 0.02 secs
11:06:11 INFO  Test final outcome:  SKIPPED
11:06:11 INFO  Test outcome reason: Testing the docker plugin is not supported on this platform.To run it, all the test with -XmyPlatform='container'
11:06:11 INFO  
</system-out>
	</testcase>
<testcase classname="DockerPluginUpdateTest" name="docker_plugin_update">
		<failure message="BLOCKED: sudo&lt;docker_run&gt; returned non-zero exit code 125" type="BLOCKED" />
		<system-out>11:48:25 INFO  ==============================================================
11:48:25 INFO  Id:    docker_plugin_update
11:48:25 INFO  Dir:   plugin_docker/
11:48:25 INFO  Title: Validate docker plugin install updates existing containers
11:48:25 INFO  ==============================================================
11:48:26 INFO  Executed sudo&lt;docker_images&gt;, exit status 0
11:48:26 INFO  Grep on file /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_update/Output/linux/docker_images.out ... passed
11:48:28 WARN  Executed sudo&lt;docker_run&gt;, exit status 125
11:48:28 INFO  Contents of docker_run.err: 
  Unable to find image 'registry:2.6.2' locally
  docker: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.
  See 'docker run --help'.
  -----

11:48:28 WARN  sudo&lt;docker_run&gt; returned non-zero exit code 125 ... blocked 
11:48:28 WARN  Aborted test due to BLOCKED outcome
11:48:28 INFO  
11:48:28 INFO  cleanup:
11:48:28 INFO  Removing containers scheduled to be cleaned up: ['da41f8e4638e', '056afe6ee369', '50fccbefa91142e3aa267bf2d4fee2b02c6d713e07780e57780b6976e470bead\n', '3668b2dd9938c2a632e8643c3c4f6ad5c4f4fbb463ae3371f1c0dae331f50cd7\n']
11:48:29 WARN  Executed sudo&lt;containers_for_cleanup&gt;, exit status 1
11:48:29 INFO  Removing images scheduled to be cleaned up: ['registry', 'registry', 'registry:2.7.1', 'registry', 'registry:2.7.1']
11:48:30 INFO  Executed sudo&lt;containers_for_cleanup&gt;, exit status 0
11:48:30 INFO  
11:48:30 INFO  Test duration: 4.99 secs
11:48:30 INFO  Test final outcome:  BLOCKED
11:48:30 INFO  Test outcome reason: sudo&lt;docker_run&gt; returned non-zero exit code 125
11:48:30 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="invalid_device_id" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="InvalidDeviceId" name="invalid_device_id" />
</testsuite><testsuite name="local_mqtt_pub_fail_noqos" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="PySysTest" name="local_mqtt_pub_fail_noqos" />
</testsuite><testsuite name="local_mqtt_pub_fail_qos0" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="PySysTest" name="local_mqtt_pub_fail_qos0" />
</testsuite><testsuite name="local_mqtt_pub_fail_qos1" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="PySysTest" name="local_mqtt_pub_fail_qos1" />
</testsuite><testsuite name="local_mqtt_pub_fail_qos2" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="PySysTest" name="local_mqtt_pub_fail_qos2" />
</testsuite><testsuite name="local_mqtt_pub_sub" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="PySysTest" name="local_mqtt_pub_sub" />
</testsuite><testsuite name="local_mqtt_pub_sub_retain" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="MqttPublishWithRetain" name="local_mqtt_pub_sub_retain" />
</testsuite><testsuite name="local_mqtt_pub_sub_with_sudo" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="PySysTest" name="local_mqtt_pub_sub_with_sudo" />
</testsuite><testsuite name="local_mqtt_sub_fail" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="PySysTest" name="local_mqtt_sub_fail" />
</testsuite><testsuite name="log_request_error_messages" tests="1" errors="0" failures="1" skipped="0" time="0"><testcase classname="LogRequestVerifySearchTextError" name="log_request_error_messages">
		<failure message="FAILED: Assert that (True == value) with value=False" type="FAILED" />
		<system-out>11:03:08 INFO  ==============================================================
11:03:08 INFO  Id:    log_request_error_messages
11:03:08 INFO  Dir:   log_request_end_to_end/
11:03:08 INFO  Title: Validate end to end behaviour for the log request operation check for error messages
11:03:08 INFO  ==============================================================
11:03:09 INFO  EnvironmentC8y Setup
11:03:10 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
11:03:10 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 3 seconds
11:03:10 INFO  Delaying execution by 8 seconds
11:03:32 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
11:03:33 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
11:03:33 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
11:03:34 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
11:03:34 INFO  Executed sudo&lt;rm_logs&gt;, exit status 0
11:03:35 INFO  Executed sudo&lt;move_logs&gt;, exit status 0
11:03:35 INFO  log response None
11:03:36 WARN  retry, retrying in 1 seconds...
11:03:37 INFO  log response https://thin-edge-io.eu-latest.cumulocity.com/event/events/19021191/binaries
11:03:38 WARN  Assert that (True == value) with value=False ... failed [run.py:43]
11:03:38 INFO  
11:03:38 INFO  cleanup:
11:03:38 INFO  Executed sudo&lt;rm_logs&gt;, exit status 0
11:03:39 INFO  Executed sudo&lt;rm_tmp_logs&gt;, exit status 0
11:03:39 INFO  Executed sudo&lt;send_failed&gt;, exit status 0
11:03:43 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
11:03:44 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
11:03:44 INFO  
11:03:44 INFO  Test duration: 35.63 secs
11:03:44 INFO  Test final outcome:  FAILED
11:03:44 INFO  Test outcome reason: Assert that (True == value) with value=False
11:03:44 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="log_request_num_lines" tests="1" errors="0" failures="1" skipped="0" time="0"><testcase classname="LogRequestVerifyNumberOfLines" name="log_request_num_lines">
		<failure message="FAILED: Assert that (True == value) with value=False" type="FAILED" />
		<system-out>11:03:44 INFO  ==============================================================
11:03:44 INFO  Id:    log_request_num_lines
11:03:44 INFO  Dir:   log_request_end_to_end/
11:03:44 INFO  Title: Validate end to end behaviour for the log request operation check for number of lines
11:03:44 INFO  ==============================================================
11:03:44 INFO  EnvironmentC8y Setup
11:03:44 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
11:03:44 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 5 seconds
11:03:44 INFO  Delaying execution by 6 seconds
11:04:05 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
11:04:05 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
11:04:06 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
11:04:06 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
11:04:07 INFO  Executed sudo&lt;rm_logs&gt;, exit status 0
11:04:07 INFO  Executed sudo&lt;move_logs&gt;, exit status 0
11:04:08 INFO  log response None
11:04:08 WARN  retry, retrying in 1 seconds...
11:04:09 INFO  log response https://thin-edge-io.eu-latest.cumulocity.com/event/events/19021199/binaries
11:04:09 INFO  nlines 0
11:04:09 WARN  Assert that (True == value) with value=False ... failed [run.py:44]
11:04:09 INFO  
11:04:09 INFO  cleanup:
11:04:10 INFO  Executed sudo&lt;rm_logs&gt;, exit status 0
11:04:10 INFO  Executed sudo&lt;rm_tmp_logs&gt;, exit status 0
11:04:11 INFO  Executed sudo&lt;send_failed&gt;, exit status 0
11:04:15 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
11:04:15 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
11:04:15 INFO  
11:04:15 INFO  Test duration: 31.59 secs
11:04:15 INFO  Test final outcome:  FAILED
11:04:15 INFO  Test outcome reason: Assert that (True == value) with value=False
11:04:15 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="mapper_awaits_before_reconnect" tests="1" errors="0" failures="1" skipped="0" time="0"><testcase classname="MapperReconnectAwait" name="mapper_awaits_before_reconnect">
		<failure message="FAILED: Line count on tedge_mapper_journal.out for &quot;tedge_mapper::core::mapper: MQTT connection error:&quot; expected &gt;=2 but got 0" type="FAILED" />
		<system-out>11:18:46 INFO  ==============================================================
11:18:46 INFO  Id:    mapper_awaits_before_reconnect
11:18:46 INFO  Dir:   tedge_mapper_c8y/
11:18:46 INFO  Title: Validate mapper doesn't reconnect too often
11:18:46 INFO  ==============================================================
11:18:46 INFO  Started mosquitto_sub with process id 23747
11:18:46 INFO  Waiting for 0.1 seconds
11:18:47 INFO  Executed sudo&lt;tedge_mapper&gt;, exit status 0
11:18:47 INFO  Waiting for 5.0 seconds
11:18:52 INFO  Executed sudo&lt;tedge_mapper&gt;, exit status 0
11:18:55 INFO  Executed sudo&lt;tedge_mapper_journal&gt;, exit status 0
11:18:55 WARN  Grep on tedge_mapper_journal.out contains "ERROR" ... failed [run.py:67]
11:18:55 INFO  Line count on file tedge_mapper_journal.out ... passed
11:18:55 WARN  Line count on tedge_mapper_journal.out for "tedge_mapper::core::mapper: MQTT connection error:" expected &gt;=2 but got 0 ... failed [run.py:78]
11:18:55 WARN  Aborted test due to FAILED outcome
11:18:55 INFO  
11:18:55 INFO  Test duration: 8.59 secs
11:18:55 INFO  Test final outcome:  FAILED
11:18:55 INFO  Test outcome reason: Line count on tedge_mapper_journal.out for "tedge_mapper::core::mapper: MQTT connection error:" expected &gt;=2 but got 0
11:18:55 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="monitoring_smaller_interval" tests="1" errors="0" failures="1" skipped="0" time="0"><testcase classname="MonitoringSmallInterval" name="monitoring_smaller_interval">
		<failure message="BLOCKED: TypeError: 'int' object is not subscriptable" type="BLOCKED" />
		<system-out>11:05:45 INFO  ==============================================================
11:05:45 INFO  Id:    monitoring_smaller_interval
11:05:45 INFO  Dir:   monitoring/
11:05:45 INFO  Title: Validate the tedge dm agent messages that are produced with smaller sampling interval than the batching window. Here the simulated collectd messages are used
11:05:45 INFO  ==============================================================
11:05:47 INFO  Executed sudo&lt;collectd&gt;, exit status 0
11:05:47 INFO  Executed sudo&lt;collectd_mapper&gt;, exit status 0
11:05:47 INFO  Started sudo&lt;tedge_sub&gt; with process id 19885
11:05:48 INFO  Executed sudo&lt;tedge_temp&gt;, exit status 0
11:05:48 INFO  Executed sudo&lt;tedge_pres&gt;, exit status 0
11:05:49 INFO  Executed sudo&lt;tedge_temp&gt;, exit status 0
11:05:49 INFO  Executed sudo&lt;tedge_pres&gt;, exit status 0
11:05:50 INFO  Executed sudo&lt;tedge_temp&gt;, exit status 0
11:05:51 INFO  Executed sudo&lt;tedge_pres&gt;, exit status 0
11:05:51 INFO  Executed sudo&lt;tedge_temp&gt;, exit status 0
11:05:52 INFO  Executed sudo&lt;tedge_pres&gt;, exit status 0
11:05:52 INFO  Executed sudo&lt;tedge_temp&gt;, exit status 0
11:05:53 INFO  Executed sudo&lt;tedge_pres&gt;, exit status 0
11:05:54 INFO  Executed sudo&lt;tedge_temp&gt;, exit status 0
11:05:54 INFO  Executed sudo&lt;tedge_pres&gt;, exit status 0
11:05:55 INFO  Executed sudo&lt;tedge_temp&gt;, exit status 0
11:05:55 INFO  Executed sudo&lt;tedge_pres&gt;, exit status 0
11:05:56 INFO  Executed sudo&lt;tedge_temp&gt;, exit status 0
11:05:57 INFO  Executed sudo&lt;tedge_pres&gt;, exit status 0
11:05:57 INFO  Executed sudo&lt;tedge_temp&gt;, exit status 0
11:05:58 INFO  Executed sudo&lt;tedge_pres&gt;, exit status 0
11:05:58 INFO  Executed sudo&lt;tedge_temp&gt;, exit status 0
11:05:59 INFO  Executed sudo&lt;tedge_pres&gt;, exit status 0
11:06:00 INFO  Executed sudo&lt;kill_out&gt;, exit status 0
11:06:00 INFO  0

11:06:00 WARN  TypeError occurred while running test - 'int' object is not subscriptable
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1296, in __call__
    self.testObj.validate()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/monitoring/monitoring_smaller_interval/run.py", line 104, in validate
    collectd_msg_validation_result=self.validate_json(),
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/monitoring/monitoring_smaller_interval/run.py", line 114, in validate_json
    if not self.validate_time():
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/monitoring/monitoring_smaller_interval/run.py", line 134, in validate_time
    if self.js_msg["time"]:
TypeError: 'int' object is not subscriptable
11:06:00 WARN  TypeError: 'int' object is not subscriptable ... blocked 
11:06:00 INFO  
11:06:00 INFO  cleanup:
11:06:00 INFO  monitoring_cleanup
11:06:01 INFO  Executed sudo&lt;collectd_mapper&gt;, exit status 0
11:06:01 INFO  
11:06:01 INFO  Test duration: 15.89 secs
11:06:01 INFO  Test final outcome:  BLOCKED
11:06:01 INFO  Test outcome reason: TypeError: 'int' object is not subscriptable
11:06:01 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="monitoring_with_collectd" tests="1" errors="0" failures="0" skipped="1" time="0"><testcase classname="MonitoringWithCollectd" name="monitoring_with_collectd">
		<skipped message="SKIPPED: Test execution disabled due to #792 (instable)" />
		<system-out>11:06:01 INFO  ==============================================================
11:06:01 INFO  Id:    monitoring_with_collectd
11:06:01 INFO  Dir:   monitoring/
11:06:01 INFO  Title: Validate tedge dm agent messages that are produced by batching the collectd messages
11:06:01 INFO  ==============================================================
11:06:01 INFO  Test execution disabled due to #792 (instable) ... skipped
11:06:01 INFO  
11:06:01 INFO  Test duration: 0.02 secs
11:06:01 INFO  Test final outcome:  SKIPPED
11:06:01 INFO  Test outcome reason: Test execution disabled due to #792 (instable)
11:06:01 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="monitoring_with_simulated_messages" tests="1" errors="0" failures="1" skipped="0" time="0"><testcase classname="MonitoringWithSimulatedMessages" name="monitoring_with_simulated_messages">
		<failure message="BLOCKED: TypeError: 'int' object is not subscriptable" type="BLOCKED" />
		<system-out>11:06:01 INFO  ==============================================================
11:06:01 INFO  Id:    monitoring_with_simulated_messages
11:06:01 INFO  Dir:   monitoring/
11:06:01 INFO  Title: Validate the tedge dm agent messages that are produced from the simulated collectd messages
11:06:01 INFO  ==============================================================
11:06:02 INFO  Executed sudo&lt;collectd&gt;, exit status 0
11:06:02 INFO  Executed sudo&lt;collectd_mapper&gt;, exit status 0
11:06:02 INFO  Started sudo&lt;tedge_sub&gt; with process id 19941
11:06:03 INFO  Executed sudo&lt;tedge_temp&gt;, exit status 0
11:06:03 INFO  Executed sudo&lt;tedge_pres&gt;, exit status 0
11:06:05 INFO  Executed sudo&lt;kill_out&gt;, exit status 0
11:06:05 INFO  0

11:06:05 WARN  TypeError occurred while running test - 'int' object is not subscriptable
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1296, in __call__
    self.testObj.validate()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/monitoring/monitoring_with_simulated_messages/run.py", line 98, in validate
    collectd_msg_validation_result=self.validate_json(),
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/monitoring/monitoring_with_simulated_messages/run.py", line 108, in validate_json
    if not self.validate_time():
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/monitoring/monitoring_with_simulated_messages/run.py", line 127, in validate_time
    if self.js_msg["time"]:
TypeError: 'int' object is not subscriptable
11:06:05 WARN  TypeError: 'int' object is not subscriptable ... blocked 
11:06:05 INFO  
11:06:05 INFO  cleanup:
11:06:05 INFO  monitoring_cleanup
11:06:06 INFO  Executed sudo&lt;collectd_mapper&gt;, exit status 0
11:06:06 INFO  
11:06:06 INFO  Test duration: 4.49 secs
11:06:06 INFO  Test final outcome:  BLOCKED
11:06:06 INFO  Test outcome reason: TypeError: 'int' object is not subscriptable
11:06:06 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="mqtt_port_change_connection_fails" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="MqttPortChangeConnectionFails" name="mqtt_port_change_connection_fails" />
</testsuite><testsuite name="mqtt_port_change_connection_works" tests="1" errors="0" failures="0" skipped="1" time="0"><testcase classname="MqttPortChangeConnectionWorks" name="mqtt_port_change_connection_works">
		<skipped message="SKIPPED: failing intermitently" />
		<system-out>11:04:51 INFO  ==============================================================
11:04:51 INFO  Id:    mqtt_port_change_connection_works
11:04:51 INFO  Dir:   misc_features/
11:04:51 INFO  Title: mqtt port change connection works for all the thin-edge services that use the mosquitto broker
11:04:51 INFO  ==============================================================
11:04:51 INFO  failing intermitently ... skipped
11:04:51 INFO  
11:04:51 INFO  Test duration: 0.02 secs
11:04:51 INFO  Test final outcome:  SKIPPED
11:04:51 INFO  Test outcome reason: failing intermitently
11:04:51 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="mqtt_port_set" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="MqttPortSet" name="mqtt_port_set" />
</testsuite><testsuite name="mqtt_port_unset" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="MqttPortUnSet" name="mqtt_port_unset" />
</testsuite><testsuite name="publish_flux" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="PublishFlux" name="publish_flux" />
</testsuite><testsuite name="publish_sawmill" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="PublishSawmill" name="publish_sawmill" />
</testsuite><testsuite name="runtime_start_two_mappers" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="RuntimeMultiMappers" name="runtime_start_two_mappers" />
</testsuite><testsuite name="sm_tedge_mapper_init_session" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="TedgeSMMapperInitSession" name="sm_tedge_mapper_init_session" />
</testsuite><testsuite name="smoketest_json" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="SmokeTestJson" name="smoketest_json" />
</testsuite><testsuite name="smoketest_json_400_samples_10ms" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="SmoketestJson400Samples10ms" name="smoketest_json_400_samples_10ms" />
</testsuite><testsuite name="smoketest_json_400_samples_20ms" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="SmoketestJson400Samples20ms" name="smoketest_json_400_samples_20ms" />
</testsuite><testsuite name="smoketest_smartrest" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="SmoketestSmartRest" name="smoketest_smartrest" />
</testsuite><testsuite name="smoketest_smartrest_400_samples_1Xms" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="SmoketestSmartRest400Samples1Xms" name="smoketest_smartrest_400_samples_1Xms" />
</testsuite><testsuite name="smoketest_smartrest_400_samples_20ms" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="SmoketestSmartRest400Samples20ms" name="smoketest_smartrest_400_samples_20ms" />
</testsuite><testsuite name="tedge_agent_user_sudo_access" tests="1" errors="0" failures="0" skipped="1" time="0"><testcase classname="TedgeAgentUserSudoAccess" name="tedge_agent_user_sudo_access">
		<skipped message="SKIPPED: #955 Observation: Exit code of the apt plugin when called with no arguments" />
		<system-out>11:16:11 INFO  ==============================================================
11:16:11 INFO  Id:    tedge_agent_user_sudo_access
11:16:11 INFO  Dir:   tedge/
11:16:11 INFO  Title: Validate tedge-agent user has a limited sudo right
11:16:11 INFO  ==============================================================
11:16:11 INFO  #955 Observation: Exit code of the apt plugin when called with no arguments ... skipped
11:16:11 INFO  
11:16:11 INFO  Test duration: 0.02 secs
11:16:11 INFO  Test final outcome:  SKIPPED
11:16:11 INFO  Test outcome reason: #955 Observation: Exit code of the apt plugin when called with no arguments
11:16:11 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="tedge_connect_test_negative" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="TedgeConnectTestNegative" name="tedge_connect_test_negative" />
</testsuite><testsuite name="tedge_connect_test_positive" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="TedgeConnectTestPositive" name="tedge_connect_test_positive" />
</testsuite><testsuite name="tedge_connect_test_sm_services" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="TedgeConnectTestSMServices" name="tedge_connect_test_sm_services" />
</testsuite><testsuite name="tedge_disconnect_test_sm_services" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="TedgeDisConnectTestSMServices" name="tedge_disconnect_test_sm_services" />
</testsuite><testsuite name="tedge_mapper_az_negative" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="TedgeMapperAzError" name="tedge_mapper_az_negative" />
</testsuite><testsuite name="tedge_mapper_az_with_timestamp" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="TedgeMapperAzWithTimestamp" name="tedge_mapper_az_with_timestamp" />
</testsuite><testsuite name="tedge_mapper_az_without_timestamp" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="TedgeMapperAzWithoutTimestamp" name="tedge_mapper_az_without_timestamp" />
</testsuite><testsuite name="tedge_mapper_c8y_alarms" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="TedgeMapperC8yAlarm" name="tedge_mapper_c8y_alarms" />
</testsuite><testsuite name="tedge_mapper_c8y_child_device_measurement" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="TedgeMapperC8yChildDevice" name="tedge_mapper_c8y_child_device_measurement" />
</testsuite><testsuite name="tedge_mapper_c8y_packet_threshold_size" tests="1" errors="0" failures="1" skipped="0" time="0"><testcase classname="TedgeMapperC8yThresholdPacketSize" name="tedge_mapper_c8y_packet_threshold_size">
		<failure message="FAILED: Grep on tedge_sub.out contains &quot;The size of the message received on tedge/measurements is 20489 which is greater than the threshold size of 16184.&quot;" type="FAILED" />
		<system-out>11:20:31 INFO  ==============================================================
11:20:31 INFO  Id:    tedge_mapper_c8y_packet_threshold_size
11:20:31 INFO  Dir:   tedge_mapper_c8y/
11:20:31 INFO  Title: Validate the Cumulocity Mapper accepted threshold packet size when it receives a message on tedge/measurements
11:20:31 INFO  ==============================================================
11:20:32 INFO  Executed sudo&lt;tedge_mapper_c8y&gt;, exit status 0
11:20:32 INFO  Started sudo&lt;tedge_sub&gt; with process id 24338
11:20:33 INFO  Executed sudo&lt;tedge_msg&gt;, exit status 0
11:20:33 INFO  Executed sudo&lt;tedge_pub&gt;, exit status 0
11:20:34 INFO  Executed sudo&lt;kill_out&gt;, exit status 0
11:20:34 WARN  Grep on tedge_sub.out contains "The size of the message received on tedge/measurements is 20489 which is greater than the threshold size of 16184." ... failed [run.py:88]
11:20:34 INFO  
11:20:34 INFO  cleanup:
11:20:34 INFO  mapper_cleanup
11:20:34 INFO  Executed sudo&lt;tedge_mapper_c8y&gt;, exit status 0
11:20:34 INFO  
11:20:34 INFO  Test duration: 3.20 secs
11:20:34 INFO  Test final outcome:  FAILED
11:20:34 INFO  Test outcome reason: Grep on tedge_sub.out contains "The size of the message received on tedge/measurements is 20489 which is greater than the threshold size of 16184."
11:20:34 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="tedge_software_update" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="PySysTest" name="tedge_software_update" />
</testsuite><testsuite name="valid_device_id" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="ValidateValidDeviceId" name="valid_device_id" />
</testsuite></testsuites>