<?xml version='1.0' encoding='utf-8'?>
<testsuites tests="147" failures="27" errors="0" skipped="45" time="0.0"><testsuite name="SoftwareManagement.Plugin.apama_plugin_install" tests="3" errors="0" failures="2" skipped="1" time="0"><testcase classname="ApamaPluginInstallTest" name="SoftwareManagement.Plugin.apama_plugin_install">
		<skipped message="SKIPPED: Apama plugin tests are disabled by default. Execute `pysys run` with `-XmyPlatform=container` to run these tests" />
		<system-out>17:30:51 INFO  ==============================================================
17:30:51 INFO  Id:    SoftwareManagement.Plugin.apama_plugin_install
17:30:51 INFO  Dir:   plugin_apama/
17:30:51 INFO  Title: Validate apama plugin install
17:30:51 INFO  ==============================================================
17:30:51 INFO  Apama plugin tests are disabled by default. Execute `pysys run` with `-XmyPlatform=container` to run these tests ... skipped
17:30:51 WARN  Aborted test due to SKIPPED outcome
17:30:51 INFO  
17:30:51 INFO  Test duration: 0.05 secs
17:30:51 INFO  Test final outcome:  SKIPPED
17:30:51 INFO  Test outcome reason: Apama plugin tests are disabled by default. Execute `pysys run` with `-XmyPlatform=container` to run these tests
17:30:51 INFO  
</system-out>
	</testcase>
<testcase classname="ApamaPluginInstallTest" name="SoftwareManagement.Plugin.apama_plugin_install">
		<failure message="BLOCKED: sudo&lt;plugin_install&gt; returned non-zero exit code 2" type="BLOCKED" />
		<system-out>18:21:57 INFO  ==============================================================
18:21:57 INFO  Id:    SoftwareManagement.Plugin.apama_plugin_install
18:21:57 INFO  Dir:   plugin_apama/
18:21:57 INFO  Title: Validate apama plugin install
18:21:57 INFO  ==============================================================
18:21:57 INFO  Assertion that path exists=False for "/etc/tedge/apama/project" ... passed
18:22:09 WARN  Executed sudo&lt;plugin_install&gt;, exit status 2, duration 11 secs
18:22:09 INFO  Contents of plugin_install.err: 
  Failed to connect to remote component: Failed to connect to localhost:15903: Connection refused
  ERROR: Execution of `/opt/softwareag/Apama/bin/apama_env` failed with exit status exit status: 1
  -----

18:22:09 WARN  sudo&lt;plugin_install&gt; returned non-zero exit code 2 ... blocked [run.py:29]
18:22:09 WARN  Aborted test due to BLOCKED outcome
18:22:09 INFO  
18:22:09 INFO  cleanup:
18:22:09 INFO  Removing apama project
18:22:10 INFO  Executed sudo&lt;remove_apama_project&gt;, exit status 0
18:22:27 INFO  Executed sudo&lt;stop_apama_service&gt;, exit status 0, duration 17 secs
18:22:28 INFO  Executed sudo&lt;remove_apama_tmp_dir&gt;, exit status 0
18:22:28 INFO  
18:22:28 INFO  Test duration: 30.94 secs
18:22:28 INFO  Test final outcome:  BLOCKED
18:22:28 INFO  Test outcome reason: sudo&lt;plugin_install&gt; returned non-zero exit code 2
18:22:28 INFO  
</system-out>
	</testcase>
<testcase classname="ApamaPluginInstallTest" name="SoftwareManagement.Plugin.apama_plugin_install">
		<failure message="BLOCKED: sudo&lt;plugin_install&gt; returned non-zero exit code 2 (+2 other failures)" type="BLOCKED" />
		<system-out>18:29:42 INFO  ==============================================================
18:29:42 INFO  Id:    SoftwareManagement.Plugin.apama_plugin_install
18:29:42 INFO  Dir:   plugin_apama/
18:29:42 INFO  Title: Validate apama plugin install
18:29:42 INFO  ==============================================================
18:29:43 WARN  Assertion that path exists=False for "/etc/tedge/apama/project" ... failed 
18:29:43 WARN  Executed sudo&lt;plugin_install&gt;, exit status 2
18:29:43 INFO  Contents of plugin_install.err: 
  ERROR: Device or resource busy (os error 16)
  -----

18:29:43 WARN  sudo&lt;plugin_install&gt; returned non-zero exit code 2 ... blocked [run.py:29]
18:29:43 WARN  Aborted test due to BLOCKED outcome
18:29:43 INFO  
18:29:43 INFO  cleanup:
18:29:43 INFO  Removing apama project
18:29:44 WARN  Executed sudo&lt;remove_apama_project&gt;, exit status 1
18:29:44 INFO  Contents of remove_apama_project.err: 
  rm: cannot remove '/etc/tedge/apama/project/logs/.nfs00000000000e13ec00003dec': Device or resource busy
  -----

18:29:44 ERROR Error while running cleanup function: 
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py", line 1305, in cleanup
    fn()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apama/environment_apama_plugin.py", line 144, in cleanup_project
    self.remove_project()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apama/environment_apama_plugin.py", line 95, in remove_project
    stdouterr="remove_apama_project",
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py", line 482, in startProcess
    abortOnError=abortOnError)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py", line 1401, in addOutcome
    self.abort(outcome, outcomeReason, callRecord)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py", line 1420, in abort
    raise AbortExecution(outcome, outcomeReason, callRecord)
pysys.exceptions.AbortExecution: sudo&lt;remove_apama_project&gt; returned non-zero exit code 1
18:29:44 WARN  Cleanup failed with 1 errors: Cleanup function failed: sudo&lt;remove_apama_project&gt; returned non-zero exit code 1 (AbortExecution) ... blocked 
18:29:44 INFO  
18:29:44 INFO  Test duration: 1.44 secs
18:29:44 INFO  Test final outcome:  BLOCKED
18:29:44 INFO  Test outcome reason: sudo&lt;plugin_install&gt; returned non-zero exit code 2 (+2 other failures)
18:29:44 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="SoftwareManagement.Plugin.apama_plugin_mon_support" tests="3" errors="0" failures="2" skipped="1" time="0"><testcase classname="ApamaPluginMonSupportTest" name="SoftwareManagement.Plugin.apama_plugin_mon_support">
		<skipped message="SKIPPED: Apama plugin tests are disabled by default. Execute `pysys run` with `-XmyPlatform=container` to run these tests" />
		<system-out>17:30:51 INFO  ==============================================================
17:30:51 INFO  Id:    SoftwareManagement.Plugin.apama_plugin_mon_support
17:30:51 INFO  Dir:   plugin_apama/
17:30:51 INFO  Title: Validate mon file support of apama plugin
17:30:51 INFO  ==============================================================
17:30:51 INFO  Apama plugin tests are disabled by default. Execute `pysys run` with `-XmyPlatform=container` to run these tests ... skipped
17:30:51 WARN  Aborted test due to SKIPPED outcome
17:30:51 INFO  
17:30:51 INFO  Test duration: 0.02 secs
17:30:51 INFO  Test final outcome:  SKIPPED
17:30:51 INFO  Test outcome reason: Apama plugin tests are disabled by default. Execute `pysys run` with `-XmyPlatform=container` to run these tests
17:30:51 INFO  
</system-out>
	</testcase>
<testcase classname="ApamaPluginMonSupportTest" name="SoftwareManagement.Plugin.apama_plugin_mon_support">
		<failure message="BLOCKED: sudo&lt;remove_apama_project&gt; returned non-zero exit code 1 (+1 other failures)" type="BLOCKED" />
		<system-out>18:22:28 INFO  ==============================================================
18:22:28 INFO  Id:    SoftwareManagement.Plugin.apama_plugin_mon_support
18:22:28 INFO  Dir:   plugin_apama/
18:22:28 INFO  Title: Validate mon file support of apama plugin
18:22:28 INFO  ==============================================================
18:22:28 INFO  Assertion that path exists=False for "/etc/tedge/apama/project" ... passed
18:22:29 INFO  Executed sudo&lt;create_project_dir&gt;, exit status 0
18:22:29 INFO  Executed sudo&lt;unzip_apama_project&gt;, exit status 0
18:22:30 INFO  Executed sudo&lt;move_apama_project&gt;, exit status 0
18:22:31 INFO  Executed sudo&lt;restart_apama_service&gt;, exit status 0
18:22:31 INFO  Executed sudo&lt;apama_correlator_wait&gt;, exit status 0
18:22:32 INFO  Executed sudo&lt;apama_list_monitors&gt;, exit status 0
18:22:32 INFO  Grep on file /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apama/apama_plugin_mon_support/Output/linux/apama_list_monitors.out ... passed
18:22:33 INFO  Executed sudo&lt;plugin_list_before_install&gt;, exit status 0
18:22:34 INFO  Executed sudo&lt;plugin_install&gt;, exit status 0
18:22:35 INFO  Executed sudo&lt;apama_correlator_wait&gt;, exit status 0
18:22:36 INFO  Executed sudo&lt;plugin_list_after_install&gt;, exit status 0
18:22:37 INFO  Executed sudo&lt;plugin_update&gt;, exit status 0
18:22:38 INFO  Executed sudo&lt;apama_correlator_wait&gt;, exit status 0
18:22:38 INFO  Executed sudo&lt;plugin_list_after_update&gt;, exit status 0
18:22:39 INFO  Executed sudo&lt;plugin_remove&gt;, exit status 0
18:22:40 INFO  Executed sudo&lt;plugin_list_after_remove&gt;, exit status 0
18:22:40 INFO  Grep on file plugin_list_before_install.out ... passed
18:22:40 INFO  Grep on file plugin_list_after_install.out ... passed
18:22:40 INFO  Grep on file plugin_list_after_update.out ... passed
18:22:40 INFO  Grep on file plugin_list_after_remove.out ... passed
18:22:40 INFO  
18:22:40 INFO  cleanup:
18:22:40 INFO  Removing apama project
18:22:40 WARN  Executed sudo&lt;remove_apama_project&gt;, exit status 1
18:22:40 INFO  Contents of remove_apama_project.err: 
  rm: cannot remove '/etc/tedge/apama/project/logs': Directory not empty
  -----

18:22:40 ERROR Error while running cleanup function: 
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py", line 1305, in cleanup
    fn()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apama/environment_apama_plugin.py", line 144, in cleanup_project
    self.remove_project()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apama/environment_apama_plugin.py", line 95, in remove_project
    stdouterr="remove_apama_project",
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py", line 482, in startProcess
    abortOnError=abortOnError)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py", line 1401, in addOutcome
    self.abort(outcome, outcomeReason, callRecord)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py", line 1420, in abort
    raise AbortExecution(outcome, outcomeReason, callRecord)
pysys.exceptions.AbortExecution: sudo&lt;remove_apama_project&gt; returned non-zero exit code 1
18:22:40 WARN  Cleanup failed with 1 errors: Cleanup function failed: sudo&lt;remove_apama_project&gt; returned non-zero exit code 1 (AbortExecution) ... blocked 
18:22:40 INFO  
18:22:40 INFO  Test duration: 12.39 secs
18:22:40 INFO  Test final outcome:  BLOCKED
18:22:40 INFO  Test outcome reason: sudo&lt;remove_apama_project&gt; returned non-zero exit code 1 (+1 other failures)
18:22:40 INFO  
</system-out>
	</testcase>
<testcase classname="ApamaPluginMonSupportTest" name="SoftwareManagement.Plugin.apama_plugin_mon_support">
		<failure message="BLOCKED: ProcessError: Error stopping process sudo&lt;unzip_apama_project&gt; (pid 5087) due to PermissionError: [Errno 1] Operation not permitted (+3 other failures)" type="BLOCKED" />
		<system-out>18:29:44 INFO  ==============================================================
18:29:44 INFO  Id:    SoftwareManagement.Plugin.apama_plugin_mon_support
18:29:44 INFO  Dir:   plugin_apama/
18:29:44 INFO  Title: Validate mon file support of apama plugin
18:29:44 INFO  ==============================================================
18:29:44 WARN  Assertion that path exists=False for "/etc/tedge/apama/project" ... failed 
18:29:44 INFO  Executed sudo&lt;create_project_dir&gt;, exit status 0
18:39:44 WARN  Process sudo&lt;unzip_apama_project&gt; (pid 5087) timed out after 600 seconds, stopping process
18:39:44 WARN  ProcessError occurred while running test - Error stopping process sudo&lt;unzip_apama_project&gt; (pid 5087) due to PermissionError: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py", line 465, in startProcess
    process.start()
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/__init__.py", line 282, in start
    self.wait(self.timeout)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/__init__.py", line 263, in wait
    raise ProcessTimeout('Waiting for completion of %r timed out after %d seconds'%(self, int(timeout)))
pysys.exceptions.ProcessTimeout: Waiting for completion of sudo&lt;unzip_apama_project&gt; (pid 5087) timed out after 600 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/plat-unix/helper.py", line 226, in stop
    os.kill(self.pid, sig)
PermissionError: [Errno 1] Operation not permitted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1292, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apama/apama_plugin_mon_support/run.py", line 19, in setup
    self.install_project(self.project.apama_input_dir + "/quickstart.zip")
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apama/environment_apama_plugin.py", line 72, in install_project
    stdouterr="unzip_apama_project",
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py", line 493, in startProcess
    process.stop()
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/plat-unix/helper.py", line 252, in stop
    raise ProcessError("Error stopping process %r due to %s: %s"%(self, type(ex).__name__, ex))
pysys.exceptions.ProcessError: Error stopping process sudo&lt;unzip_apama_project&gt; (pid 5087) due to PermissionError: [Errno 1] Operation not permitted
18:39:45 WARN  ProcessError: Error stopping process sudo&lt;unzip_apama_project&gt; (pid 5087) due to PermissionError: [Errno 1] Operation not permitted ... blocked 
18:39:45 INFO  
18:39:45 INFO  cleanup:
18:39:45 INFO  Removing apama project
18:39:45 WARN  Executed sudo&lt;remove_apama_project&gt;, exit status 1
18:39:45 INFO  Contents of remove_apama_project.err: 
  rm: cannot remove '/etc/tedge/apama/project/logs/.nfs00000000000e13ec00003dec': Device or resource busy
  -----

18:39:45 ERROR Error while running cleanup function: 
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py", line 1305, in cleanup
    fn()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apama/environment_apama_plugin.py", line 144, in cleanup_project
    self.remove_project()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apama/environment_apama_plugin.py", line 95, in remove_project
    stdouterr="remove_apama_project",
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py", line 482, in startProcess
    abortOnError=abortOnError)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py", line 1401, in addOutcome
    self.abort(outcome, outcomeReason, callRecord)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py", line 1420, in abort
    raise AbortExecution(outcome, outcomeReason, callRecord)
pysys.exceptions.AbortExecution: sudo&lt;remove_apama_project&gt; returned non-zero exit code 1
18:39:45 WARN  Cleanup failed with 1 errors: Cleanup function failed: sudo&lt;remove_apama_project&gt; returned non-zero exit code 1 (AbortExecution) ... blocked 
18:39:45 INFO  
18:39:45 INFO  Test duration: 601.23 secs
18:39:45 INFO  Test final outcome:  BLOCKED
18:39:45 INFO  Test outcome reason: ProcessError: Error stopping process sudo&lt;unzip_apama_project&gt; (pid 5087) due to PermissionError: [Errno 1] Operation not permitted (+3 other failures)
18:39:45 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="SoftwareManagement.Plugin.apama_plugin_remove" tests="3" errors="0" failures="2" skipped="1" time="0"><testcase classname="ApamaPluginRemoveTest" name="SoftwareManagement.Plugin.apama_plugin_remove">
		<skipped message="SKIPPED: Apama plugin tests are disabled by default. Execute `pysys run` with `-XmyPlatform=container` to run these tests" />
		<system-out>17:30:51 INFO  ==============================================================
17:30:51 INFO  Id:    SoftwareManagement.Plugin.apama_plugin_remove
17:30:51 INFO  Dir:   plugin_apama/
17:30:51 INFO  Title: Validate apama plugin remove
17:30:51 INFO  ==============================================================
17:30:51 INFO  Apama plugin tests are disabled by default. Execute `pysys run` with `-XmyPlatform=container` to run these tests ... skipped
17:30:51 WARN  Aborted test due to SKIPPED outcome
17:30:51 INFO  
17:30:51 INFO  Test duration: 0.06 secs
17:30:51 INFO  Test final outcome:  SKIPPED
17:30:51 INFO  Test outcome reason: Apama plugin tests are disabled by default. Execute `pysys run` with `-XmyPlatform=container` to run these tests
17:30:51 INFO  
</system-out>
	</testcase>
<testcase classname="ApamaPluginRemoveTest" name="SoftwareManagement.Plugin.apama_plugin_remove">
		<failure message="BLOCKED: sudo&lt;remove_apama_project&gt; returned non-zero exit code 1 (+2 other failures)" type="BLOCKED" />
		<system-out>18:22:40 INFO  ==============================================================
18:22:40 INFO  Id:    SoftwareManagement.Plugin.apama_plugin_remove
18:22:40 INFO  Dir:   plugin_apama/
18:22:40 INFO  Title: Validate apama plugin remove
18:22:40 INFO  ==============================================================
18:22:41 WARN  Assertion that path exists=False for "/etc/tedge/apama/project" ... failed 
18:22:41 WARN  Aborted test due to FAILED outcome
18:22:41 INFO  
18:22:41 INFO  cleanup:
18:22:41 INFO  Removing apama project
18:22:41 WARN  Executed sudo&lt;remove_apama_project&gt;, exit status 1
18:22:41 INFO  Contents of remove_apama_project.err: 
  rm: cannot remove '/etc/tedge/apama/project/logs/.nfs00000000000e13ec00003dec': Device or resource busy
  -----

18:22:41 ERROR Error while running cleanup function: 
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py", line 1305, in cleanup
    fn()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apama/environment_apama_plugin.py", line 144, in cleanup_project
    self.remove_project()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apama/environment_apama_plugin.py", line 95, in remove_project
    stdouterr="remove_apama_project",
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py", line 482, in startProcess
    abortOnError=abortOnError)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py", line 1401, in addOutcome
    self.abort(outcome, outcomeReason, callRecord)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py", line 1420, in abort
    raise AbortExecution(outcome, outcomeReason, callRecord)
pysys.exceptions.AbortExecution: sudo&lt;remove_apama_project&gt; returned non-zero exit code 1
18:22:41 WARN  Cleanup failed with 1 errors: Cleanup function failed: sudo&lt;remove_apama_project&gt; returned non-zero exit code 1 (AbortExecution) ... blocked 
18:22:41 INFO  
18:22:41 INFO  Test duration: 0.64 secs
18:22:41 INFO  Test final outcome:  BLOCKED
18:22:41 INFO  Test outcome reason: sudo&lt;remove_apama_project&gt; returned non-zero exit code 1 (+2 other failures)
18:22:41 INFO  
</system-out>
	</testcase>
<testcase classname="ApamaPluginRemoveTest" name="SoftwareManagement.Plugin.apama_plugin_remove">
		<failure message="BLOCKED: sudo&lt;remove_apama_project&gt; returned non-zero exit code 1 (+2 other failures)" type="BLOCKED" />
		<system-out>18:39:45 INFO  ==============================================================
18:39:45 INFO  Id:    SoftwareManagement.Plugin.apama_plugin_remove
18:39:45 INFO  Dir:   plugin_apama/
18:39:45 INFO  Title: Validate apama plugin remove
18:39:45 INFO  ==============================================================
18:39:45 WARN  Assertion that path exists=False for "/etc/tedge/apama/project" ... failed 
18:39:45 WARN  Aborted test due to FAILED outcome
18:39:45 INFO  
18:39:45 INFO  cleanup:
18:39:45 INFO  Removing apama project
18:39:46 WARN  Executed sudo&lt;remove_apama_project&gt;, exit status 1
18:39:46 INFO  Contents of remove_apama_project.err: 
  rm: cannot remove '/etc/tedge/apama/project/logs/.nfs00000000000e13ec00003dec': Device or resource busy
  -----

18:39:46 ERROR Error while running cleanup function: 
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py", line 1305, in cleanup
    fn()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apama/environment_apama_plugin.py", line 144, in cleanup_project
    self.remove_project()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apama/environment_apama_plugin.py", line 95, in remove_project
    stdouterr="remove_apama_project",
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py", line 482, in startProcess
    abortOnError=abortOnError)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py", line 1401, in addOutcome
    self.abort(outcome, outcomeReason, callRecord)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py", line 1420, in abort
    raise AbortExecution(outcome, outcomeReason, callRecord)
pysys.exceptions.AbortExecution: sudo&lt;remove_apama_project&gt; returned non-zero exit code 1
18:39:46 WARN  Cleanup failed with 1 errors: Cleanup function failed: sudo&lt;remove_apama_project&gt; returned non-zero exit code 1 (AbortExecution) ... blocked 
18:39:46 INFO  
18:39:46 INFO  Test duration: 0.65 secs
18:39:46 INFO  Test final outcome:  BLOCKED
18:39:46 INFO  Test outcome reason: sudo&lt;remove_apama_project&gt; returned non-zero exit code 1 (+2 other failures)
18:39:46 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="SoftwareManagement.Plugin.apama_plugin_update" tests="3" errors="0" failures="2" skipped="1" time="0"><testcase classname="ApamaPluginUpdateTest" name="SoftwareManagement.Plugin.apama_plugin_update">
		<skipped message="SKIPPED: Apama plugin tests are disabled by default. Execute `pysys run` with `-XmyPlatform=container` to run these tests" />
		<system-out>17:30:51 INFO  ==============================================================
17:30:51 INFO  Id:    SoftwareManagement.Plugin.apama_plugin_update
17:30:51 INFO  Dir:   plugin_apama/
17:30:51 INFO  Title: Validate apama plugin updating one project with another
17:30:51 INFO  ==============================================================
17:30:51 INFO  Apama plugin tests are disabled by default. Execute `pysys run` with `-XmyPlatform=container` to run these tests ... skipped
17:30:51 WARN  Aborted test due to SKIPPED outcome
17:30:51 INFO  
17:30:51 INFO  Test duration: 0.02 secs
17:30:51 INFO  Test final outcome:  SKIPPED
17:30:51 INFO  Test outcome reason: Apama plugin tests are disabled by default. Execute `pysys run` with `-XmyPlatform=container` to run these tests
17:30:51 INFO  
</system-out>
	</testcase>
<testcase classname="ApamaPluginUpdateTest" name="SoftwareManagement.Plugin.apama_plugin_update">
		<failure message="BLOCKED: sudo&lt;remove_apama_project&gt; returned non-zero exit code 1 (+2 other failures)" type="BLOCKED" />
		<system-out>18:22:41 INFO  ==============================================================
18:22:41 INFO  Id:    SoftwareManagement.Plugin.apama_plugin_update
18:22:41 INFO  Dir:   plugin_apama/
18:22:41 INFO  Title: Validate apama plugin updating one project with another
18:22:41 INFO  ==============================================================
18:22:41 WARN  Assertion that path exists=False for "/etc/tedge/apama/project" ... failed 
18:22:41 WARN  Aborted test due to FAILED outcome
18:22:41 INFO  
18:22:41 INFO  cleanup:
18:22:41 INFO  Removing apama project
18:22:42 WARN  Executed sudo&lt;remove_apama_project&gt;, exit status 1
18:22:42 INFO  Contents of remove_apama_project.err: 
  rm: cannot remove '/etc/tedge/apama/project/logs/.nfs00000000000e13ec00003dec': Device or resource busy
  -----

18:22:42 ERROR Error while running cleanup function: 
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py", line 1305, in cleanup
    fn()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apama/environment_apama_plugin.py", line 144, in cleanup_project
    self.remove_project()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apama/environment_apama_plugin.py", line 95, in remove_project
    stdouterr="remove_apama_project",
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py", line 482, in startProcess
    abortOnError=abortOnError)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py", line 1401, in addOutcome
    self.abort(outcome, outcomeReason, callRecord)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py", line 1420, in abort
    raise AbortExecution(outcome, outcomeReason, callRecord)
pysys.exceptions.AbortExecution: sudo&lt;remove_apama_project&gt; returned non-zero exit code 1
18:22:42 WARN  Cleanup failed with 1 errors: Cleanup function failed: sudo&lt;remove_apama_project&gt; returned non-zero exit code 1 (AbortExecution) ... blocked 
18:22:42 INFO  
18:22:42 INFO  Test duration: 0.64 secs
18:22:42 INFO  Test final outcome:  BLOCKED
18:22:42 INFO  Test outcome reason: sudo&lt;remove_apama_project&gt; returned non-zero exit code 1 (+2 other failures)
18:22:42 INFO  
</system-out>
	</testcase>
<testcase classname="ApamaPluginUpdateTest" name="SoftwareManagement.Plugin.apama_plugin_update">
		<failure message="BLOCKED: sudo&lt;remove_apama_project&gt; returned non-zero exit code 1 (+2 other failures)" type="BLOCKED" />
		<system-out>18:39:46 INFO  ==============================================================
18:39:46 INFO  Id:    SoftwareManagement.Plugin.apama_plugin_update
18:39:46 INFO  Dir:   plugin_apama/
18:39:46 INFO  Title: Validate apama plugin updating one project with another
18:39:46 INFO  ==============================================================
18:39:46 WARN  Assertion that path exists=False for "/etc/tedge/apama/project" ... failed 
18:39:46 WARN  Aborted test due to FAILED outcome
18:39:46 INFO  
18:39:46 INFO  cleanup:
18:39:46 INFO  Removing apama project
18:39:46 WARN  Executed sudo&lt;remove_apama_project&gt;, exit status 1
18:39:47 INFO  Contents of remove_apama_project.err: 
  rm: cannot remove '/etc/tedge/apama/project/logs/.nfs00000000000e13ec00003dec': Device or resource busy
  -----

18:39:47 ERROR Error while running cleanup function: 
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py", line 1305, in cleanup
    fn()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apama/environment_apama_plugin.py", line 144, in cleanup_project
    self.remove_project()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apama/environment_apama_plugin.py", line 95, in remove_project
    stdouterr="remove_apama_project",
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py", line 482, in startProcess
    abortOnError=abortOnError)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py", line 1401, in addOutcome
    self.abort(outcome, outcomeReason, callRecord)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py", line 1420, in abort
    raise AbortExecution(outcome, outcomeReason, callRecord)
pysys.exceptions.AbortExecution: sudo&lt;remove_apama_project&gt; returned non-zero exit code 1
18:39:47 WARN  Cleanup failed with 1 errors: Cleanup function failed: sudo&lt;remove_apama_project&gt; returned non-zero exit code 1 (AbortExecution) ... blocked 
18:39:47 INFO  
18:39:47 INFO  Test duration: 0.74 secs
18:39:47 INFO  Test final outcome:  BLOCKED
18:39:47 INFO  Test outcome reason: sudo&lt;remove_apama_project&gt; returned non-zero exit code 1 (+2 other failures)
18:39:47 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="SoftwareManagement.sm_apt_install_download_path" tests="3" errors="0" failures="2" skipped="1" time="0"><testcase classname="AptInstallWithDownloadPath" name="SoftwareManagement.sm_apt_install_download_path">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it" />
		<system-out>17:42:04 INFO  ==============================================================
17:42:04 INFO  Id:    SoftwareManagement.sm_apt_install_download_path
17:42:04 INFO  Dir:   software_management_end_to_end/
17:42:04 INFO  Title: Install package to directory specified in tedge config set tmp.path
17:42:04 INFO  ==============================================================
17:42:04 INFO  Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it ... skipped
17:42:04 WARN  Aborted test due to SKIPPED outcome
17:42:04 INFO  
17:42:04 INFO  Test duration: 0.06 secs
17:42:04 INFO  Test final outcome:  SKIPPED
17:42:04 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it
17:42:04 INFO  
</system-out>
	</testcase>
<testcase classname="AptInstallWithDownloadPath" name="SoftwareManagement.sm_apt_install_download_path">
		<failure message="BLOCKED: AssertionError:" type="BLOCKED" />
		<system-out>18:05:08 INFO  ==============================================================
18:05:08 INFO  Id:    SoftwareManagement.sm_apt_install_download_path
18:05:08 INFO  Dir:   software_management_end_to_end/
18:05:08 INFO  Title: Install package to directory specified in tedge config set tmp.path
18:05:08 INFO  ==============================================================
18:05:08 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
18:05:08 INFO  EnvironmentC8y Setup
18:05:08 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
18:05:23 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
18:05:25 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
18:05:26 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
18:05:26 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
18:05:29 INFO  State of current operation: SUCCESSFUL
18:05:29 INFO  Assert that (False == value) with value=False ... passed
18:05:29 INFO  Executed sudo, exit status 0
18:05:30 INFO  Executed sudo, exit status 0
18:05:30 INFO  Executed sudo, exit status 0
18:05:34 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
18:05:35 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 3 seconds
18:05:35 INFO  Delaying execution by 8 seconds
18:05:56 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 13 secs
18:05:57 INFO  Response status: 201
18:05:57 INFO  Response to action: {
    "creationTime": "2022-04-27T18:05:57.095Z",
    "deviceName": "m32sd10b",
    "deviceId": "17821468",
    "self": "https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17832342",
    "id": "17832342",
    "status": "PENDING",
    "description": "Apply software changes, triggered from PySys: [{'name': 'rolldice', 'id': '5152439', 'version': '::apt', 'url': 'https://thin-edge-io.eu-latest.cumulocity.com/inventory/binaries/12435463', 'action': 'install'}]",
    "c8y_SoftwareUpdate": [
        {
            "name": "rolldice",
            "action": "install",
            "id": "5152439",
            "version": "::apt",
            "url": "https://thin-edge-io.eu-latest.cumulocity.com/inventory/binaries/12435463"
        }
    ]
}
18:05:57 INFO  Started operation: {'creationTime': '2022-04-27T18:05:57.095Z', 'deviceName': 'm32sd10b', 'deviceId': '17821468', 'self': 'https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17832342', 'id': '17832342', 'status': 'PENDING', 'description': "Apply software changes, triggered from PySys: [{'name': 'rolldice', 'id': '5152439', 'version': '::apt', 'url': 'https://thin-edge-io.eu-latest.cumulocity.com/inventory/binaries/12435463', 'action': 'install'}]", 'c8y_SoftwareUpdate': [{'name': 'rolldice', 'action': 'install', 'id': '5152439', 'version': '::apt', 'url': 'https://thin-edge-io.eu-latest.cumulocity.com/inventory/binaries/12435463'}]}
18:05:57 WARN  , retrying in 0.5 seconds...
18:05:57 WARN  , retrying in 0.5 seconds...
18:05:58 WARN  , retrying in 0.5 seconds...
18:05:58 WARN  , retrying in 0.5 seconds...
18:05:59 WARN  , retrying in 0.5 seconds...
18:05:59 WARN  , retrying in 0.5 seconds...
18:06:00 WARN  , retrying in 0.5 seconds...
18:06:00 WARN  , retrying in 0.5 seconds...
18:06:01 WARN  , retrying in 0.5 seconds...
18:06:01 WARN  AssertionError occurred while running test - 
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1294, in __call__
    self.testObj.execute()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_download_path/run.py", line 83, in execute
    assert_install_in_download_path(install_directory=self.DOWNLOAD_DIR)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/retry/api.py", line 74, in retry_decorator
    logger)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_download_path/run.py", line 28, in assert_install_in_download_path
    assert "rolldice" in os.listdir(f"{install_directory}")
AssertionError
18:06:02 WARN  AssertionError: ... blocked 
18:06:02 INFO  
18:06:02 INFO  cleanup:
18:06:03 INFO  Executed sudo, exit status 0
18:06:03 INFO  Executed sudo, exit status 0
18:06:08 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
18:06:08 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 3 seconds
18:06:08 INFO  Delaying execution by 8 seconds
18:06:30 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
18:06:34 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
18:06:34 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
18:06:34 INFO  
18:06:34 INFO  Test duration: 86.84 secs
18:06:34 INFO  Test final outcome:  BLOCKED
18:06:34 INFO  Test outcome reason: AssertionError:
18:06:34 INFO  
</system-out>
	</testcase>
<testcase classname="AptInstallWithDownloadPath" name="SoftwareManagement.sm_apt_install_download_path">
		<failure message="BLOCKED: AssertionError:" type="BLOCKED" />
		<system-out>18:39:47 INFO  ==============================================================
18:39:47 INFO  Id:    SoftwareManagement.sm_apt_install_download_path
18:39:47 INFO  Dir:   software_management_end_to_end/
18:39:47 INFO  Title: Install package to directory specified in tedge config set tmp.path
18:39:47 INFO  ==============================================================
18:39:48 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
18:39:48 INFO  EnvironmentC8y Setup
18:39:49 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
18:40:03 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
18:40:04 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
18:40:05 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
18:40:05 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
18:40:07 INFO  State of current operation: SUCCESSFUL
18:40:08 INFO  Assert that (False == value) with value=False ... passed
18:40:08 INFO  Executed sudo, exit status 0
18:40:09 INFO  Executed sudo, exit status 0
18:40:10 INFO  Executed sudo, exit status 0
18:40:14 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
18:40:14 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 3 seconds
18:40:14 INFO  Delaying execution by 8 seconds
18:40:36 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 13 secs
18:40:36 INFO  Response status: 201
18:40:36 INFO  Response to action: {
    "creationTime": "2022-04-27T18:40:36.323Z",
    "deviceName": "m32sd10b",
    "deviceId": "17821468",
    "self": "https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17832465",
    "id": "17832465",
    "status": "PENDING",
    "description": "Apply software changes, triggered from PySys: [{'name': 'rolldice', 'id': '5152439', 'version': '::apt', 'url': 'https://thin-edge-io.eu-latest.cumulocity.com/inventory/binaries/12435463', 'action': 'install'}]",
    "c8y_SoftwareUpdate": [
        {
            "name": "rolldice",
            "action": "install",
            "id": "5152439",
            "version": "::apt",
            "url": "https://thin-edge-io.eu-latest.cumulocity.com/inventory/binaries/12435463"
        }
    ]
}
18:40:36 INFO  Started operation: {'creationTime': '2022-04-27T18:40:36.323Z', 'deviceName': 'm32sd10b', 'deviceId': '17821468', 'self': 'https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17832465', 'id': '17832465', 'status': 'PENDING', 'description': "Apply software changes, triggered from PySys: [{'name': 'rolldice', 'id': '5152439', 'version': '::apt', 'url': 'https://thin-edge-io.eu-latest.cumulocity.com/inventory/binaries/12435463', 'action': 'install'}]", 'c8y_SoftwareUpdate': [{'name': 'rolldice', 'action': 'install', 'id': '5152439', 'version': '::apt', 'url': 'https://thin-edge-io.eu-latest.cumulocity.com/inventory/binaries/12435463'}]}
18:40:36 WARN  , retrying in 0.5 seconds...
18:40:36 WARN  , retrying in 0.5 seconds...
18:40:37 WARN  , retrying in 0.5 seconds...
18:40:37 WARN  , retrying in 0.5 seconds...
18:40:38 WARN  , retrying in 0.5 seconds...
18:40:38 WARN  , retrying in 0.5 seconds...
18:40:39 WARN  , retrying in 0.5 seconds...
18:40:39 WARN  , retrying in 0.5 seconds...
18:40:40 WARN  , retrying in 0.5 seconds...
18:40:40 WARN  AssertionError occurred while running test - 
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1294, in __call__
    self.testObj.execute()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_download_path/run.py", line 83, in execute
    assert_install_in_download_path(install_directory=self.DOWNLOAD_DIR)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/retry/api.py", line 74, in retry_decorator
    logger)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_download_path/run.py", line 28, in assert_install_in_download_path
    assert "rolldice" in os.listdir(f"{install_directory}")
AssertionError
18:40:40 WARN  AssertionError: ... blocked 
18:40:40 INFO  
18:40:40 INFO  cleanup:
18:40:41 INFO  Executed sudo, exit status 0
18:40:42 INFO  Executed sudo, exit status 0
18:40:46 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
18:40:46 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 4 seconds
18:40:46 INFO  Delaying execution by 7 seconds
18:41:08 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
18:41:12 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
18:41:12 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
18:41:12 INFO  
18:41:12 INFO  Test duration: 85.89 secs
18:41:12 INFO  Test final outcome:  BLOCKED
18:41:12 INFO  Test outcome reason: AssertionError:
18:41:12 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="SoftwareManagement.sm_apt_install_fail" tests="3" errors="0" failures="0" skipped="1" time="0"><testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_fail">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it" />
		<system-out>17:42:04 INFO  ==============================================================
17:42:04 INFO  Id:    SoftwareManagement.sm_apt_install_fail
17:42:04 INFO  Dir:   software_management_end_to_end/
17:42:04 INFO  Title: Validate end to end behaviour for a failing installation
17:42:04 INFO  ==============================================================
17:42:04 INFO  Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it ... skipped
17:42:04 WARN  Aborted test due to SKIPPED outcome
17:42:04 INFO  
17:42:04 INFO  Test duration: 0.02 secs
17:42:04 INFO  Test final outcome:  SKIPPED
17:42:04 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it
17:42:04 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_fail" />
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_fail" />
</testsuite><testsuite name="SoftwareManagement.sm_apt_install_remove" tests="3" errors="0" failures="0" skipped="1" time="0"><testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it" />
		<system-out>17:42:05 INFO  ==============================================================
17:42:05 INFO  Id:    SoftwareManagement.sm_apt_install_remove
17:42:05 INFO  Dir:   software_management_end_to_end/
17:42:05 INFO  Title: Validate end to end behaviour for the apt plugin for installation and removal of packages
17:42:05 INFO  ==============================================================
17:42:05 INFO  Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it ... skipped
17:42:05 WARN  Aborted test due to SKIPPED outcome
17:42:05 INFO  
17:42:05 INFO  Test duration: 0.02 secs
17:42:05 INFO  Test final outcome:  SKIPPED
17:42:05 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it
17:42:05 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove" />
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove" />
</testsuite><testsuite name="SoftwareManagement.sm_apt_install_remove_default" tests="3" errors="0" failures="0" skipped="1" time="0"><testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove_default">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it" />
		<system-out>17:42:05 INFO  ==============================================================
17:42:05 INFO  Id:    SoftwareManagement.sm_apt_install_remove_default
17:42:05 INFO  Dir:   software_management_end_to_end/
17:42:05 INFO  Title: Validate end to end behaviour for the default plugin for installation and removal of packages
17:42:05 INFO  ==============================================================
17:42:05 INFO  Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it ... skipped
17:42:05 WARN  Aborted test due to SKIPPED outcome
17:42:05 INFO  
17:42:05 INFO  Test duration: 0.02 secs
17:42:05 INFO  Test final outcome:  SKIPPED
17:42:05 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it
17:42:05 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove_default" />
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove_default" />
</testsuite><testsuite name="SoftwareManagement.sm_apt_install_remove_multiple" tests="3" errors="0" failures="2" skipped="1" time="0"><testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove_multiple">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it" />
		<system-out>17:42:05 INFO  ==============================================================
17:42:05 INFO  Id:    SoftwareManagement.sm_apt_install_remove_multiple
17:42:05 INFO  Dir:   software_management_end_to_end/
17:42:05 INFO  Title: Validate end to end behaviour for the apt plugin for multiple packages
17:42:05 INFO  ==============================================================
17:42:05 INFO  Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it ... skipped
17:42:05 WARN  Aborted test due to SKIPPED outcome
17:42:05 INFO  
17:42:05 INFO  Test duration: 0.04 secs
17:42:05 INFO  Test final outcome:  SKIPPED
17:42:05 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it
17:42:05 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove_multiple">
		<failure message="FAILED: Assert that (False == value) with value=True" type="FAILED" />
		<system-out>18:13:22 INFO  ==============================================================
18:13:22 INFO  Id:    SoftwareManagement.sm_apt_install_remove_multiple
18:13:22 INFO  Dir:   software_management_end_to_end/
18:13:22 INFO  Title: Validate end to end behaviour for the apt plugin for multiple packages
18:13:22 INFO  ==============================================================
18:13:22 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
18:13:22 INFO  EnvironmentC8y Setup
18:13:22 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
18:13:23 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 4 seconds
18:13:23 INFO  Delaying execution by 7 seconds
18:13:44 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 13 secs
18:13:44 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
18:13:45 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
18:13:45 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
18:13:47 INFO  State of current operation: SUCCESSFUL
18:13:48 INFO  Assert that (False == value) with value=False ... passed
18:13:48 INFO  Assert that (False == value) with value=False ... passed
18:13:48 INFO  Assert that (False == value) with value=False ... passed
18:13:48 INFO  Package robotfindskitten is installed
18:13:48 WARN  Assert that (False == value) with value=True ... failed 
18:13:49 INFO  Response status: 201
18:13:49 INFO  Response to action: {
    "creationTime": "2022-04-27T18:13:49.104Z",
    "deviceName": "m32sd10b",
    "deviceId": "17821468",
    "self": "https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17832396",
    "id": "17832396",
    "status": "PENDING",
    "description": "Apply software changes, triggered from PySys: [{'action': 'install', 'id': '5475369', 'name': 'asciijump', 'url': ' ', 'version': '::apt'}, {'action': 'install', 'id': '5474869', 'name': 'robotfindskitten', 'url': ' ', 'version': '::apt'}, {'action': 'install', 'id': '5475279', 'name': 'squirrel3', 'url': ' ', 'version': '::apt'}]",
    "c8y_SoftwareUpdate": [
        {
            "name": "asciijump",
            "action": "install",
            "id": "5475369",
            "version": "::apt",
            "url": " "
        },
        {
            "name": "robotfindskitten",
            "action": "install",
            "id": "5474869",
            "version": "::apt",
            "url": " "
        },
        {
            "name": "squirrel3",
            "action": "install",
            "id": "5475279",
            "version": "::apt",
            "url": " "
        }
    ]
}
18:13:49 INFO  Started operation: {'creationTime': '2022-04-27T18:13:49.104Z', 'deviceName': 'm32sd10b', 'deviceId': '17821468', 'self': 'https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17832396', 'id': '17832396', 'status': 'PENDING', 'description': "Apply software changes, triggered from PySys: [{'action': 'install', 'id': '5475369', 'name': 'asciijump', 'url': ' ', 'version': '::apt'}, {'action': 'install', 'id': '5474869', 'name': 'robotfindskitten', 'url': ' ', 'version': '::apt'}, {'action': 'install', 'id': '5475279', 'name': 'squirrel3', 'url': ' ', 'version': '::apt'}]", 'c8y_SoftwareUpdate': [{'name': 'asciijump', 'action': 'install', 'id': '5475369', 'version': '::apt', 'url': ' '}, {'name': 'robotfindskitten', 'action': 'install', 'id': '5474869', 'version': '::apt', 'url': ' '}, {'name': 'squirrel3', 'action': 'install', 'id': '5475279', 'version': '::apt', 'url': ' '}]}
18:13:51 INFO  State of operation 17832396 : PENDING
18:13:53 INFO  State of operation 17832396 : EXECUTING
18:13:55 INFO  State of operation 17832396 : EXECUTING
18:13:57 INFO  State of operation 17832396 : EXECUTING
18:14:00 INFO  State of operation 17832396 : EXECUTING
18:14:02 INFO  State of operation 17832396 : EXECUTING
18:14:05 INFO  State of operation 17832396 : EXECUTING
18:14:07 INFO  State of operation 17832396 : EXECUTING
18:14:10 INFO  State of operation 17832396 : EXECUTING
18:14:12 INFO  State of operation 17832396 : EXECUTING
18:14:14 INFO  State of operation 17832396 : EXECUTING
18:14:16 INFO  State of operation 17832396 : EXECUTING
18:14:19 INFO  State of operation 17832396 : EXECUTING
18:14:21 INFO  State of operation 17832396 : EXECUTING
18:14:23 INFO  State of operation 17832396 : EXECUTING
18:14:26 INFO  State of operation 17832396 : EXECUTING
18:14:28 INFO  State of operation 17832396 : EXECUTING
18:14:31 INFO  State of operation 17832396 : EXECUTING
18:14:33 INFO  State of operation 17832396 : EXECUTING
18:14:35 INFO  State of operation 17832396 : EXECUTING
18:14:37 INFO  State of operation 17832396 : EXECUTING
18:14:40 INFO  State of operation 17832396 : EXECUTING
18:14:42 INFO  State of operation 17832396 : EXECUTING
18:14:44 INFO  State of operation 17832396 : EXECUTING
18:14:47 INFO  State of operation 17832396 : EXECUTING
18:14:49 INFO  State of operation 17832396 : EXECUTING
18:14:51 INFO  State of operation 17832396 : EXECUTING
18:14:54 INFO  State of operation 17832396 : EXECUTING
18:14:56 INFO  State of operation 17832396 : EXECUTING
18:14:58 INFO  State of operation 17832396 : EXECUTING
18:15:01 INFO  State of operation 17832396 : EXECUTING
18:15:03 INFO  State of operation 17832396 : EXECUTING
18:15:05 INFO  State of operation 17832396 : EXECUTING
18:15:07 INFO  State of operation 17832396 : EXECUTING
18:15:10 INFO  State of operation 17832396 : SUCCESSFUL
18:15:10 INFO  Assert that (False == value) with value=False ... passed
18:15:10 INFO  Package asciijump is installed
18:15:10 INFO  Assert that (True == value) with value=True ... passed
18:15:10 INFO  Package squirrel3 is installed
18:15:10 INFO  Assert that (True == value) with value=True ... passed
18:15:10 INFO  Package robotfindskitten is installed
18:15:10 INFO  Assert that (True == value) with value=True ... passed
18:15:11 INFO  Response status: 201
18:15:11 INFO  Response to action: {
    "creationTime": "2022-04-27T18:15:11.122Z",
    "deviceName": "m32sd10b",
    "deviceId": "17821468",
    "self": "https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17832402",
    "id": "17832402",
    "status": "PENDING",
    "description": "Apply software changes, triggered from PySys: [{'action': 'delete', 'id': '5475369', 'name': 'asciijump', 'url': ' ', 'version': '::apt'}, {'action': 'delete', 'id': '5474869', 'name': 'robotfindskitten', 'url': ' ', 'version': '::apt'}, {'action': 'delete', 'id': '5475279', 'name': 'squirrel3', 'url': ' ', 'version': '::apt'}]",
    "c8y_SoftwareUpdate": [
        {
            "name": "asciijump",
            "action": "delete",
            "id": "5475369",
            "version": "::apt",
            "url": " "
        },
        {
            "name": "robotfindskitten",
            "action": "delete",
            "id": "5474869",
            "version": "::apt",
            "url": " "
        },
        {
            "name": "squirrel3",
            "action": "delete",
            "id": "5475279",
            "version": "::apt",
            "url": " "
        }
    ]
}
18:15:11 INFO  Started operation: {'creationTime': '2022-04-27T18:15:11.122Z', 'deviceName': 'm32sd10b', 'deviceId': '17821468', 'self': 'https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17832402', 'id': '17832402', 'status': 'PENDING', 'description': "Apply software changes, triggered from PySys: [{'action': 'delete', 'id': '5475369', 'name': 'asciijump', 'url': ' ', 'version': '::apt'}, {'action': 'delete', 'id': '5474869', 'name': 'robotfindskitten', 'url': ' ', 'version': '::apt'}, {'action': 'delete', 'id': '5475279', 'name': 'squirrel3', 'url': ' ', 'version': '::apt'}]", 'c8y_SoftwareUpdate': [{'name': 'asciijump', 'action': 'delete', 'id': '5475369', 'version': '::apt', 'url': ' '}, {'name': 'robotfindskitten', 'action': 'delete', 'id': '5474869', 'version': '::apt', 'url': ' '}, {'name': 'squirrel3', 'action': 'delete', 'id': '5475279', 'version': '::apt', 'url': ' '}]}
18:15:13 INFO  State of operation 17832402 : PENDING
18:15:15 INFO  State of operation 17832402 : EXECUTING
18:15:17 INFO  State of operation 17832402 : EXECUTING
18:15:20 INFO  State of operation 17832402 : EXECUTING
18:15:22 INFO  State of operation 17832402 : EXECUTING
18:15:24 INFO  State of operation 17832402 : EXECUTING
18:15:27 INFO  State of operation 17832402 : EXECUTING
18:15:30 INFO  State of operation 17832402 : EXECUTING
18:15:32 INFO  State of operation 17832402 : EXECUTING
18:15:34 INFO  State of operation 17832402 : EXECUTING
18:15:37 INFO  State of operation 17832402 : EXECUTING
18:15:39 INFO  State of operation 17832402 : EXECUTING
18:15:41 INFO  State of operation 17832402 : EXECUTING
18:15:43 INFO  State of operation 17832402 : EXECUTING
18:15:46 INFO  State of operation 17832402 : EXECUTING
18:15:48 INFO  State of operation 17832402 : EXECUTING
18:15:50 INFO  State of operation 17832402 : EXECUTING
18:15:53 INFO  State of operation 17832402 : EXECUTING
18:15:56 INFO  State of operation 17832402 : EXECUTING
18:15:58 INFO  State of operation 17832402 : EXECUTING
18:16:00 INFO  State of operation 17832402 : EXECUTING
18:16:02 INFO  State of operation 17832402 : EXECUTING
18:16:04 INFO  State of operation 17832402 : EXECUTING
18:16:07 INFO  State of operation 17832402 : EXECUTING
18:16:10 INFO  State of operation 17832402 : EXECUTING
18:16:12 INFO  State of operation 17832402 : EXECUTING
18:16:14 INFO  State of operation 17832402 : EXECUTING
18:16:16 INFO  State of operation 17832402 : SUCCESSFUL
18:16:17 INFO  Assert that (False == value) with value=False ... passed
18:16:17 INFO  Assert that (False == value) with value=False ... passed
18:16:17 INFO  Assert that (False == value) with value=False ... passed
18:16:17 INFO  Assert that (False == value) with value=False ... passed
18:16:17 INFO  
18:16:17 INFO  cleanup:
18:16:21 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
18:16:22 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
18:16:22 INFO  
18:16:22 INFO  Test duration: 180.15 secs
18:16:22 INFO  Test final outcome:  FAILED
18:16:22 INFO  Test outcome reason: Assert that (False == value) with value=True
18:16:22 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove_multiple">
		<failure message="FAILED: Assert that (False == value) with value=True (+2 other failures)" type="FAILED" />
		<system-out>18:47:46 INFO  ==============================================================
18:47:46 INFO  Id:    SoftwareManagement.sm_apt_install_remove_multiple
18:47:46 INFO  Dir:   software_management_end_to_end/
18:47:46 INFO  Title: Validate end to end behaviour for the apt plugin for multiple packages
18:47:46 INFO  ==============================================================
18:47:46 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
18:47:46 INFO  EnvironmentC8y Setup
18:47:47 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
18:47:47 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 4 seconds
18:47:47 INFO  Delaying execution by 7 seconds
18:48:08 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
18:48:09 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
18:48:09 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
18:48:10 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
18:48:12 INFO  State of current operation: SUCCESSFUL
18:48:12 INFO  Assert that (False == value) with value=False ... passed
18:48:13 INFO  Package asciijump is installed
18:48:13 WARN  Assert that (False == value) with value=True ... failed 
18:48:13 INFO  Package squirrel3 is installed
18:48:13 WARN  Assert that (False == value) with value=True ... failed 
18:48:13 INFO  Package robotfindskitten is installed
18:48:13 WARN  Assert that (False == value) with value=True ... failed 
18:48:14 INFO  Response status: 201
18:48:14 INFO  Response to action: {
    "creationTime": "2022-04-27T18:48:14.045Z",
    "deviceName": "m32sd10b",
    "deviceId": "17821468",
    "self": "https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17832508",
    "id": "17832508",
    "status": "PENDING",
    "description": "Apply software changes, triggered from PySys: [{'action': 'install', 'id': '5475369', 'name': 'asciijump', 'url': ' ', 'version': '::apt'}, {'action': 'install', 'id': '5474869', 'name': 'robotfindskitten', 'url': ' ', 'version': '::apt'}, {'action': 'install', 'id': '5475279', 'name': 'squirrel3', 'url': ' ', 'version': '::apt'}]",
    "c8y_SoftwareUpdate": [
        {
            "name": "asciijump",
            "action": "install",
            "id": "5475369",
            "version": "::apt",
            "url": " "
        },
        {
            "name": "robotfindskitten",
            "action": "install",
            "id": "5474869",
            "version": "::apt",
            "url": " "
        },
        {
            "name": "squirrel3",
            "action": "install",
            "id": "5475279",
            "version": "::apt",
            "url": " "
        }
    ]
}
18:48:14 INFO  Started operation: {'creationTime': '2022-04-27T18:48:14.045Z', 'deviceName': 'm32sd10b', 'deviceId': '17821468', 'self': 'https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17832508', 'id': '17832508', 'status': 'PENDING', 'description': "Apply software changes, triggered from PySys: [{'action': 'install', 'id': '5475369', 'name': 'asciijump', 'url': ' ', 'version': '::apt'}, {'action': 'install', 'id': '5474869', 'name': 'robotfindskitten', 'url': ' ', 'version': '::apt'}, {'action': 'install', 'id': '5475279', 'name': 'squirrel3', 'url': ' ', 'version': '::apt'}]", 'c8y_SoftwareUpdate': [{'name': 'asciijump', 'action': 'install', 'id': '5475369', 'version': '::apt', 'url': ' '}, {'name': 'robotfindskitten', 'action': 'install', 'id': '5474869', 'version': '::apt', 'url': ' '}, {'name': 'squirrel3', 'action': 'install', 'id': '5475279', 'version': '::apt', 'url': ' '}]}
18:48:16 INFO  State of operation 17832508 : PENDING
18:48:18 INFO  State of operation 17832508 : EXECUTING
18:48:20 INFO  State of operation 17832508 : EXECUTING
18:48:22 INFO  State of operation 17832508 : EXECUTING
18:48:25 INFO  State of operation 17832508 : EXECUTING
18:48:27 INFO  State of operation 17832508 : EXECUTING
18:48:30 INFO  State of operation 17832508 : EXECUTING
18:48:32 INFO  State of operation 17832508 : EXECUTING
18:48:35 INFO  State of operation 17832508 : EXECUTING
18:48:37 INFO  State of operation 17832508 : EXECUTING
18:48:39 INFO  State of operation 17832508 : EXECUTING
18:48:41 INFO  State of operation 17832508 : EXECUTING
18:48:44 INFO  State of operation 17832508 : EXECUTING
18:48:46 INFO  State of operation 17832508 : EXECUTING
18:48:48 INFO  State of operation 17832508 : EXECUTING
18:48:50 INFO  State of operation 17832508 : SUCCESSFUL
18:48:50 INFO  Assert that (False == value) with value=False ... passed
18:48:51 INFO  Package asciijump is installed
18:48:51 INFO  Assert that (True == value) with value=True ... passed
18:48:51 INFO  Package squirrel3 is installed
18:48:51 INFO  Assert that (True == value) with value=True ... passed
18:48:51 INFO  Package robotfindskitten is installed
18:48:51 INFO  Assert that (True == value) with value=True ... passed
18:48:52 INFO  Response status: 201
18:48:52 INFO  Response to action: {
    "creationTime": "2022-04-27T18:48:51.866Z",
    "deviceName": "m32sd10b",
    "deviceId": "17821468",
    "self": "https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17832512",
    "id": "17832512",
    "status": "PENDING",
    "description": "Apply software changes, triggered from PySys: [{'action': 'delete', 'id': '5475369', 'name': 'asciijump', 'url': ' ', 'version': '::apt'}, {'action': 'delete', 'id': '5474869', 'name': 'robotfindskitten', 'url': ' ', 'version': '::apt'}, {'action': 'delete', 'id': '5475279', 'name': 'squirrel3', 'url': ' ', 'version': '::apt'}]",
    "c8y_SoftwareUpdate": [
        {
            "name": "asciijump",
            "action": "delete",
            "id": "5475369",
            "version": "::apt",
            "url": " "
        },
        {
            "name": "robotfindskitten",
            "action": "delete",
            "id": "5474869",
            "version": "::apt",
            "url": " "
        },
        {
            "name": "squirrel3",
            "action": "delete",
            "id": "5475279",
            "version": "::apt",
            "url": " "
        }
    ]
}
18:48:52 INFO  Started operation: {'creationTime': '2022-04-27T18:48:51.866Z', 'deviceName': 'm32sd10b', 'deviceId': '17821468', 'self': 'https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17832512', 'id': '17832512', 'status': 'PENDING', 'description': "Apply software changes, triggered from PySys: [{'action': 'delete', 'id': '5475369', 'name': 'asciijump', 'url': ' ', 'version': '::apt'}, {'action': 'delete', 'id': '5474869', 'name': 'robotfindskitten', 'url': ' ', 'version': '::apt'}, {'action': 'delete', 'id': '5475279', 'name': 'squirrel3', 'url': ' ', 'version': '::apt'}]", 'c8y_SoftwareUpdate': [{'name': 'asciijump', 'action': 'delete', 'id': '5475369', 'version': '::apt', 'url': ' '}, {'name': 'robotfindskitten', 'action': 'delete', 'id': '5474869', 'version': '::apt', 'url': ' '}, {'name': 'squirrel3', 'action': 'delete', 'id': '5475279', 'version': '::apt', 'url': ' '}]}
18:48:54 INFO  State of operation 17832512 : PENDING
18:48:56 INFO  State of operation 17832512 : EXECUTING
18:48:58 INFO  State of operation 17832512 : EXECUTING
18:49:00 INFO  State of operation 17832512 : EXECUTING
18:49:03 INFO  State of operation 17832512 : EXECUTING
18:49:05 INFO  State of operation 17832512 : EXECUTING
18:49:07 INFO  State of operation 17832512 : EXECUTING
18:49:10 INFO  State of operation 17832512 : EXECUTING
18:49:12 INFO  State of operation 17832512 : EXECUTING
18:49:15 INFO  State of operation 17832512 : EXECUTING
18:49:17 INFO  State of operation 17832512 : EXECUTING
18:49:19 INFO  State of operation 17832512 : EXECUTING
18:49:21 INFO  State of operation 17832512 : EXECUTING
18:49:24 INFO  State of operation 17832512 : EXECUTING
18:49:26 INFO  State of operation 17832512 : EXECUTING
18:49:28 INFO  State of operation 17832512 : EXECUTING
18:49:31 INFO  State of operation 17832512 : EXECUTING
18:49:33 INFO  State of operation 17832512 : EXECUTING
18:49:36 INFO  State of operation 17832512 : EXECUTING
18:49:38 INFO  State of operation 17832512 : EXECUTING
18:49:40 INFO  State of operation 17832512 : EXECUTING
18:49:42 INFO  State of operation 17832512 : EXECUTING
18:49:45 INFO  State of operation 17832512 : EXECUTING
18:49:47 INFO  State of operation 17832512 : EXECUTING
18:49:49 INFO  State of operation 17832512 : EXECUTING
18:49:52 INFO  State of operation 17832512 : EXECUTING
18:49:54 INFO  State of operation 17832512 : EXECUTING
18:49:57 INFO  State of operation 17832512 : EXECUTING
18:49:59 INFO  State of operation 17832512 : EXECUTING
18:50:01 INFO  State of operation 17832512 : SUCCESSFUL
18:50:02 INFO  Assert that (False == value) with value=False ... passed
18:50:02 INFO  Assert that (False == value) with value=False ... passed
18:50:02 INFO  Assert that (False == value) with value=False ... passed
18:50:02 INFO  Assert that (False == value) with value=False ... passed
18:50:02 INFO  
18:50:02 INFO  cleanup:
18:50:06 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
18:50:07 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
18:50:07 INFO  
18:50:07 INFO  Test duration: 140.67 secs
18:50:07 INFO  Test final outcome:  FAILED
18:50:07 INFO  Test outcome reason: Assert that (False == value) with value=True (+2 other failures)
18:50:07 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="SoftwareManagement.sm_apt_install_remove_multiple_mixed" tests="3" errors="0" failures="2" skipped="1" time="0"><testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove_multiple_mixed">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it" />
		<system-out>17:42:05 INFO  ==============================================================
17:42:05 INFO  Id:    SoftwareManagement.sm_apt_install_remove_multiple_mixed
17:42:05 INFO  Dir:   software_management_end_to_end/
17:42:05 INFO  Title: Validate end to end behaviour for the apt plugin for multiple packages with mixed versions
17:42:05 INFO  ==============================================================
17:42:05 INFO  Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it ... skipped
17:42:05 WARN  Aborted test due to SKIPPED outcome
17:42:05 INFO  
17:42:05 INFO  Test duration: 0.02 secs
17:42:05 INFO  Test final outcome:  SKIPPED
17:42:05 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it
17:42:05 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove_multiple_mixed">
		<failure message="BLOCKED: SystemError: Timeout while waiting for status SUCCESSFUL or False" type="BLOCKED" />
		<system-out>18:16:22 INFO  ==============================================================
18:16:22 INFO  Id:    SoftwareManagement.sm_apt_install_remove_multiple_mixed
18:16:22 INFO  Dir:   software_management_end_to_end/
18:16:22 INFO  Title: Validate end to end behaviour for the apt plugin for multiple packages with mixed versions
18:16:22 INFO  ==============================================================
18:16:22 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
18:16:22 INFO  EnvironmentC8y Setup
18:16:23 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
18:16:23 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 4 seconds
18:16:23 INFO  Delaying execution by 7 seconds
18:16:44 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 13 secs
18:16:44 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
18:16:45 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
18:16:45 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
18:16:47 INFO  State of current operation: SUCCESSFUL
18:16:48 INFO  Assert that (False == value) with value=False ... passed
18:16:48 INFO  Assert that (False == value) with value=False ... passed
18:16:48 INFO  Assert that (False == value) with value=False ... passed
18:16:48 INFO  Assert that (False == value) with value=False ... passed
18:16:48 INFO  Assert that (False == value) with value=False ... passed
18:16:50 INFO  Response status: 201
18:16:50 INFO  Response to action: {
    "creationTime": "2022-04-27T18:16:50.129Z",
    "deviceName": "m32sd10b",
    "deviceId": "17821468",
    "self": "https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17832412",
    "id": "17832412",
    "status": "PENDING",
    "description": "Apply software changes, triggered from PySys: [{'action': 'install', 'id': '5475369', 'name': 'asciijump', 'url': ' ', 'version': '::apt'}, {'action': 'install', 'id': '5474869', 'name': 'robotfindskitten', 'url': ' ', 'version': ' '}, {'action': 'install', 'id': '5475279', 'name': 'squirrel3', 'url': ' ', 'version': '3.1-7::apt'}, {'action': 'install', 'id': '5152439', 'name': 'rolldice', 'url': ' ', 'version': '1.16-1+b1'}, {'action': 'install', 'id': '5439204', 'name': 'moon-buggy', 'url': ' ', 'version': '1:1.0.51-12'}, {'action': 'install', 'id': '5475369', 'name': 'asciijump', 'url': ' ', 'version': '::apt'}]",
    "c8y_SoftwareUpdate": [
        {
            "name": "asciijump",
            "action": "install",
            "id": "5475369",
            "version": "::apt",
            "url": " "
        },
        {
            "name": "robotfindskitten",
            "action": "install",
            "id": "5474869",
            "version": " ",
            "url": " "
        },
        {
            "name": "squirrel3",
            "action": "install",
            "id": "5475279",
            "version": "3.1-7::apt",
            "url": " "
        },
        {
            "name": "rolldice",
            "action": "install",
            "id": "5152439",
            "version": "1.16-1+b1",
            "url": " "
        },
        {
            "name": "moon-buggy",
            "action": "install",
            "id": "5439204",
            "version": "1:1.0.51-12",
            "url": " "
        },
        {
            "name": "asciijump",
            "action": "install",
            "id": "5475369",
            "version": "::apt",
            "url": " "
        }
    ]
}
18:16:50 INFO  Started operation: {'creationTime': '2022-04-27T18:16:50.129Z', 'deviceName': 'm32sd10b', 'deviceId': '17821468', 'self': 'https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17832412', 'id': '17832412', 'status': 'PENDING', 'description': "Apply software changes, triggered from PySys: [{'action': 'install', 'id': '5475369', 'name': 'asciijump', 'url': ' ', 'version': '::apt'}, {'action': 'install', 'id': '5474869', 'name': 'robotfindskitten', 'url': ' ', 'version': ' '}, {'action': 'install', 'id': '5475279', 'name': 'squirrel3', 'url': ' ', 'version': '3.1-7::apt'}, {'action': 'install', 'id': '5152439', 'name': 'rolldice', 'url': ' ', 'version': '1.16-1+b1'}, {'action': 'install', 'id': '5439204', 'name': 'moon-buggy', 'url': ' ', 'version': '1:1.0.51-12'}, {'action': 'install', 'id': '5475369', 'name': 'asciijump', 'url': ' ', 'version': '::apt'}]", 'c8y_SoftwareUpdate': [{'name': 'asciijump', 'action': 'install', 'id': '5475369', 'version': '::apt', 'url': ' '}, {'name': 'robotfindskitten', 'action': 'install', 'id': '5474869', 'version': ' ', 'url': ' '}, {'name': 'squirrel3', 'action': 'install', 'id': '5475279', 'version': '3.1-7::apt', 'url': ' '}, {'name': 'rolldice', 'action': 'install', 'id': '5152439', 'version': '1.16-1+b1', 'url': ' '}, {'name': 'moon-buggy', 'action': 'install', 'id': '5439204', 'version': '1:1.0.51-12', 'url': ' '}, {'name': 'asciijump', 'action': 'install', 'id': '5475369', 'version': '::apt', 'url': ' '}]}
18:16:52 INFO  State of operation 17832412 : PENDING
18:16:54 INFO  State of operation 17832412 : EXECUTING
18:16:56 INFO  State of operation 17832412 : EXECUTING
18:16:59 INFO  State of operation 17832412 : EXECUTING
18:17:01 INFO  State of operation 17832412 : EXECUTING
18:17:03 INFO  State of operation 17832412 : EXECUTING
18:17:06 INFO  State of operation 17832412 : EXECUTING
18:17:09 INFO  State of operation 17832412 : EXECUTING
18:17:11 INFO  State of operation 17832412 : EXECUTING
18:17:13 INFO  State of operation 17832412 : EXECUTING
18:17:15 INFO  State of operation 17832412 : EXECUTING
18:17:18 INFO  State of operation 17832412 : EXECUTING
18:17:20 INFO  State of operation 17832412 : EXECUTING
18:17:22 INFO  State of operation 17832412 : EXECUTING
18:17:24 INFO  State of operation 17832412 : EXECUTING
18:17:27 INFO  State of operation 17832412 : EXECUTING
18:17:29 INFO  State of operation 17832412 : EXECUTING
18:17:32 INFO  State of operation 17832412 : EXECUTING
18:17:34 INFO  State of operation 17832412 : EXECUTING
18:17:36 INFO  State of operation 17832412 : EXECUTING
18:17:38 INFO  State of operation 17832412 : EXECUTING
18:17:41 INFO  State of operation 17832412 : EXECUTING
18:17:43 INFO  State of operation 17832412 : EXECUTING
18:17:46 INFO  State of operation 17832412 : EXECUTING
18:17:48 INFO  State of operation 17832412 : EXECUTING
18:17:50 INFO  State of operation 17832412 : EXECUTING
18:17:53 INFO  State of operation 17832412 : EXECUTING
18:17:55 INFO  State of operation 17832412 : EXECUTING
18:17:57 INFO  State of operation 17832412 : EXECUTING
18:17:59 INFO  State of operation 17832412 : EXECUTING
18:18:02 INFO  State of operation 17832412 : EXECUTING
18:18:04 INFO  State of operation 17832412 : EXECUTING
18:18:06 INFO  State of operation 17832412 : EXECUTING
18:18:08 INFO  State of operation 17832412 : EXECUTING
18:18:11 INFO  State of operation 17832412 : EXECUTING
18:18:13 INFO  State of operation 17832412 : EXECUTING
18:18:15 INFO  State of operation 17832412 : EXECUTING
18:18:17 INFO  State of operation 17832412 : EXECUTING
18:18:20 INFO  State of operation 17832412 : EXECUTING
18:18:23 INFO  State of operation 17832412 : EXECUTING
18:18:25 INFO  State of operation 17832412 : EXECUTING
18:18:28 INFO  State of operation 17832412 : EXECUTING
18:18:30 INFO  State of operation 17832412 : EXECUTING
18:18:32 INFO  State of operation 17832412 : EXECUTING
18:18:34 INFO  State of operation 17832412 : EXECUTING
18:18:36 INFO  State of operation 17832412 : EXECUTING
18:18:39 INFO  State of operation 17832412 : EXECUTING
18:18:41 INFO  State of operation 17832412 : EXECUTING
18:18:43 INFO  State of operation 17832412 : EXECUTING
18:18:46 INFO  State of operation 17832412 : EXECUTING
18:18:49 INFO  State of operation 17832412 : EXECUTING
18:18:51 INFO  State of operation 17832412 : EXECUTING
18:18:53 INFO  State of operation 17832412 : EXECUTING
18:18:56 INFO  State of operation 17832412 : EXECUTING
18:18:58 INFO  State of operation 17832412 : EXECUTING
18:19:00 INFO  State of operation 17832412 : EXECUTING
18:19:03 INFO  State of operation 17832412 : EXECUTING
18:19:05 INFO  State of operation 17832412 : EXECUTING
18:19:08 INFO  State of operation 17832412 : EXECUTING
18:19:10 INFO  State of operation 17832412 : EXECUTING
18:19:12 INFO  State of operation 17832412 : EXECUTING
18:19:14 WARN  SystemError occurred while running test - Timeout while waiting for status SUCCESSFUL or False
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1294, in __call__
    self.testObj.execute()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple_mixed/run.py", line 89, in execute
    self.wait_until_succcess()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 324, in wait_until_succcess
    self.wait_until_status("SUCCESSFUL")
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 381, in wait_until_status
    "Timeout while waiting for status %s or %s" % (status, status2)
SystemError: Timeout while waiting for status SUCCESSFUL or False
18:19:14 WARN  SystemError: Timeout while waiting for status SUCCESSFUL or False ... blocked 
18:19:14 INFO  
18:19:14 INFO  cleanup:
18:19:21 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
18:19:21 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
18:19:21 INFO  
18:19:21 INFO  Test duration: 179.14 secs
18:19:21 INFO  Test final outcome:  BLOCKED
18:19:21 INFO  Test outcome reason: SystemError: Timeout while waiting for status SUCCESSFUL or False
18:19:21 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove_multiple_mixed">
		<failure message="BLOCKED: SystemError: Timeout while waiting for status SUCCESSFUL or False (+1 other failures)" type="BLOCKED" />
		<system-out>18:50:07 INFO  ==============================================================
18:50:07 INFO  Id:    SoftwareManagement.sm_apt_install_remove_multiple_mixed
18:50:07 INFO  Dir:   software_management_end_to_end/
18:50:07 INFO  Title: Validate end to end behaviour for the apt plugin for multiple packages with mixed versions
18:50:07 INFO  ==============================================================
18:50:07 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
18:50:07 INFO  EnvironmentC8y Setup
18:50:08 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
18:50:08 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 4 seconds
18:50:08 INFO  Delaying execution by 7 seconds
18:50:29 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
18:50:29 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
18:50:30 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
18:50:30 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
18:50:32 INFO  State of current operation: SUCCESSFUL
18:50:33 INFO  Assert that (False == value) with value=False ... passed
18:50:33 INFO  Assert that (False == value) with value=False ... passed
18:50:33 INFO  Assert that (False == value) with value=False ... passed
18:50:33 INFO  Assert that (False == value) with value=False ... passed
18:50:34 INFO  Package moon-buggy is installed
18:50:34 WARN  Assert that (False == value) with value=True ... failed 
18:50:35 INFO  Response status: 201
18:50:35 INFO  Response to action: {
    "creationTime": "2022-04-27T18:50:35.308Z",
    "deviceName": "m32sd10b",
    "deviceId": "17821468",
    "self": "https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17832519",
    "id": "17832519",
    "status": "PENDING",
    "description": "Apply software changes, triggered from PySys: [{'action': 'install', 'id': '5475369', 'name': 'asciijump', 'url': ' ', 'version': '::apt'}, {'action': 'install', 'id': '5474869', 'name': 'robotfindskitten', 'url': ' ', 'version': ' '}, {'action': 'install', 'id': '5475279', 'name': 'squirrel3', 'url': ' ', 'version': '3.1-7::apt'}, {'action': 'install', 'id': '5152439', 'name': 'rolldice', 'url': ' ', 'version': '1.16-1+b1'}, {'action': 'install', 'id': '5439204', 'name': 'moon-buggy', 'url': ' ', 'version': '1:1.0.51-12'}, {'action': 'install', 'id': '5475369', 'name': 'asciijump', 'url': ' ', 'version': '::apt'}]",
    "c8y_SoftwareUpdate": [
        {
            "name": "asciijump",
            "action": "install",
            "id": "5475369",
            "version": "::apt",
            "url": " "
        },
        {
            "name": "robotfindskitten",
            "action": "install",
            "id": "5474869",
            "version": " ",
            "url": " "
        },
        {
            "name": "squirrel3",
            "action": "install",
            "id": "5475279",
            "version": "3.1-7::apt",
            "url": " "
        },
        {
            "name": "rolldice",
            "action": "install",
            "id": "5152439",
            "version": "1.16-1+b1",
            "url": " "
        },
        {
            "name": "moon-buggy",
            "action": "install",
            "id": "5439204",
            "version": "1:1.0.51-12",
            "url": " "
        },
        {
            "name": "asciijump",
            "action": "install",
            "id": "5475369",
            "version": "::apt",
            "url": " "
        }
    ]
}
18:50:35 INFO  Started operation: {'creationTime': '2022-04-27T18:50:35.308Z', 'deviceName': 'm32sd10b', 'deviceId': '17821468', 'self': 'https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17832519', 'id': '17832519', 'status': 'PENDING', 'description': "Apply software changes, triggered from PySys: [{'action': 'install', 'id': '5475369', 'name': 'asciijump', 'url': ' ', 'version': '::apt'}, {'action': 'install', 'id': '5474869', 'name': 'robotfindskitten', 'url': ' ', 'version': ' '}, {'action': 'install', 'id': '5475279', 'name': 'squirrel3', 'url': ' ', 'version': '3.1-7::apt'}, {'action': 'install', 'id': '5152439', 'name': 'rolldice', 'url': ' ', 'version': '1.16-1+b1'}, {'action': 'install', 'id': '5439204', 'name': 'moon-buggy', 'url': ' ', 'version': '1:1.0.51-12'}, {'action': 'install', 'id': '5475369', 'name': 'asciijump', 'url': ' ', 'version': '::apt'}]", 'c8y_SoftwareUpdate': [{'name': 'asciijump', 'action': 'install', 'id': '5475369', 'version': '::apt', 'url': ' '}, {'name': 'robotfindskitten', 'action': 'install', 'id': '5474869', 'version': ' ', 'url': ' '}, {'name': 'squirrel3', 'action': 'install', 'id': '5475279', 'version': '3.1-7::apt', 'url': ' '}, {'name': 'rolldice', 'action': 'install', 'id': '5152439', 'version': '1.16-1+b1', 'url': ' '}, {'name': 'moon-buggy', 'action': 'install', 'id': '5439204', 'version': '1:1.0.51-12', 'url': ' '}, {'name': 'asciijump', 'action': 'install', 'id': '5475369', 'version': '::apt', 'url': ' '}]}
18:50:37 INFO  State of operation 17832519 : PENDING
18:50:39 INFO  State of operation 17832519 : EXECUTING
18:50:42 INFO  State of operation 17832519 : EXECUTING
18:50:44 INFO  State of operation 17832519 : EXECUTING
18:50:46 INFO  State of operation 17832519 : EXECUTING
18:50:49 INFO  State of operation 17832519 : EXECUTING
18:50:51 INFO  State of operation 17832519 : EXECUTING
18:50:54 INFO  State of operation 17832519 : EXECUTING
18:50:56 INFO  State of operation 17832519 : EXECUTING
18:50:59 INFO  State of operation 17832519 : EXECUTING
18:51:01 INFO  State of operation 17832519 : EXECUTING
18:51:03 INFO  State of operation 17832519 : EXECUTING
18:51:05 INFO  State of operation 17832519 : EXECUTING
18:51:08 INFO  State of operation 17832519 : EXECUTING
18:51:10 INFO  State of operation 17832519 : EXECUTING
18:51:12 INFO  State of operation 17832519 : EXECUTING
18:51:14 INFO  State of operation 17832519 : EXECUTING
18:51:17 INFO  State of operation 17832519 : EXECUTING
18:51:19 INFO  State of operation 17832519 : EXECUTING
18:51:22 INFO  State of operation 17832519 : EXECUTING
18:51:24 INFO  State of operation 17832519 : EXECUTING
18:51:26 INFO  State of operation 17832519 : EXECUTING
18:51:28 INFO  State of operation 17832519 : EXECUTING
18:51:30 INFO  State of operation 17832519 : EXECUTING
18:51:33 INFO  State of operation 17832519 : EXECUTING
18:51:36 INFO  State of operation 17832519 : EXECUTING
18:51:38 INFO  State of operation 17832519 : EXECUTING
18:51:41 INFO  State of operation 17832519 : EXECUTING
18:51:43 INFO  State of operation 17832519 : EXECUTING
18:51:45 INFO  State of operation 17832519 : EXECUTING
18:51:48 INFO  State of operation 17832519 : EXECUTING
18:51:50 INFO  State of operation 17832519 : EXECUTING
18:51:52 INFO  State of operation 17832519 : EXECUTING
18:51:55 INFO  State of operation 17832519 : EXECUTING
18:51:57 INFO  State of operation 17832519 : EXECUTING
18:51:59 INFO  State of operation 17832519 : EXECUTING
18:52:01 INFO  State of operation 17832519 : EXECUTING
18:52:03 INFO  State of operation 17832519 : EXECUTING
18:52:06 INFO  State of operation 17832519 : EXECUTING
18:52:09 INFO  State of operation 17832519 : EXECUTING
18:52:11 INFO  State of operation 17832519 : EXECUTING
18:52:13 INFO  State of operation 17832519 : EXECUTING
18:52:16 INFO  State of operation 17832519 : EXECUTING
18:52:18 INFO  State of operation 17832519 : EXECUTING
18:52:20 INFO  State of operation 17832519 : EXECUTING
18:52:22 INFO  State of operation 17832519 : EXECUTING
18:52:25 INFO  State of operation 17832519 : EXECUTING
18:52:27 INFO  State of operation 17832519 : EXECUTING
18:52:29 INFO  State of operation 17832519 : EXECUTING
18:52:32 INFO  State of operation 17832519 : EXECUTING
18:52:34 INFO  State of operation 17832519 : EXECUTING
18:52:37 INFO  State of operation 17832519 : EXECUTING
18:52:39 INFO  State of operation 17832519 : EXECUTING
18:52:42 INFO  State of operation 17832519 : EXECUTING
18:52:44 INFO  State of operation 17832519 : EXECUTING
18:52:46 INFO  State of operation 17832519 : EXECUTING
18:52:48 INFO  State of operation 17832519 : EXECUTING
18:52:51 INFO  State of operation 17832519 : EXECUTING
18:52:53 INFO  State of operation 17832519 : EXECUTING
18:52:55 INFO  State of operation 17832519 : EXECUTING
18:52:57 INFO  State of operation 17832519 : EXECUTING
18:52:59 WARN  SystemError occurred while running test - Timeout while waiting for status SUCCESSFUL or False
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1294, in __call__
    self.testObj.execute()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple_mixed/run.py", line 89, in execute
    self.wait_until_succcess()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 324, in wait_until_succcess
    self.wait_until_status("SUCCESSFUL")
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 381, in wait_until_status
    "Timeout while waiting for status %s or %s" % (status, status2)
SystemError: Timeout while waiting for status SUCCESSFUL or False
18:53:00 WARN  SystemError: Timeout while waiting for status SUCCESSFUL or False ... blocked 
18:53:00 INFO  
18:53:00 INFO  cleanup:
18:53:05 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
18:53:05 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
18:53:05 INFO  
18:53:05 INFO  Test duration: 178.16 secs
18:53:05 INFO  Test final outcome:  BLOCKED
18:53:05 INFO  Test outcome reason: SystemError: Timeout while waiting for status SUCCESSFUL or False (+1 other failures)
18:53:05 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="SoftwareManagement.sm_apt_install_remove_with_version" tests="3" errors="0" failures="0" skipped="1" time="0"><testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove_with_version">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it" />
		<system-out>17:42:05 INFO  ==============================================================
17:42:05 INFO  Id:    SoftwareManagement.sm_apt_install_remove_with_version
17:42:05 INFO  Dir:   software_management_end_to_end/
17:42:05 INFO  Title: Validate end to end behaviour for the apt plugin for packages with version
17:42:05 INFO  ==============================================================
17:42:05 INFO  Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it ... skipped
17:42:05 WARN  Aborted test due to SKIPPED outcome
17:42:05 INFO  
17:42:05 INFO  Test duration: 0.02 secs
17:42:05 INFO  Test final outcome:  SKIPPED
17:42:05 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it
17:42:05 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove_with_version" />
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove_with_version" />
</testsuite><testsuite name="SoftwareManagement.sm_docker_install_remove_multiple" tests="3" errors="0" failures="2" skipped="1" time="0"><testcase classname="SMDockerInstallRemove" name="SoftwareManagement.sm_docker_install_remove_multiple">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it" />
		<system-out>17:42:05 INFO  ==============================================================
17:42:05 INFO  Id:    SoftwareManagement.sm_docker_install_remove_multiple
17:42:05 INFO  Dir:   software_management_end_to_end/
17:42:05 INFO  Title: Validate end to end behaviour for the docker plugin for multiple docker images with mixed versions
17:42:05 INFO  ==============================================================
17:42:05 INFO  Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it ... skipped
17:42:05 WARN  Aborted test due to SKIPPED outcome
17:42:05 INFO  
17:42:05 INFO  Test duration: 0.02 secs
17:42:05 INFO  Test final outcome:  SKIPPED
17:42:05 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.Use parameter -XmyPlatform='container' to enable it
17:42:05 INFO  
</system-out>
	</testcase>
<testcase classname="SMDockerInstallRemove" name="SoftwareManagement.sm_docker_install_remove_multiple">
		<failure message="BLOCKED: SystemError: The operation has failed" type="BLOCKED" />
		<system-out>18:26:37 INFO  ==============================================================
18:26:37 INFO  Id:    SoftwareManagement.sm_docker_install_remove_multiple
18:26:37 INFO  Dir:   software_management_end_to_end/
18:26:37 INFO  Title: Validate end to end behaviour for the docker plugin for multiple docker images with mixed versions
18:26:37 INFO  ==============================================================
18:26:39 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
18:26:39 INFO  EnvironmentC8y Setup
18:26:40 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
18:26:57 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 16 secs
18:26:57 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
18:26:58 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
18:26:58 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
18:27:01 INFO  State of current operation: SUCCESSFUL
18:27:01 INFO  Response status: 201
18:27:01 INFO  Response to action: {
    "creationTime": "2022-04-27T18:27:01.427Z",
    "deviceName": "m32sd10b",
    "deviceId": "17821468",
    "self": "https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17832440",
    "id": "17832440",
    "status": "PENDING",
    "description": "Apply software changes, triggered from PySys: [{'action': 'install', 'id': '8021526', 'name': 'hello-world', 'url': '', 'version': '::docker'}, {'action': 'install', 'id': '8018911', 'name': 'registry', 'url': '', 'version': '2.6.2::docker'}]",
    "c8y_SoftwareUpdate": [
        {
            "name": "hello-world",
            "action": "install",
            "id": "8021526",
            "version": "::docker",
            "url": ""
        },
        {
            "name": "registry",
            "action": "install",
            "id": "8018911",
            "version": "2.6.2::docker",
            "url": ""
        }
    ]
}
18:27:01 INFO  Started operation: {'creationTime': '2022-04-27T18:27:01.427Z', 'deviceName': 'm32sd10b', 'deviceId': '17821468', 'self': 'https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17832440', 'id': '17832440', 'status': 'PENDING', 'description': "Apply software changes, triggered from PySys: [{'action': 'install', 'id': '8021526', 'name': 'hello-world', 'url': '', 'version': '::docker'}, {'action': 'install', 'id': '8018911', 'name': 'registry', 'url': '', 'version': '2.6.2::docker'}]", 'c8y_SoftwareUpdate': [{'name': 'hello-world', 'action': 'install', 'id': '8021526', 'version': '::docker', 'url': ''}, {'name': 'registry', 'action': 'install', 'id': '8018911', 'version': '2.6.2::docker', 'url': ''}]}
18:27:03 INFO  State of operation 17832440 : PENDING
18:27:05 INFO  State of operation 17832440 : EXECUTING
18:27:08 INFO  State of operation 17832440 : EXECUTING
18:27:10 INFO  State of operation 17832440 : EXECUTING
18:27:12 INFO  State of operation 17832440 : EXECUTING
18:27:15 INFO  State of operation 17832440 : EXECUTING
18:27:17 INFO  State of operation 17832440 : EXECUTING
18:27:19 INFO  State of operation 17832440 : EXECUTING
18:27:22 INFO  State of operation 17832440 : EXECUTING
18:27:24 INFO  State of operation 17832440 : EXECUTING
18:27:26 INFO  State of operation 17832440 : EXECUTING
18:27:29 INFO  State of operation 17832440 : EXECUTING
18:27:31 INFO  State of operation 17832440 : EXECUTING
18:27:33 INFO  State of operation 17832440 : EXECUTING
18:27:35 INFO  State of operation 17832440 : EXECUTING
18:27:37 INFO  State of operation 17832440 : EXECUTING
18:27:40 INFO  State of operation 17832440 : SUCCESSFUL
18:27:41 INFO  Package hello-world is installed
18:27:41 INFO  Package hello-world is installed
18:27:41 INFO  Assert that (True == value) with value=True ... passed
18:27:41 INFO  Package registry is installed
18:27:41 INFO  Assert that (True == value) with value=True ... passed
18:27:42 INFO  Assert that (False == value) with value=False ... passed
18:27:42 INFO  Response status: 201
18:27:42 INFO  Response to action: {
    "creationTime": "2022-04-27T18:27:42.316Z",
    "deviceName": "m32sd10b",
    "deviceId": "17821468",
    "self": "https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17832444",
    "id": "17832444",
    "status": "PENDING",
    "description": "Apply software changes, triggered from PySys: [{'action': 'install', 'id': '8018911', 'name': 'registry', 'url': '', 'version': '2.7.1::docker'}, {'action': 'install', 'id': '7991792', 'name': 'alpine', 'url': '', 'version': '::docker'}]",
    "c8y_SoftwareUpdate": [
        {
            "name": "registry",
            "action": "install",
            "id": "8018911",
            "version": "2.7.1::docker",
            "url": ""
        },
        {
            "name": "alpine",
            "action": "install",
            "id": "7991792",
            "version": "::docker",
            "url": ""
        }
    ]
}
18:27:42 INFO  Started operation: {'creationTime': '2022-04-27T18:27:42.316Z', 'deviceName': 'm32sd10b', 'deviceId': '17821468', 'self': 'https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17832444', 'id': '17832444', 'status': 'PENDING', 'description': "Apply software changes, triggered from PySys: [{'action': 'install', 'id': '8018911', 'name': 'registry', 'url': '', 'version': '2.7.1::docker'}, {'action': 'install', 'id': '7991792', 'name': 'alpine', 'url': '', 'version': '::docker'}]", 'c8y_SoftwareUpdate': [{'name': 'registry', 'action': 'install', 'id': '8018911', 'version': '2.7.1::docker', 'url': ''}, {'name': 'alpine', 'action': 'install', 'id': '7991792', 'version': '::docker', 'url': ''}]}
18:27:44 INFO  State of operation 17832444 : PENDING
18:27:46 INFO  State of operation 17832444 : EXECUTING
18:27:49 INFO  State of operation 17832444 : EXECUTING
18:27:51 INFO  State of operation 17832444 : EXECUTING
18:27:53 INFO  State of operation 17832444 : EXECUTING
18:27:55 INFO  State of operation 17832444 : EXECUTING
18:27:58 INFO  State of operation 17832444 : EXECUTING
18:28:00 INFO  State of operation 17832444 : EXECUTING
18:28:02 INFO  State of operation 17832444 : EXECUTING
18:28:04 INFO  State of operation 17832444 : EXECUTING
18:28:07 INFO  State of operation 17832444 : EXECUTING
18:28:09 INFO  State of operation 17832444 : EXECUTING
18:28:11 INFO  State of operation 17832444 : EXECUTING
18:28:13 INFO  State of operation 17832444 : EXECUTING
18:28:16 INFO  State of operation 17832444 : EXECUTING
18:28:18 INFO  State of operation 17832444 : EXECUTING
18:28:20 INFO  State of operation 17832444 : EXECUTING
18:28:22 INFO  State of operation 17832444 : FAILED
18:28:22 ERROR Stopping as the operation has failed
18:28:22 WARN  SystemError occurred while running test - The operation has failed
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1294, in __call__
    self.testObj.execute()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_docker_install_remove_multiple/run.py", line 91, in execute
    self.wait_until_succcess()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 324, in wait_until_succcess
    self.wait_until_status("SUCCESSFUL")
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 361, in wait_until_status
    raise SystemError("The operation has failed")
SystemError: The operation has failed
18:28:23 WARN  SystemError: The operation has failed ... blocked 
18:28:23 INFO  
18:28:23 INFO  cleanup:
18:28:23 INFO  Response status: 201
18:28:23 INFO  Response to action: {
    "creationTime": "2022-04-27T18:28:23.683Z",
    "deviceName": "m32sd10b",
    "deviceId": "17821468",
    "self": "https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17832452",
    "id": "17832452",
    "status": "PENDING",
    "description": "Apply software changes, triggered from PySys: [{'action': 'delete', 'id': '8018911', 'name': 'registry', 'url': '', 'version': '2.7.1::docker'}, {'action': 'delete', 'id': '7991792', 'name': 'alpine', 'url': '', 'version': '::docker'}, {'action': 'delete', 'id': '8021526', 'name': 'hello-world', 'url': '', 'version': '::docker'}]",
    "c8y_SoftwareUpdate": [
        {
            "name": "registry",
            "action": "delete",
            "id": "8018911",
            "version": "2.7.1::docker",
            "url": ""
        },
        {
            "name": "alpine",
            "action": "delete",
            "id": "7991792",
            "version": "::docker",
            "url": ""
        },
        {
            "name": "hello-world",
            "action": "delete",
            "id": "8021526",
            "version": "::docker",
            "url": ""
        }
    ]
}
18:28:23 INFO  Started operation: {'creationTime': '2022-04-27T18:28:23.683Z', 'deviceName': 'm32sd10b', 'deviceId': '17821468', 'self': 'https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17832452', 'id': '17832452', 'status': 'PENDING', 'description': "Apply software changes, triggered from PySys: [{'action': 'delete', 'id': '8018911', 'name': 'registry', 'url': '', 'version': '2.7.1::docker'}, {'action': 'delete', 'id': '7991792', 'name': 'alpine', 'url': '', 'version': '::docker'}, {'action': 'delete', 'id': '8021526', 'name': 'hello-world', 'url': '', 'version': '::docker'}]", 'c8y_SoftwareUpdate': [{'name': 'registry', 'action': 'delete', 'id': '8018911', 'version': '2.7.1::docker', 'url': ''}, {'name': 'alpine', 'action': 'delete', 'id': '7991792', 'version': '::docker', 'url': ''}, {'name': 'hello-world', 'action': 'delete', 'id': '8021526', 'version': '::docker', 'url': ''}]}
18:28:25 INFO  State of operation 17832452 : PENDING
18:28:28 INFO  State of operation 17832452 : EXECUTING
18:28:30 INFO  State of operation 17832452 : EXECUTING
18:28:32 INFO  State of operation 17832452 : EXECUTING
18:28:34 INFO  State of operation 17832452 : EXECUTING
18:28:37 INFO  State of operation 17832452 : EXECUTING
18:28:39 INFO  State of operation 17832452 : EXECUTING
18:28:41 INFO  State of operation 17832452 : SUCCESSFUL
18:28:52 INFO  Assert that (False == value) with value=False ... passed
18:28:52 INFO  Assert that (False == value) with value=False ... passed
18:28:53 INFO  Assert that (False == value) with value=False ... passed
18:28:57 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
18:28:57 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
18:28:57 INFO  
18:28:57 INFO  Test duration: 140.53 secs
18:28:57 INFO  Test final outcome:  BLOCKED
18:28:57 INFO  Test outcome reason: SystemError: The operation has failed
18:28:57 INFO  
</system-out>
	</testcase>
<testcase classname="SMDockerInstallRemove" name="SoftwareManagement.sm_docker_install_remove_multiple">
		<failure message="BLOCKED: SystemError: The operation has failed" type="BLOCKED" />
		<system-out>18:55:42 INFO  ==============================================================
18:55:42 INFO  Id:    SoftwareManagement.sm_docker_install_remove_multiple
18:55:42 INFO  Dir:   software_management_end_to_end/
18:55:42 INFO  Title: Validate end to end behaviour for the docker plugin for multiple docker images with mixed versions
18:55:42 INFO  ==============================================================
18:55:42 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
18:55:42 INFO  EnvironmentC8y Setup
18:55:42 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
18:55:42 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 5 seconds
18:55:42 INFO  Delaying execution by 6 seconds
18:56:02 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
18:56:03 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
18:56:04 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
18:56:04 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
18:56:06 INFO  State of current operation: SUCCESSFUL
18:56:06 INFO  Response status: 201
18:56:06 INFO  Response to action: {
    "creationTime": "2022-04-27T18:56:06.936Z",
    "deviceName": "m32sd10b",
    "deviceId": "17821468",
    "self": "https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17832535",
    "id": "17832535",
    "status": "PENDING",
    "description": "Apply software changes, triggered from PySys: [{'action': 'install', 'id': '8021526', 'name': 'hello-world', 'url': '', 'version': '::docker'}, {'action': 'install', 'id': '8018911', 'name': 'registry', 'url': '', 'version': '2.6.2::docker'}]",
    "c8y_SoftwareUpdate": [
        {
            "name": "hello-world",
            "action": "install",
            "id": "8021526",
            "version": "::docker",
            "url": ""
        },
        {
            "name": "registry",
            "action": "install",
            "id": "8018911",
            "version": "2.6.2::docker",
            "url": ""
        }
    ]
}
18:56:06 INFO  Started operation: {'creationTime': '2022-04-27T18:56:06.936Z', 'deviceName': 'm32sd10b', 'deviceId': '17821468', 'self': 'https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17832535', 'id': '17832535', 'status': 'PENDING', 'description': "Apply software changes, triggered from PySys: [{'action': 'install', 'id': '8021526', 'name': 'hello-world', 'url': '', 'version': '::docker'}, {'action': 'install', 'id': '8018911', 'name': 'registry', 'url': '', 'version': '2.6.2::docker'}]", 'c8y_SoftwareUpdate': [{'name': 'hello-world', 'action': 'install', 'id': '8021526', 'version': '::docker', 'url': ''}, {'name': 'registry', 'action': 'install', 'id': '8018911', 'version': '2.6.2::docker', 'url': ''}]}
18:56:09 INFO  State of operation 17832535 : PENDING
18:56:11 INFO  State of operation 17832535 : EXECUTING
18:56:13 INFO  State of operation 17832535 : EXECUTING
18:56:15 INFO  State of operation 17832535 : EXECUTING
18:56:18 INFO  State of operation 17832535 : EXECUTING
18:56:20 INFO  State of operation 17832535 : FAILED
18:56:20 ERROR Stopping as the operation has failed
18:56:20 WARN  SystemError occurred while running test - The operation has failed
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1292, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_docker_install_remove_multiple/run.py", line 55, in setup
    self.wait_until_succcess()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 324, in wait_until_succcess
    self.wait_until_status("SUCCESSFUL")
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 361, in wait_until_status
    raise SystemError("The operation has failed")
SystemError: The operation has failed
18:56:20 WARN  SystemError: The operation has failed ... blocked 
18:56:20 INFO  
18:56:20 INFO  cleanup:
18:56:24 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
18:56:24 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
18:56:24 INFO  
18:56:24 INFO  Test duration: 42.63 secs
18:56:24 INFO  Test final outcome:  BLOCKED
18:56:24 INFO  Test outcome reason: SystemError: The operation has failed
18:56:24 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="SoftwareManagement.sm_fake_install_remove" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="PySysTest" name="SoftwareManagement.sm_fake_install_remove">
		<skipped message="SKIPPED: Testing the fake plugin is not enabled.Use parameter -Xfakeplugin=fakeplugin to enable it" />
		<system-out>17:42:05 INFO  ==============================================================
17:42:05 INFO  Id:    SoftwareManagement.sm_fake_install_remove
17:42:05 INFO  Dir:   software_management_end_to_end/
17:42:05 INFO  Title: Validate end to end behaviour for the dummy plugin for installation and removal of packages
17:42:05 INFO  ==============================================================
17:42:05 INFO  Testing the fake plugin is not enabled.Use parameter -Xfakeplugin=fakeplugin to enable it ... skipped
17:42:05 WARN  Aborted test due to SKIPPED outcome
17:42:05 INFO  
17:42:05 INFO  Test duration: 0.02 secs
17:42:05 INFO  Test final outcome:  SKIPPED
17:42:05 INFO  Test outcome reason: Testing the fake plugin is not enabled.Use parameter -Xfakeplugin=fakeplugin to enable it
17:42:05 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_fake_install_remove" />
</testsuite><testsuite name="SoftwareManagement.sm_fake_install_remove_multiple" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="PySysTest" name="SoftwareManagement.sm_fake_install_remove_multiple">
		<skipped message="SKIPPED: Testing the fake plugin is not enabled.Use parameter -Xfakeplugin=fakeplugin to enable it" />
		<system-out>17:42:05 INFO  ==============================================================
17:42:05 INFO  Id:    SoftwareManagement.sm_fake_install_remove_multiple
17:42:05 INFO  Dir:   software_management_end_to_end/
17:42:05 INFO  Title: Validate end to end behaviour for the dummy-plugin for multiple packages
17:42:05 INFO  ==============================================================
17:42:05 INFO  Testing the fake plugin is not enabled.Use parameter -Xfakeplugin=fakeplugin to enable it ... skipped
17:42:05 WARN  Aborted test due to SKIPPED outcome
17:42:05 INFO  
17:42:05 INFO  Test duration: 0.03 secs
17:42:05 INFO  Test final outcome:  SKIPPED
17:42:05 INFO  Test outcome reason: Testing the fake plugin is not enabled.Use parameter -Xfakeplugin=fakeplugin to enable it
17:42:05 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_fake_install_remove_multiple" />
</testsuite><testsuite name="SoftwareManagement.sm_mapper_fail_and_reconnect" tests="2" errors="0" failures="0" skipped="2" time="0"><testcase classname="MapperC8yReceiveLastMessageOnRestart" name="SoftwareManagement.sm_mapper_fail_and_reconnect">
		<skipped message="SKIPPED: instable https://github.com/thin-edge/thin-edge.io/issues/752" />
		<system-out>17:42:05 INFO  ==============================================================
17:42:05 INFO  Id:    SoftwareManagement.sm_mapper_fail_and_reconnect
17:42:05 INFO  Dir:   software_management_end_to_end/
17:42:05 INFO  Title: Validate the tedge-mapper-sm-c8y for receiving the last message on restart
17:42:05 INFO  ==============================================================
17:42:05 INFO  instable https://github.com/thin-edge/thin-edge.io/issues/752 ... skipped
17:42:05 INFO  
17:42:05 INFO  Test duration: 0.02 secs
17:42:05 INFO  Test final outcome:  SKIPPED
17:42:05 INFO  Test outcome reason: instable https://github.com/thin-edge/thin-edge.io/issues/752
17:42:05 INFO  
</system-out>
	</testcase>
<testcase classname="MapperC8yReceiveLastMessageOnRestart" name="SoftwareManagement.sm_mapper_fail_and_reconnect">
		<skipped message="SKIPPED: instable https://github.com/thin-edge/thin-edge.io/issues/752" />
		<system-out>18:58:02 INFO  ==============================================================
18:58:02 INFO  Id:    SoftwareManagement.sm_mapper_fail_and_reconnect
18:58:02 INFO  Dir:   software_management_end_to_end/
18:58:02 INFO  Title: Validate the tedge-mapper-sm-c8y for receiving the last message on restart
18:58:02 INFO  ==============================================================
18:58:02 INFO  instable https://github.com/thin-edge/thin-edge.io/issues/752 ... skipped
18:58:02 INFO  
18:58:02 INFO  Test duration: 0.04 secs
18:58:02 INFO  Test final outcome:  SKIPPED
18:58:02 INFO  Test outcome reason: instable https://github.com/thin-edge/thin-edge.io/issues/752
18:58:02 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="SoftwareManagement.sm_mixed_install_remove_multiple" tests="2" errors="0" failures="1" skipped="1" time="0"><testcase classname="PySysTest" name="SoftwareManagement.sm_mixed_install_remove_multiple">
		<skipped message="SKIPPED: Testing the fake plugin is not enabled.Use parameter -Xfakeplugin=fakeplugin to enable it" />
		<system-out>17:42:05 INFO  ==============================================================
17:42:05 INFO  Id:    SoftwareManagement.sm_mixed_install_remove_multiple
17:42:05 INFO  Dir:   software_management_end_to_end/
17:42:05 INFO  Title: Validate end to end behaviour for the dummy-plugin for multiple packages with mixed versions
17:42:05 INFO  ==============================================================
17:42:05 INFO  Testing the fake plugin is not enabled.Use parameter -Xfakeplugin=fakeplugin to enable it ... skipped
17:42:05 WARN  Aborted test due to SKIPPED outcome
17:42:05 INFO  
17:42:05 INFO  Test duration: 0.02 secs
17:42:05 INFO  Test final outcome:  SKIPPED
17:42:05 INFO  Test outcome reason: Testing the fake plugin is not enabled.Use parameter -Xfakeplugin=fakeplugin to enable it
17:42:05 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_mixed_install_remove_multiple">
		<failure message="BLOCKED: SystemError: The operation has failed (+1 other failures)" type="BLOCKED" />
		<system-out>18:58:02 INFO  ==============================================================
18:58:02 INFO  Id:    SoftwareManagement.sm_mixed_install_remove_multiple
18:58:02 INFO  Dir:   software_management_end_to_end/
18:58:02 INFO  Title: Validate end to end behaviour for the dummy-plugin for multiple packages with mixed versions
18:58:02 INFO  ==============================================================
18:58:02 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
18:58:02 INFO  EnvironmentC8y Setup
18:58:03 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
18:58:03 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 4 seconds
18:58:03 INFO  Delaying execution by 7 seconds
18:58:24 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 13 secs
18:58:24 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
18:58:25 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
18:58:25 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
18:58:27 INFO  State of current operation: SUCCESSFUL
18:58:28 INFO  Package apple is installed
18:58:28 INFO  Assert that (True == value) with value=True ... passed
18:58:28 INFO  Package banana is installed
18:58:28 INFO  Assert that (True == value) with value=True ... passed
18:58:28 INFO  Package cherry is installed
18:58:28 INFO  Assert that (True == value) with value=True ... passed
18:58:28 INFO  Package asciijump is installed
18:58:28 WARN  Assert that (False == value) with value=True ... failed 
18:58:29 INFO  Assert that (False == value) with value=False ... passed
18:58:29 INFO  Response status: 201
18:58:29 INFO  Response to action: {
    "delivery": {
        "time": "2022-04-27T18:58:29.320Z",
        "log": [],
        "status": "PENDING"
    },
    "creationTime": "2022-04-27T18:58:29.306Z",
    "deviceName": "m32sd10b",
    "deviceId": "17821468",
    "self": "https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17832566",
    "id": "17832566",
    "status": "PENDING",
    "description": "Apply software changes, triggered from PySys: [{'action': 'install', 'id': '5495053', 'name': 'apple', 'url': ' ', 'version': '::fruits'}, {'action': 'install', 'id': '5494888', 'name': 'banana', 'url': ' ', 'version': '::fruits'}, {'action': 'install', 'id': '5475369', 'name': 'asciijump', 'url': ' ', 'version': '::apt'}, {'action': 'install', 'id': '5495382', 'name': 'cherry', 'url': ' ', 'version': '::fruits'}, {'action': 'install', 'id': '8018911', 'name': 'registry', 'url': ' ', 'version': '::docker'}]",
    "c8y_SoftwareUpdate": [
        {
            "name": "apple",
            "action": "install",
            "id": "5495053",
            "version": "::fruits",
            "url": " "
        },
        {
            "name": "banana",
            "action": "install",
            "id": "5494888",
            "version": "::fruits",
            "url": " "
        },
        {
            "name": "asciijump",
            "action": "install",
            "id": "5475369",
            "version": "::apt",
            "url": " "
        },
        {
            "name": "cherry",
            "action": "install",
            "id": "5495382",
            "version": "::fruits",
            "url": " "
        },
        {
            "name": "registry",
            "action": "install",
            "id": "8018911",
            "version": "::docker",
            "url": " "
        }
    ]
}
18:58:29 INFO  Started operation: {'delivery': {'time': '2022-04-27T18:58:29.320Z', 'log': [], 'status': 'PENDING'}, 'creationTime': '2022-04-27T18:58:29.306Z', 'deviceName': 'm32sd10b', 'deviceId': '17821468', 'self': 'https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17832566', 'id': '17832566', 'status': 'PENDING', 'description': "Apply software changes, triggered from PySys: [{'action': 'install', 'id': '5495053', 'name': 'apple', 'url': ' ', 'version': '::fruits'}, {'action': 'install', 'id': '5494888', 'name': 'banana', 'url': ' ', 'version': '::fruits'}, {'action': 'install', 'id': '5475369', 'name': 'asciijump', 'url': ' ', 'version': '::apt'}, {'action': 'install', 'id': '5495382', 'name': 'cherry', 'url': ' ', 'version': '::fruits'}, {'action': 'install', 'id': '8018911', 'name': 'registry', 'url': ' ', 'version': '::docker'}]", 'c8y_SoftwareUpdate': [{'name': 'apple', 'action': 'install', 'id': '5495053', 'version': '::fruits', 'url': ' '}, {'name': 'banana', 'action': 'install', 'id': '5494888', 'version': '::fruits', 'url': ' '}, {'name': 'asciijump', 'action': 'install', 'id': '5475369', 'version': '::apt', 'url': ' '}, {'name': 'cherry', 'action': 'install', 'id': '5495382', 'version': '::fruits', 'url': ' '}, {'name': 'registry', 'action': 'install', 'id': '8018911', 'version': '::docker', 'url': ' '}]}
18:58:31 INFO  State of operation 17832566 : PENDING
18:58:33 INFO  State of operation 17832566 : EXECUTING
18:58:36 INFO  State of operation 17832566 : EXECUTING
18:58:38 INFO  State of operation 17832566 : EXECUTING
18:58:40 INFO  State of operation 17832566 : EXECUTING
18:58:42 INFO  State of operation 17832566 : EXECUTING
18:58:45 INFO  State of operation 17832566 : EXECUTING
18:58:47 INFO  State of operation 17832566 : EXECUTING
18:58:50 INFO  State of operation 17832566 : EXECUTING
18:58:52 INFO  State of operation 17832566 : EXECUTING
18:58:54 INFO  State of operation 17832566 : EXECUTING
18:58:57 INFO  State of operation 17832566 : EXECUTING
18:58:59 INFO  State of operation 17832566 : EXECUTING
18:59:01 INFO  State of operation 17832566 : EXECUTING
18:59:03 INFO  State of operation 17832566 : EXECUTING
18:59:06 INFO  State of operation 17832566 : EXECUTING
18:59:08 INFO  State of operation 17832566 : EXECUTING
18:59:10 INFO  State of operation 17832566 : FAILED
18:59:10 ERROR Stopping as the operation has failed
18:59:10 WARN  SystemError occurred while running test - The operation has failed
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1294, in __call__
    self.testObj.execute()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_mixed_install_remove_multiple/run.py", line 95, in execute
    self.wait_until_succcess()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 324, in wait_until_succcess
    self.wait_until_status("SUCCESSFUL")
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 361, in wait_until_status
    raise SystemError("The operation has failed")
SystemError: The operation has failed
18:59:10 WARN  SystemError: The operation has failed ... blocked 
18:59:10 INFO  
18:59:10 INFO  cleanup:
18:59:14 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
18:59:15 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
18:59:15 INFO  
18:59:15 INFO  Test duration: 72.45 secs
18:59:15 INFO  Test final outcome:  BLOCKED
18:59:15 INFO  Test outcome reason: SystemError: The operation has failed (+1 other failures)
18:59:15 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="agent_init_session" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="AgentInitSession" name="agent_init_session" />
</testsuite><testsuite name="apt_fail_noarg" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="AptPluginFailNoArg" name="apt_fail_noarg">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'" />
		<system-out>17:30:51 INFO  ==============================================================
17:30:51 INFO  Id:    apt_fail_noarg
17:30:51 INFO  Dir:   plugin_apt/
17:30:51 INFO  Title: Validate apt plugin fetures(prepare, list, install, remove finalize) without arguments
17:30:51 INFO  ==============================================================
17:30:51 INFO  Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container' ... skipped
17:30:51 WARN  Aborted test due to SKIPPED outcome
17:30:51 INFO  
17:30:51 INFO  Test duration: 0.04 secs
17:30:51 INFO  Test final outcome:  SKIPPED
17:30:51 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'
17:30:51 INFO  
</system-out>
	</testcase>
<testcase classname="AptPluginFailNoArg" name="apt_fail_noarg" />
</testsuite><testsuite name="apt_finalize" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="AptPluginFinalize" name="apt_finalize">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'" />
		<system-out>17:30:51 INFO  ==============================================================
17:30:51 INFO  Id:    apt_finalize
17:30:51 INFO  Dir:   plugin_apt/
17:30:51 INFO  Title: Validate apt plugin finalize - dense version
17:30:51 INFO  ==============================================================
17:30:51 INFO  Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container' ... skipped
17:30:51 WARN  Aborted test due to SKIPPED outcome
17:30:51 INFO  
17:30:51 INFO  Test duration: 0.02 secs
17:30:51 INFO  Test final outcome:  SKIPPED
17:30:51 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'
17:30:51 INFO  
</system-out>
	</testcase>
<testcase classname="AptPluginFinalize" name="apt_finalize" />
</testsuite><testsuite name="apt_install" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="AptPluginInstallDense" name="apt_install">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'" />
		<system-out>17:30:51 INFO  ==============================================================
17:30:51 INFO  Id:    apt_install
17:30:51 INFO  Dir:   plugin_apt/
17:30:51 INFO  Title: Validate apt plugin prepare - dense version
17:30:51 INFO  ==============================================================
17:30:51 INFO  Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container' ... skipped
17:30:51 WARN  Aborted test due to SKIPPED outcome
17:30:51 INFO  
17:30:51 INFO  Test duration: 0.02 secs
17:30:51 INFO  Test final outcome:  SKIPPED
17:30:51 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'
17:30:51 INFO  
</system-out>
	</testcase>
<testcase classname="AptPluginInstallDense" name="apt_install" />
</testsuite><testsuite name="apt_install_fail" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="AptPluginInstallFail" name="apt_install_fail">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'" />
		<system-out>17:30:51 INFO  ==============================================================
17:30:51 INFO  Id:    apt_install_fail
17:30:51 INFO  Dir:   plugin_apt/
17:30:51 INFO  Title: Validate apt plugin prepare - failing
17:30:51 INFO  ==============================================================
17:30:51 INFO  Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container' ... skipped
17:30:51 WARN  Aborted test due to SKIPPED outcome
17:30:51 INFO  
17:30:51 INFO  Test duration: 0.02 secs
17:30:51 INFO  Test final outcome:  SKIPPED
17:30:51 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'
17:30:51 INFO  
</system-out>
	</testcase>
<testcase classname="AptPluginInstallFail" name="apt_install_fail" />
</testsuite><testsuite name="apt_install_local_file" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="AptPluginInstallFromLocalFile" name="apt_install_local_file">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'" />
		<system-out>17:30:51 INFO  ==============================================================
17:30:51 INFO  Id:    apt_install_local_file
17:30:51 INFO  Dir:   plugin_apt/
17:30:51 INFO  Title: Validate apt plugin install from local file - SUCCESS case
17:30:51 INFO  ==============================================================
17:30:51 INFO  Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container' ... skipped
17:30:51 WARN  Aborted test due to SKIPPED outcome
17:30:51 INFO  
17:30:51 INFO  Test duration: 0.02 secs
17:30:51 INFO  Test final outcome:  SKIPPED
17:30:51 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'
17:30:51 INFO  
</system-out>
	</testcase>
<testcase classname="AptPluginInstallFromLocalFile" name="apt_install_local_file" />
</testsuite><testsuite name="apt_install_local_file_fail" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="AptPluginInstallFromLocalFileFail" name="apt_install_local_file_fail">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'" />
		<system-out>17:30:51 INFO  ==============================================================
17:30:51 INFO  Id:    apt_install_local_file_fail
17:30:51 INFO  Dir:   plugin_apt/
17:30:51 INFO  Title: Validate apt plugin install from local file - FAIL case
17:30:51 INFO  ==============================================================
17:30:51 INFO  Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container' ... skipped
17:30:51 WARN  Aborted test due to SKIPPED outcome
17:30:51 INFO  
17:30:51 INFO  Test duration: 0.03 secs
17:30:51 INFO  Test final outcome:  SKIPPED
17:30:51 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'
17:30:51 INFO  
</system-out>
	</testcase>
<testcase classname="AptPluginInstallFromLocalFileFail" name="apt_install_local_file_fail" />
</testsuite><testsuite name="apt_install_local_file_with_version" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="AptPluginInstallFromLocalFileWithVersion" name="apt_install_local_file_with_version">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'" />
		<system-out>17:30:51 INFO  ==============================================================
17:30:51 INFO  Id:    apt_install_local_file_with_version
17:30:51 INFO  Dir:   plugin_apt/
17:30:51 INFO  Title: Validate apt plugin install from local file AND with a version - SUCCESS case
17:30:51 INFO  ==============================================================
17:30:51 INFO  Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container' ... skipped
17:30:51 WARN  Aborted test due to SKIPPED outcome
17:30:51 INFO  
17:30:51 INFO  Test duration: 0.02 secs
17:30:51 INFO  Test final outcome:  SKIPPED
17:30:51 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'
17:30:51 INFO  
</system-out>
	</testcase>
<testcase classname="AptPluginInstallFromLocalFileWithVersion" name="apt_install_local_file_with_version" />
</testsuite><testsuite name="apt_install_local_file_with_version_fail" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="AptPluginInstallFromLocalFileWithVersionFail" name="apt_install_local_file_with_version_fail">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'" />
		<system-out>17:30:51 INFO  ==============================================================
17:30:51 INFO  Id:    apt_install_local_file_with_version_fail
17:30:51 INFO  Dir:   plugin_apt/
17:30:51 INFO  Title: Validate apt plugin install from local file AND with a version - FAIL case
17:30:51 INFO  ==============================================================
17:30:51 INFO  Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container' ... skipped
17:30:51 WARN  Aborted test due to SKIPPED outcome
17:30:51 INFO  
17:30:51 INFO  Test duration: 0.02 secs
17:30:51 INFO  Test final outcome:  SKIPPED
17:30:51 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'
17:30:51 INFO  
</system-out>
	</testcase>
<testcase classname="AptPluginInstallFromLocalFileWithVersionFail" name="apt_install_local_file_with_version_fail" />
</testsuite><testsuite name="apt_list_format" tests="2" errors="0" failures="0" skipped="0" time="0"><testcase classname="AptPluginListFormat" name="apt_list_format" />
<testcase classname="AptPluginListFormat" name="apt_list_format" />
</testsuite><testsuite name="apt_prepare" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="AptPluginPrepare" name="apt_prepare">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'" />
		<system-out>17:30:54 INFO  ==============================================================
17:30:54 INFO  Id:    apt_prepare
17:30:54 INFO  Dir:   plugin_apt/
17:30:54 INFO  Title: Validate apt plugin install - dense version
17:30:54 INFO  ==============================================================
17:30:54 INFO  Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container' ... skipped
17:30:54 WARN  Aborted test due to SKIPPED outcome
17:30:54 INFO  
17:30:54 INFO  Test duration: 0.02 secs
17:30:54 INFO  Test final outcome:  SKIPPED
17:30:54 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'
17:30:54 INFO  
</system-out>
	</testcase>
<testcase classname="AptPluginPrepare" name="apt_prepare" />
</testsuite><testsuite name="apt_prepare_install_finalize" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="AptPluginPrepareInstallFinalize" name="apt_prepare_install_finalize">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'" />
		<system-out>17:30:55 INFO  ==============================================================
17:30:55 INFO  Id:    apt_prepare_install_finalize
17:30:55 INFO  Dir:   plugin_apt/
17:30:55 INFO  Title: Validate apt plugin install use case
17:30:55 INFO  ==============================================================
17:30:55 INFO  Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container' ... skipped
17:30:55 WARN  Aborted test due to SKIPPED outcome
17:30:55 INFO  
17:30:55 INFO  Test duration: 0.02 secs
17:30:55 INFO  Test final outcome:  SKIPPED
17:30:55 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'
17:30:55 INFO  
</system-out>
	</testcase>
<testcase classname="AptPluginPrepareInstallFinalize" name="apt_prepare_install_finalize" />
</testsuite><testsuite name="apt_remove" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="AptPluginRemoveDense" name="apt_remove">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'" />
		<system-out>17:30:55 INFO  ==============================================================
17:30:55 INFO  Id:    apt_remove
17:30:55 INFO  Dir:   plugin_apt/
17:30:55 INFO  Title: Validate apt plugin prepare - dense version
17:30:55 INFO  ==============================================================
17:30:55 INFO  Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container' ... skipped
17:30:55 WARN  Aborted test due to SKIPPED outcome
17:30:55 INFO  
17:30:55 INFO  Test duration: 0.02 secs
17:30:55 INFO  Test final outcome:  SKIPPED
17:30:55 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'
17:30:55 INFO  
</system-out>
	</testcase>
<testcase classname="AptPluginRemoveDense" name="apt_remove" />
</testsuite><testsuite name="apt_remove_fail" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="AptPluginRemoveFails" name="apt_remove_fail">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'" />
		<system-out>17:30:55 INFO  ==============================================================
17:30:55 INFO  Id:    apt_remove_fail
17:30:55 INFO  Dir:   plugin_apt/
17:30:55 INFO  Title: Validate apt plugin prepare - failing
17:30:55 INFO  ==============================================================
17:30:55 INFO  Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container' ... skipped
17:30:55 WARN  Aborted test due to SKIPPED outcome
17:30:55 INFO  
17:30:55 INFO  Test duration: 0.02 secs
17:30:55 INFO  Test final outcome:  SKIPPED
17:30:55 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'
17:30:55 INFO  
</system-out>
	</testcase>
<testcase classname="AptPluginRemoveFails" name="apt_remove_fail" />
</testsuite><testsuite name="apt_sequence_install_with_version" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="AptPluginPrepInstallWithVersionFinalize" name="apt_sequence_install_with_version">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'" />
		<system-out>17:30:55 INFO  ==============================================================
17:30:55 INFO  Id:    apt_sequence_install_with_version
17:30:55 INFO  Dir:   plugin_apt/
17:30:55 INFO  Title: Validate apt plugin install with version use case
17:30:55 INFO  ==============================================================
17:30:55 INFO  Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container' ... skipped
17:30:55 WARN  Aborted test due to SKIPPED outcome
17:30:55 INFO  
17:30:55 INFO  Test duration: 0.02 secs
17:30:55 INFO  Test final outcome:  SKIPPED
17:30:55 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'
17:30:55 INFO  
</system-out>
	</testcase>
<testcase classname="AptPluginPrepInstallWithVersionFinalize" name="apt_sequence_install_with_version" />
</testsuite><testsuite name="apt_sequence_install_with_version_fail" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="AptPluginInstallWithVersionFails" name="apt_sequence_install_with_version_fail">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'" />
		<system-out>17:30:55 INFO  ==============================================================
17:30:55 INFO  Id:    apt_sequence_install_with_version_fail
17:30:55 INFO  Dir:   plugin_apt/
17:30:55 INFO  Title: Validate apt plugin install with version fails use case
17:30:55 INFO  ==============================================================
17:30:55 INFO  Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container' ... skipped
17:30:55 WARN  Aborted test due to SKIPPED outcome
17:30:55 INFO  
17:30:55 INFO  Test duration: 0.02 secs
17:30:55 INFO  Test final outcome:  SKIPPED
17:30:55 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'
17:30:55 INFO  
</system-out>
	</testcase>
<testcase classname="AptPluginInstallWithVersionFails" name="apt_sequence_install_with_version_fail" />
</testsuite><testsuite name="apt_sequence_remove" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="AptPluginInstallPrepareRemoveFinalize" name="apt_sequence_remove">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'" />
		<system-out>17:30:55 INFO  ==============================================================
17:30:55 INFO  Id:    apt_sequence_remove
17:30:55 INFO  Dir:   plugin_apt/
17:30:55 INFO  Title: Validate apt plugin prepare install remove finalize use case
17:30:55 INFO  ==============================================================
17:30:55 INFO  Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container' ... skipped
17:30:55 WARN  Aborted test due to SKIPPED outcome
17:30:55 INFO  
17:30:55 INFO  Test duration: 0.02 secs
17:30:55 INFO  Test final outcome:  SKIPPED
17:30:55 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'
17:30:55 INFO  
</system-out>
	</testcase>
<testcase classname="AptPluginInstallPrepareRemoveFinalize" name="apt_sequence_remove" />
</testsuite><testsuite name="apt_sequence_remove_with_version" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="AptPluginRemoveWithVersion" name="apt_sequence_remove_with_version">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'" />
		<system-out>17:30:55 INFO  ==============================================================
17:30:55 INFO  Id:    apt_sequence_remove_with_version
17:30:55 INFO  Dir:   plugin_apt/
17:30:55 INFO  Title: Validate apt plugin remove with version use case
17:30:55 INFO  ==============================================================
17:30:55 INFO  Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container' ... skipped
17:30:55 WARN  Aborted test due to SKIPPED outcome
17:30:55 INFO  
17:30:55 INFO  Test duration: 0.02 secs
17:30:55 INFO  Test final outcome:  SKIPPED
17:30:55 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'
17:30:55 INFO  
</system-out>
	</testcase>
<testcase classname="AptPluginRemoveWithVersion" name="apt_sequence_remove_with_version" />
</testsuite><testsuite name="apt_sequence_remove_with_version_fail" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="AptPluginRemoveWithVersionFails" name="apt_sequence_remove_with_version_fail">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'" />
		<system-out>17:30:55 INFO  ==============================================================
17:30:55 INFO  Id:    apt_sequence_remove_with_version_fail
17:30:55 INFO  Dir:   plugin_apt/
17:30:55 INFO  Title: Validate apt plugin remove with version fails when the version not found
17:30:55 INFO  ==============================================================
17:30:55 INFO  Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container' ... skipped
17:30:55 WARN  Aborted test due to SKIPPED outcome
17:30:55 INFO  
17:30:55 INFO  Test duration: 0.02 secs
17:30:55 INFO  Test final outcome:  SKIPPED
17:30:55 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'
17:30:55 INFO  
</system-out>
	</testcase>
<testcase classname="AptPluginRemoveWithVersionFails" name="apt_sequence_remove_with_version_fail" />
</testsuite><testsuite name="apt_update_list" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="AptPluginUpdateList" name="apt_update_list">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'" />
		<system-out>17:30:55 INFO  ==============================================================
17:30:55 INFO  Id:    apt_update_list
17:30:55 INFO  Dir:   plugin_apt/
17:30:55 INFO  Title: Validate apt plugin update-list command use case
17:30:55 INFO  ==============================================================
17:30:55 INFO  Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container' ... skipped
17:30:55 WARN  Aborted test due to SKIPPED outcome
17:30:55 INFO  
17:30:55 INFO  Test duration: 0.02 secs
17:30:55 INFO  Test final outcome:  SKIPPED
17:30:55 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'
17:30:55 INFO  
</system-out>
	</testcase>
<testcase classname="AptPluginUpdateList" name="apt_update_list" />
</testsuite><testsuite name="apt_wrong_option" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="AptPluginWrongOption" name="apt_wrong_option">
		<skipped message="SKIPPED: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'" />
		<system-out>17:30:55 INFO  ==============================================================
17:30:55 INFO  Id:    apt_wrong_option
17:30:55 INFO  Dir:   plugin_apt/
17:30:55 INFO  Title: Validate apt plugin install
17:30:55 INFO  ==============================================================
17:30:55 INFO  Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container' ... skipped
17:30:55 WARN  Aborted test due to SKIPPED outcome
17:30:55 INFO  
17:30:55 INFO  Test duration: 0.02 secs
17:30:55 INFO  Test final outcome:  SKIPPED
17:30:55 INFO  Test outcome reason: Testing the apt plugin is not supported on this platform.To run the tests call PySys with -XmyPlatform='container'
17:30:55 INFO  
</system-out>
	</testcase>
<testcase classname="AptPluginWrongOption" name="apt_wrong_option" />
</testsuite><testsuite name="c8y_jwt_token_retrieval" tests="1" errors="0" failures="1" skipped="0" time="0"><testcase classname="ValidateJWTTokenRetrieval" name="c8y_jwt_token_retrieval">
		<failure message="FAILED: Grep on resp_jwt.out contains &quot;\[c8y/s/dat\] 71,&quot;" type="FAILED" />
		<system-out>17:27:10 INFO  ==============================================================
17:27:10 INFO  Id:    c8y_jwt_token_retrieval
17:27:10 INFO  Dir:   cloud_c8y/
17:27:10 INFO  Title: Validate the Cumulocity JWT Token Retrieval feature
17:27:10 INFO  ==============================================================
17:27:10 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
17:27:25 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
17:27:25 INFO  Started sudo&lt;resp_jwt&gt; with process id 18988
17:27:26 INFO  Executed sudo&lt;req_jwt&gt;, exit status 0
17:27:28 INFO  Executed sudo&lt;kill_out&gt;, exit status 0
17:27:28 WARN  Grep on resp_jwt.out contains "\[c8y/s/dat\] 71," ... failed [run.py:60]
17:27:28 INFO  
17:27:28 INFO  cleanup:
17:27:33 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
17:27:33 INFO  
17:27:33 INFO  Test duration: 23.27 secs
17:27:33 INFO  Test final outcome:  FAILED
17:27:33 INFO  Test outcome reason: Grep on resp_jwt.out contains "\[c8y/s/dat\] 71,"
17:27:33 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="c8y_restart_bridge" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="RestartBridge" name="c8y_restart_bridge" />
</testsuite><testsuite name="call_tedge_-V" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="PySysTest" name="call_tedge_-V" />
</testsuite><testsuite name="call_tedge_-h" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="PySysTest" name="call_tedge_-h" />
</testsuite><testsuite name="call_tedge_-h_-V" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="PySysTest" name="call_tedge_-h_-V" />
</testsuite><testsuite name="call_tedge_config_help" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="PySysTest" name="call_tedge_config_help" />
</testsuite><testsuite name="call_tedge_config_list" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="PySysTest" name="call_tedge_config_list" />
</testsuite><testsuite name="custom_init_system" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="CustomInitSystem" name="custom_init_system" />
</testsuite><testsuite name="docker_plugin_finalize" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="DockerPluginFinalizeTest" name="docker_plugin_finalize">
		<skipped message="SKIPPED: Testing the docker plugin is not supported on this platform.To run it, all the test with -XmyPlatform='container'" />
		<system-out>17:30:55 INFO  ==============================================================
17:30:55 INFO  Id:    docker_plugin_finalize
17:30:55 INFO  Dir:   plugin_docker/
17:30:55 INFO  Title: Validate docker plugin finalize command
17:30:55 INFO  ==============================================================
17:30:55 INFO  Testing the docker plugin is not supported on this platform.To run it, all the test with -XmyPlatform='container' ... skipped
17:30:55 WARN  Aborted test due to SKIPPED outcome
17:30:55 INFO  
17:30:55 INFO  Test duration: 0.05 secs
17:30:55 INFO  Test final outcome:  SKIPPED
17:30:55 INFO  Test outcome reason: Testing the docker plugin is not supported on this platform.To run it, all the test with -XmyPlatform='container'
17:30:55 INFO  
</system-out>
	</testcase>
<testcase classname="DockerPluginFinalizeTest" name="docker_plugin_finalize" />
</testsuite><testsuite name="docker_plugin_install" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="DockerPluginInstallTest" name="docker_plugin_install">
		<skipped message="SKIPPED: Testing the docker plugin is not supported on this platform.To run it, all the test with -XmyPlatform='container'" />
		<system-out>17:30:55 INFO  ==============================================================
17:30:55 INFO  Id:    docker_plugin_install
17:30:55 INFO  Dir:   plugin_docker/
17:30:55 INFO  Title: Validate docker plugin install
17:30:55 INFO  ==============================================================
17:30:55 INFO  Testing the docker plugin is not supported on this platform.To run it, all the test with -XmyPlatform='container' ... skipped
17:30:55 WARN  Aborted test due to SKIPPED outcome
17:30:55 INFO  
17:30:55 INFO  Test duration: 0.02 secs
17:30:55 INFO  Test final outcome:  SKIPPED
17:30:55 INFO  Test outcome reason: Testing the docker plugin is not supported on this platform.To run it, all the test with -XmyPlatform='container'
17:30:55 INFO  
</system-out>
	</testcase>
<testcase classname="DockerPluginInstallTest" name="docker_plugin_install" />
</testsuite><testsuite name="docker_plugin_install_with_version" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="DockerPluginInstallWithVersionTest" name="docker_plugin_install_with_version">
		<skipped message="SKIPPED: Testing the docker plugin is not supported on this platform.To run it, all the test with -XmyPlatform='container'" />
		<system-out>17:30:55 INFO  ==============================================================
17:30:55 INFO  Id:    docker_plugin_install_with_version
17:30:55 INFO  Dir:   plugin_docker/
17:30:55 INFO  Title: Validate docker plugin install
17:30:55 INFO  ==============================================================
17:30:55 INFO  Testing the docker plugin is not supported on this platform.To run it, all the test with -XmyPlatform='container' ... skipped
17:30:55 WARN  Aborted test due to SKIPPED outcome
17:30:55 INFO  
17:30:55 INFO  Test duration: 0.02 secs
17:30:55 INFO  Test final outcome:  SKIPPED
17:30:55 INFO  Test outcome reason: Testing the docker plugin is not supported on this platform.To run it, all the test with -XmyPlatform='container'
17:30:55 INFO  
</system-out>
	</testcase>
<testcase classname="DockerPluginInstallWithVersionTest" name="docker_plugin_install_with_version" />
</testsuite><testsuite name="docker_plugin_remove" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="DockerPluginRemoveTest" name="docker_plugin_remove">
		<skipped message="SKIPPED: Testing the docker plugin is not supported on this platform.To run it, all the test with -XmyPlatform='container'" />
		<system-out>17:30:55 INFO  ==============================================================
17:30:55 INFO  Id:    docker_plugin_remove
17:30:55 INFO  Dir:   plugin_docker/
17:30:55 INFO  Title: Validate docker plugin remove
17:30:55 INFO  ==============================================================
17:30:55 INFO  Testing the docker plugin is not supported on this platform.To run it, all the test with -XmyPlatform='container' ... skipped
17:30:55 WARN  Aborted test due to SKIPPED outcome
17:30:55 INFO  
17:30:55 INFO  Test duration: 0.02 secs
17:30:55 INFO  Test final outcome:  SKIPPED
17:30:55 INFO  Test outcome reason: Testing the docker plugin is not supported on this platform.To run it, all the test with -XmyPlatform='container'
17:30:55 INFO  
</system-out>
	</testcase>
<testcase classname="DockerPluginRemoveTest" name="docker_plugin_remove" />
</testsuite><testsuite name="docker_plugin_remove_with_version" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="DockerPluginRemoveWithVersionTest" name="docker_plugin_remove_with_version">
		<skipped message="SKIPPED: Testing the docker plugin is not supported on this platform.To run it, all the test with -XmyPlatform='container'" />
		<system-out>17:30:56 INFO  ==============================================================
17:30:56 INFO  Id:    docker_plugin_remove_with_version
17:30:56 INFO  Dir:   plugin_docker/
17:30:56 INFO  Title: Validate docker plugin remove with version
17:30:56 INFO  ==============================================================
17:30:56 INFO  Testing the docker plugin is not supported on this platform.To run it, all the test with -XmyPlatform='container' ... skipped
17:30:56 WARN  Aborted test due to SKIPPED outcome
17:30:56 INFO  
17:30:56 INFO  Test duration: 0.04 secs
17:30:56 INFO  Test final outcome:  SKIPPED
17:30:56 INFO  Test outcome reason: Testing the docker plugin is not supported on this platform.To run it, all the test with -XmyPlatform='container'
17:30:56 INFO  
</system-out>
	</testcase>
<testcase classname="DockerPluginRemoveWithVersionTest" name="docker_plugin_remove_with_version" />
</testsuite><testsuite name="docker_plugin_update" tests="2" errors="0" failures="0" skipped="1" time="0"><testcase classname="DockerPluginUpdateTest" name="docker_plugin_update">
		<skipped message="SKIPPED: Testing the docker plugin is not supported on this platform.To run it, all the test with -XmyPlatform='container'" />
		<system-out>17:30:56 INFO  ==============================================================
17:30:56 INFO  Id:    docker_plugin_update
17:30:56 INFO  Dir:   plugin_docker/
17:30:56 INFO  Title: Validate docker plugin install updates existing containers
17:30:56 INFO  ==============================================================
17:30:56 INFO  Testing the docker plugin is not supported on this platform.To run it, all the test with -XmyPlatform='container' ... skipped
17:30:56 WARN  Aborted test due to SKIPPED outcome
17:30:56 INFO  
17:30:56 INFO  Test duration: 0.02 secs
17:30:56 INFO  Test final outcome:  SKIPPED
17:30:56 INFO  Test outcome reason: Testing the docker plugin is not supported on this platform.To run it, all the test with -XmyPlatform='container'
17:30:56 INFO  
</system-out>
	</testcase>
<testcase classname="DockerPluginUpdateTest" name="docker_plugin_update" />
</testsuite><testsuite name="invalid_device_id" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="InvalidDeviceId" name="invalid_device_id" />
</testsuite><testsuite name="local_mqtt_pub_fail_noqos" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="PySysTest" name="local_mqtt_pub_fail_noqos" />
</testsuite><testsuite name="local_mqtt_pub_fail_qos0" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="PySysTest" name="local_mqtt_pub_fail_qos0" />
</testsuite><testsuite name="local_mqtt_pub_fail_qos1" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="PySysTest" name="local_mqtt_pub_fail_qos1" />
</testsuite><testsuite name="local_mqtt_pub_fail_qos2" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="PySysTest" name="local_mqtt_pub_fail_qos2" />
</testsuite><testsuite name="local_mqtt_pub_sub" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="PySysTest" name="local_mqtt_pub_sub" />
</testsuite><testsuite name="local_mqtt_pub_sub_retain" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="MqttPublishWithRetain" name="local_mqtt_pub_sub_retain" />
</testsuite><testsuite name="local_mqtt_pub_sub_with_sudo" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="PySysTest" name="local_mqtt_pub_sub_with_sudo" />
</testsuite><testsuite name="local_mqtt_sub_fail" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="PySysTest" name="local_mqtt_sub_fail" />
</testsuite><testsuite name="log_request_error_messages" tests="1" errors="0" failures="1" skipped="0" time="0"><testcase classname="LogRequestVerifySearchTextError" name="log_request_error_messages">
		<failure message="FAILED: Assert that (True == value) with value=False" type="FAILED" />
		<system-out>17:27:52 INFO  ==============================================================
17:27:52 INFO  Id:    log_request_error_messages
17:27:52 INFO  Dir:   log_request_end_to_end/
17:27:52 INFO  Title: Validate end to end behaviour for the log request operation check for error messages
17:27:52 INFO  ==============================================================
17:27:54 INFO  EnvironmentC8y Setup
17:27:54 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
17:27:54 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 2 seconds
17:27:54 INFO  Delaying execution by 9 seconds
17:28:17 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
17:28:18 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
17:28:18 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
17:28:19 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
17:28:20 INFO  Executed sudo&lt;rm_logs&gt;, exit status 0
17:28:20 INFO  Executed sudo&lt;move_logs&gt;, exit status 0
17:28:21 INFO  log response None
17:28:21 WARN  retry, retrying in 1 seconds...
17:28:22 INFO  log response https://thin-edge-io.eu-latest.cumulocity.com/event/events/17820342/binaries
17:28:23 WARN  Assert that (True == value) with value=False ... failed [run.py:43]
17:28:23 INFO  
17:28:23 INFO  cleanup:
17:28:23 INFO  Executed sudo&lt;rm_logs&gt;, exit status 0
17:28:24 INFO  Executed sudo&lt;rm_tmp_logs&gt;, exit status 0
17:28:24 INFO  Executed sudo&lt;send_failed&gt;, exit status 0
17:28:28 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
17:28:29 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
17:28:29 INFO  
17:28:29 INFO  Test duration: 36.51 secs
17:28:29 INFO  Test final outcome:  FAILED
17:28:29 INFO  Test outcome reason: Assert that (True == value) with value=False
17:28:29 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="log_request_num_lines" tests="1" errors="0" failures="1" skipped="0" time="0"><testcase classname="LogRequestVerifyNumberOfLines" name="log_request_num_lines">
		<failure message="FAILED: Assert that (True == value) with value=False" type="FAILED" />
		<system-out>17:28:29 INFO  ==============================================================
17:28:29 INFO  Id:    log_request_num_lines
17:28:29 INFO  Dir:   log_request_end_to_end/
17:28:29 INFO  Title: Validate end to end behaviour for the log request operation check for number of lines
17:28:29 INFO  ==============================================================
17:28:29 INFO  EnvironmentC8y Setup
17:28:30 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
17:28:30 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 4 seconds
17:28:30 INFO  Delaying execution by 7 seconds
17:28:51 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
17:28:52 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
17:28:52 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
17:28:53 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
17:28:53 INFO  Executed sudo&lt;rm_logs&gt;, exit status 0
17:28:54 INFO  Executed sudo&lt;move_logs&gt;, exit status 0
17:28:54 INFO  log response None
17:28:54 WARN  retry, retrying in 1 seconds...
17:28:56 INFO  log response https://thin-edge-io.eu-latest.cumulocity.com/event/events/17821631/binaries
17:28:56 INFO  nlines 0
17:28:56 WARN  Assert that (True == value) with value=False ... failed [run.py:44]
17:28:56 INFO  
17:28:56 INFO  cleanup:
17:28:56 INFO  Executed sudo&lt;rm_logs&gt;, exit status 0
17:28:57 INFO  Executed sudo&lt;rm_tmp_logs&gt;, exit status 0
17:28:57 INFO  Executed sudo&lt;send_failed&gt;, exit status 0
17:29:02 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
17:29:02 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
17:29:02 INFO  
17:29:02 INFO  Test duration: 33.30 secs
17:29:02 INFO  Test final outcome:  FAILED
17:29:02 INFO  Test outcome reason: Assert that (True == value) with value=False
17:29:02 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="mapper_awaits_before_reconnect" tests="1" errors="0" failures="1" skipped="0" time="0"><testcase classname="MapperReconnectAwait" name="mapper_awaits_before_reconnect">
		<failure message="FAILED: Line count on tedge_mapper_journal.out for &quot;::mapper: MQTT connection error:&quot; expected &gt;=2 but got 0" type="FAILED" />
		<system-out>17:45:08 INFO  ==============================================================
17:45:08 INFO  Id:    mapper_awaits_before_reconnect
17:45:08 INFO  Dir:   tedge_mapper_c8y/
17:45:08 INFO  Title: Validate mapper doesn't reconnect too often
17:45:08 INFO  ==============================================================
17:45:08 INFO  Started mosquitto_sub with process id 24965
17:45:08 INFO  Waiting for 0.1 seconds
17:45:09 INFO  Executed sudo&lt;tedge_mapper&gt;, exit status 0
17:45:09 INFO  Waiting for 5.0 seconds
17:45:14 INFO  Executed sudo&lt;tedge_mapper&gt;, exit status 0
17:45:15 INFO  Executed sudo&lt;tedge_mapper_journal&gt;, exit status 0
17:45:15 WARN  Grep on tedge_mapper_journal.out contains "ERROR" ... failed [run.py:67]
17:45:15 INFO  Line count on file tedge_mapper_journal.out ... passed
17:45:15 WARN  Line count on tedge_mapper_journal.out for "::mapper: MQTT connection error:" expected &gt;=2 but got 0 ... failed [run.py:78]
17:45:15 WARN  Aborted test due to FAILED outcome
17:45:15 INFO  
17:45:15 INFO  Test duration: 7.50 secs
17:45:15 INFO  Test final outcome:  FAILED
17:45:15 INFO  Test outcome reason: Line count on tedge_mapper_journal.out for "::mapper: MQTT connection error:" expected &gt;=2 but got 0
17:45:15 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="monitoring_smaller_interval" tests="1" errors="0" failures="1" skipped="0" time="0"><testcase classname="MonitoringSmallInterval" name="monitoring_smaller_interval">
		<failure message="BLOCKED: TypeError: 'int' object is not subscriptable" type="BLOCKED" />
		<system-out>17:30:31 INFO  ==============================================================
17:30:31 INFO  Id:    monitoring_smaller_interval
17:30:31 INFO  Dir:   monitoring/
17:30:31 INFO  Title: Validate the tedge dm agent messages that are produced with smaller sampling interval than the batching window. Here the simulated collectd messages are used
17:30:31 INFO  ==============================================================
17:30:32 INFO  Executed sudo&lt;collectd&gt;, exit status 0
17:30:32 INFO  Executed sudo&lt;collectd_mapper&gt;, exit status 0
17:30:32 INFO  Started sudo&lt;tedge_sub&gt; with process id 19903
17:30:33 INFO  Executed sudo&lt;tedge_temp&gt;, exit status 0
17:30:33 INFO  Executed sudo&lt;tedge_pres&gt;, exit status 0
17:30:34 INFO  Executed sudo&lt;tedge_temp&gt;, exit status 0
17:30:34 INFO  Executed sudo&lt;tedge_pres&gt;, exit status 0
17:30:35 INFO  Executed sudo&lt;tedge_temp&gt;, exit status 0
17:30:36 INFO  Executed sudo&lt;tedge_pres&gt;, exit status 0
17:30:36 INFO  Executed sudo&lt;tedge_temp&gt;, exit status 0
17:30:37 INFO  Executed sudo&lt;tedge_pres&gt;, exit status 0
17:30:37 INFO  Executed sudo&lt;tedge_temp&gt;, exit status 0
17:30:38 INFO  Executed sudo&lt;tedge_pres&gt;, exit status 0
17:30:39 INFO  Executed sudo&lt;tedge_temp&gt;, exit status 0
17:30:39 INFO  Executed sudo&lt;tedge_pres&gt;, exit status 0
17:30:40 INFO  Executed sudo&lt;tedge_temp&gt;, exit status 0
17:30:40 INFO  Executed sudo&lt;tedge_pres&gt;, exit status 0
17:30:41 INFO  Executed sudo&lt;tedge_temp&gt;, exit status 0
17:30:41 INFO  Executed sudo&lt;tedge_pres&gt;, exit status 0
17:30:42 INFO  Executed sudo&lt;tedge_temp&gt;, exit status 0
17:30:43 INFO  Executed sudo&lt;tedge_pres&gt;, exit status 0
17:30:43 INFO  Executed sudo&lt;tedge_temp&gt;, exit status 0
17:30:44 INFO  Executed sudo&lt;tedge_pres&gt;, exit status 0
17:30:45 INFO  Executed sudo&lt;kill_out&gt;, exit status 0
17:30:45 INFO  0

17:30:45 WARN  TypeError occurred while running test - 'int' object is not subscriptable
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1296, in __call__
    self.testObj.validate()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/monitoring/monitoring_smaller_interval/run.py", line 104, in validate
    collectd_msg_validation_result=self.validate_json(),
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/monitoring/monitoring_smaller_interval/run.py", line 114, in validate_json
    if not self.validate_time():
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/monitoring/monitoring_smaller_interval/run.py", line 134, in validate_time
    if self.js_msg["time"]:
TypeError: 'int' object is not subscriptable
17:30:45 WARN  TypeError: 'int' object is not subscriptable ... blocked 
17:30:45 INFO  
17:30:45 INFO  cleanup:
17:30:45 INFO  monitoring_cleanup
17:30:46 INFO  Executed sudo&lt;collectd_mapper&gt;, exit status 0
17:30:46 INFO  
17:30:46 INFO  Test duration: 15.06 secs
17:30:46 INFO  Test final outcome:  BLOCKED
17:30:46 INFO  Test outcome reason: TypeError: 'int' object is not subscriptable
17:30:46 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="monitoring_with_collectd" tests="1" errors="0" failures="0" skipped="1" time="0"><testcase classname="MonitoringWithCollectd" name="monitoring_with_collectd">
		<skipped message="SKIPPED: Test execution disabled due to #792 (instable)" />
		<system-out>17:30:46 INFO  ==============================================================
17:30:46 INFO  Id:    monitoring_with_collectd
17:30:46 INFO  Dir:   monitoring/
17:30:46 INFO  Title: Validate tedge dm agent messages that are produced by batching the collectd messages
17:30:46 INFO  ==============================================================
17:30:46 INFO  Test execution disabled due to #792 (instable) ... skipped
17:30:46 INFO  
17:30:46 INFO  Test duration: 0.02 secs
17:30:46 INFO  Test final outcome:  SKIPPED
17:30:46 INFO  Test outcome reason: Test execution disabled due to #792 (instable)
17:30:46 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="monitoring_with_simulated_messages" tests="1" errors="0" failures="1" skipped="0" time="0"><testcase classname="MonitoringWithSimulatedMessages" name="monitoring_with_simulated_messages">
		<failure message="BLOCKED: TypeError: 'int' object is not subscriptable" type="BLOCKED" />
		<system-out>17:30:46 INFO  ==============================================================
17:30:46 INFO  Id:    monitoring_with_simulated_messages
17:30:46 INFO  Dir:   monitoring/
17:30:46 INFO  Title: Validate the tedge dm agent messages that are produced from the simulated collectd messages
17:30:46 INFO  ==============================================================
17:30:47 INFO  Executed sudo&lt;collectd&gt;, exit status 0
17:30:47 INFO  Executed sudo&lt;collectd_mapper&gt;, exit status 0
17:30:47 INFO  Started sudo&lt;tedge_sub&gt; with process id 19963
17:30:48 INFO  Executed sudo&lt;tedge_temp&gt;, exit status 0
17:30:48 INFO  Executed sudo&lt;tedge_pres&gt;, exit status 0
17:30:50 INFO  Executed sudo&lt;kill_out&gt;, exit status 0
17:30:50 INFO  0

17:30:50 WARN  TypeError occurred while running test - 'int' object is not subscriptable
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1296, in __call__
    self.testObj.validate()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/monitoring/monitoring_with_simulated_messages/run.py", line 98, in validate
    collectd_msg_validation_result=self.validate_json(),
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/monitoring/monitoring_with_simulated_messages/run.py", line 108, in validate_json
    if not self.validate_time():
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/monitoring/monitoring_with_simulated_messages/run.py", line 127, in validate_time
    if self.js_msg["time"]:
TypeError: 'int' object is not subscriptable
17:30:50 WARN  TypeError: 'int' object is not subscriptable ... blocked 
17:30:50 INFO  
17:30:50 INFO  cleanup:
17:30:50 INFO  monitoring_cleanup
17:30:50 INFO  Executed sudo&lt;collectd_mapper&gt;, exit status 0
17:30:50 INFO  
17:30:50 INFO  Test duration: 4.44 secs
17:30:50 INFO  Test final outcome:  BLOCKED
17:30:50 INFO  Test outcome reason: TypeError: 'int' object is not subscriptable
17:30:50 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="mqtt_port_change_connection_fails" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="MqttPortChangeConnectionFails" name="mqtt_port_change_connection_fails" />
</testsuite><testsuite name="mqtt_port_change_connection_works" tests="1" errors="0" failures="0" skipped="1" time="0"><testcase classname="MqttPortChangeConnectionWorks" name="mqtt_port_change_connection_works">
		<skipped message="SKIPPED: failing intermitently" />
		<system-out>17:29:37 INFO  ==============================================================
17:29:37 INFO  Id:    mqtt_port_change_connection_works
17:29:37 INFO  Dir:   misc_features/
17:29:37 INFO  Title: mqtt port change connection works for all the thin-edge services that use the mosquitto broker
17:29:37 INFO  ==============================================================
17:29:37 INFO  failing intermitently ... skipped
17:29:37 INFO  
17:29:37 INFO  Test duration: 0.02 secs
17:29:37 INFO  Test final outcome:  SKIPPED
17:29:37 INFO  Test outcome reason: failing intermitently
17:29:37 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="mqtt_port_set" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="MqttPortSet" name="mqtt_port_set" />
</testsuite><testsuite name="mqtt_port_unset" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="MqttPortUnSet" name="mqtt_port_unset" />
</testsuite><testsuite name="publish_flux" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="PublishFlux" name="publish_flux" />
</testsuite><testsuite name="publish_sawmill" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="PublishSawmill" name="publish_sawmill" />
</testsuite><testsuite name="runtime_start_two_mappers" tests="1" errors="0" failures="1" skipped="0" time="0"><testcase classname="RuntimeMultiMappers" name="runtime_start_two_mappers">
		<failure message="FAILED: Grep on tedge_mapper2.err contains &quot;Error: Couldn't acquire file lock.&quot;" type="FAILED" />
		<system-out>17:45:15 INFO  ==============================================================
17:45:15 INFO  Id:    runtime_start_two_mappers
17:45:15 INFO  Dir:   tedge_mapper_c8y/
17:45:15 INFO  Title: Validate two mappers can't be started at the same time
17:45:15 INFO  ==============================================================
17:45:16 INFO  Executed sudo&lt;tedge_mapper1&gt;, exit status 0
17:45:16 INFO  Waiting for 0.1 seconds
17:45:17 INFO  Executed sudo&lt;tedge_mapper2&gt;, exit status 1
17:45:17 INFO  Executed sudo&lt;tedge_mapper1&gt;, exit status 0
17:45:17 WARN  Grep on tedge_mapper2.err contains "Error: Couldn't acquire file lock." ... failed [run.py:46]
17:45:17 INFO  
17:45:17 INFO  Test duration: 1.91 secs
17:45:17 INFO  Test final outcome:  FAILED
17:45:17 INFO  Test outcome reason: Grep on tedge_mapper2.err contains "Error: Couldn't acquire file lock."
17:45:17 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="sm_tedge_mapper_init_session" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="TedgeSMMapperInitSession" name="sm_tedge_mapper_init_session" />
</testsuite><testsuite name="smoketest_json" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="SmokeTestJson" name="smoketest_json" />
</testsuite><testsuite name="smoketest_json_400_samples_10ms" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="SmoketestJson400Samples10ms" name="smoketest_json_400_samples_10ms" />
</testsuite><testsuite name="smoketest_json_400_samples_20ms" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="SmoketestJson400Samples20ms" name="smoketest_json_400_samples_20ms" />
</testsuite><testsuite name="smoketest_smartrest" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="SmoketestSmartRest" name="smoketest_smartrest" />
</testsuite><testsuite name="smoketest_smartrest_400_samples_1Xms" tests="1" errors="0" failures="1" skipped="0" time="0"><testcase classname="SmoketestSmartRest400Samples1Xms" name="smoketest_smartrest_400_samples_1Xms">
		<failure message="BLOCKED: python3&lt;stdout&gt; returned non-zero exit code 1" type="BLOCKED" />
		<system-out>17:36:57 INFO  ==============================================================
17:36:57 INFO  Id:    smoketest_smartrest_400_samples_1Xms
17:36:57 INFO  Dir:   smoketests/
17:36:57 INFO  Title: Smoketest Smart Rest 400 Samples 1Xms Delay
17:36:57 INFO  ==============================================================
17:36:57 INFO  EnvironmentC8y Setup
17:36:57 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
17:36:57 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 5 seconds
17:36:57 INFO  Delaying execution by 6 seconds
17:37:17 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
17:37:18 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
17:37:18 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
17:37:19 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
17:39:27 WARN  Executed python3&lt;stdout&gt;, exit status 1, duration 68 secs
17:39:27 INFO  Contents of stdout.out: 
     40    41    42    43    44    45    46    47    48    49    50    51    52    53    54    55    56    57    58    59
     60    61    62    63    64    65    66    67    68    69    70    71    72    73    74    75    76    77    78    79
     80    81    82    83    84    85    86    87    88    89    90    91    92    93    94    95    96    97    98    99
    100   101   102   103   104   105   106   107   108   109   110   111   112   113   114   115   116   117   118   119
    120   121   122   123   124   125   126   127   128   129   130   131   132   133   134   135   136   137   138   139
    140   141   142   143   144   145   146   147   148   149   150   151   152   153   154   155   156   157   158   159
    160   161   162   163   164   165   166   167   168   169   170   171   172   173   174   175   176   177   178   179
    180   181   182   183   184   185   186   187   188   189   190   191   192   193   194   195   196   197   198   199
    200   201   202   203   204   205   206   207   208   209   210   211   212   213   214   215   216   217   218   219
    220   221   222   223   224   225   226   227   228   229   230   231   232   233   234   235   236   237   238   239
    240   241   242   243   244   245   246   247   248   249   250   251   252   253   254   255   256   257   258   259
    260   261   262   263   264   265   266   267   268   269   270   271   272   273   274   275   276   277   278   279
    280   281   282   283   284   285   286   287   288   289   290   291   292   293   294   295   296   297   298   299
    300   301   302   303   304   305   306   307   308   309   310   311   312   313   314   315   316   317   318   319
    320   321   322   323   324   325   326   327   328   329   330   331   332   333   334   335   336   337   338   339
    340   341   342   343   344   345   346   347   348   349   350   351   352   353   354   355   356   357   358   359
    360   361   362   363   364   365   366   367   368   369   370   371   372   373   374   375   376   377   378   379
    380   381   382   383   384   385   386   387   388   389   390   391   392   393   394   395   396   397   398   399
  Expected:  0.0  ...  399.0
  Data verification FAILED
  -----

17:39:27 WARN  python3&lt;stdout&gt; returned non-zero exit code 1 ... blocked 
17:39:27 WARN  Aborted test due to BLOCKED outcome
17:39:27 INFO  
17:39:27 INFO  cleanup:
17:39:31 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
17:39:32 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
17:39:32 INFO  
17:39:32 INFO  Test duration: 155.19 secs
17:39:32 INFO  Test final outcome:  BLOCKED
17:39:32 INFO  Test outcome reason: python3&lt;stdout&gt; returned non-zero exit code 1
17:39:32 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="smoketest_smartrest_400_samples_20ms" tests="1" errors="0" failures="1" skipped="0" time="0"><testcase classname="SmoketestSmartRest400Samples20ms" name="smoketest_smartrest_400_samples_20ms">
		<failure message="BLOCKED: python3&lt;stdout&gt; returned non-zero exit code 1" type="BLOCKED" />
		<system-out>17:39:32 INFO  ==============================================================
17:39:32 INFO  Id:    smoketest_smartrest_400_samples_20ms
17:39:32 INFO  Dir:   smoketests/
17:39:32 INFO  Title: Smoketest SmartRest 400 Samples 20ms Delay
17:39:32 INFO  ==============================================================
17:39:32 INFO  EnvironmentC8y Setup
17:39:32 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
17:39:32 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 5 seconds
17:39:32 INFO  Delaying execution by 6 seconds
17:39:52 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 13 secs
17:39:53 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
17:39:53 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
17:39:54 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
17:41:59 WARN  Executed python3&lt;stdout&gt;, exit status 1, duration 70 secs
17:41:59 INFO  Contents of stdout.out: 
  Retrieved values:
     74    75    76    77    78    79
     80    81    82    83    84    85    86    87    88    89    90    91    92    93    94    95    96    97    98    99
    100   101   102   103   104   105   106   107   108   109   110   111   112   113   114   115   116   117   118   119
    120   121   122   123   124   125   126   127   128   129   130   131   132   133   134   135   136   137   138   139
    140   141   142   143   144   145   146   147   148   149   150   151   152   153   154   155   156   157   158   159
    160   161   162   163   164   165   166   167   168   169   170   171   172   173   174   175   176   177   178   179
    180   181   182   183   184   185   186   187   188   189   190   191   192   193   194   195   196   197   198   199
    200   201   202   203   204   205   206   207   208   209   210   211   212   213   214   215   216   217   218   219
    220   221   222   223   224   225   226   227   228   229   230   231   232   233   234   235   236   237   238   239
    240   241   242   243   244   245   246   247   248   249   250   251   252   253   254   255   256   257   258   259
    260   261   262   263   264   265   266   267   268   269   270   271   272   273   274   275   276   277   278   279
    280   281   282   283   284   285   286   287   288   289   290   291   292   293   294   295   296   297   298   299
    300   301   302   303   304   305   306   307   308   309   310   311   312   313   314   315   316   317   318   319
    320   321   322   323   324   325   326   327   328   329   330   331   332   333   334   335   336   337   338   339
    340   341   342   343   344   345   346   347   348   349   350   351   352   353   354   355   356   357   358   359
    360   361   362   363   364   365   366   367   368   369   370   371   372   373   374   375   376   377   378   379
    380   381   382   383   384   385   386   387   388   389   390   391   392   393   394   395   396   397   398   399
  Expected:  0.0  ...  399.0
  Data verification FAILED
  -----

17:42:00 WARN  python3&lt;stdout&gt; returned non-zero exit code 1 ... blocked 
17:42:00 WARN  Aborted test due to BLOCKED outcome
17:42:00 INFO  
17:42:00 INFO  cleanup:
17:42:04 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
17:42:04 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
17:42:04 INFO  
17:42:04 INFO  Test duration: 152.49 secs
17:42:04 INFO  Test final outcome:  BLOCKED
17:42:04 INFO  Test outcome reason: python3&lt;stdout&gt; returned non-zero exit code 1
17:42:04 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="tedge_agent_user_sudo_access" tests="1" errors="0" failures="0" skipped="1" time="0"><testcase classname="TedgeAgentUserSudoAccess" name="tedge_agent_user_sudo_access">
		<skipped message="SKIPPED: #955 Observation: Exit code of the apt plugin when called with no arguments" />
		<system-out>17:42:31 INFO  ==============================================================
17:42:31 INFO  Id:    tedge_agent_user_sudo_access
17:42:31 INFO  Dir:   tedge/
17:42:31 INFO  Title: Validate tedge-agent user has a limited sudo right
17:42:31 INFO  ==============================================================
17:42:31 INFO  #955 Observation: Exit code of the apt plugin when called with no arguments ... skipped
17:42:31 INFO  
17:42:31 INFO  Test duration: 0.02 secs
17:42:31 INFO  Test final outcome:  SKIPPED
17:42:31 INFO  Test outcome reason: #955 Observation: Exit code of the apt plugin when called with no arguments
17:42:31 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="tedge_connect_test_negative" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="TedgeConnectTestNegative" name="tedge_connect_test_negative" />
</testsuite><testsuite name="tedge_connect_test_positive" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="TedgeConnectTestPositive" name="tedge_connect_test_positive" />
</testsuite><testsuite name="tedge_connect_test_sm_services" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="TedgeConnectTestSMServices" name="tedge_connect_test_sm_services" />
</testsuite><testsuite name="tedge_disconnect_test_sm_services" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="TedgeDisConnectTestSMServices" name="tedge_disconnect_test_sm_services" />
</testsuite><testsuite name="tedge_mapper_az_negative" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="TedgeMapperAzError" name="tedge_mapper_az_negative" />
</testsuite><testsuite name="tedge_mapper_az_with_timestamp" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="TedgeMapperAzWithTimestamp" name="tedge_mapper_az_with_timestamp" />
</testsuite><testsuite name="tedge_mapper_az_without_timestamp" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="TedgeMapperAzWithoutTimestamp" name="tedge_mapper_az_without_timestamp" />
</testsuite><testsuite name="tedge_mapper_c8y_alarms" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="TedgeMapperC8yAlarm" name="tedge_mapper_c8y_alarms" />
</testsuite><testsuite name="tedge_mapper_c8y_child_device_measurement" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="TedgeMapperC8yChildDevice" name="tedge_mapper_c8y_child_device_measurement" />
</testsuite><testsuite name="tedge_mapper_c8y_packet_threshold_size" tests="1" errors="0" failures="1" skipped="0" time="0"><testcase classname="TedgeMapperC8yThresholdPacketSize" name="tedge_mapper_c8y_packet_threshold_size">
		<failure message="FAILED: Grep on tedge_sub.out contains &quot;The size of the message received on tedge/measurements is 20489 which is greater than the threshold size of 16184.&quot;" type="FAILED" />
		<system-out>17:46:52 INFO  ==============================================================
17:46:52 INFO  Id:    tedge_mapper_c8y_packet_threshold_size
17:46:52 INFO  Dir:   tedge_mapper_c8y/
17:46:52 INFO  Title: Validate the Cumulocity Mapper accepted threshold packet size when it receives a message on tedge/measurements
17:46:52 INFO  ==============================================================
17:46:53 INFO  Executed sudo&lt;tedge_mapper_c8y&gt;, exit status 0
17:46:53 INFO  Started sudo&lt;tedge_sub&gt; with process id 25568
17:46:53 INFO  Executed sudo&lt;tedge_msg&gt;, exit status 0
17:46:54 INFO  Executed sudo&lt;tedge_pub&gt;, exit status 0
17:46:55 INFO  Executed sudo&lt;kill_out&gt;, exit status 0
17:46:55 WARN  Grep on tedge_sub.out contains "The size of the message received on tedge/measurements is 20489 which is greater than the threshold size of 16184." ... failed [run.py:88]
17:46:55 INFO  
17:46:55 INFO  cleanup:
17:46:55 INFO  mapper_cleanup
17:46:55 INFO  Executed sudo&lt;tedge_mapper_c8y&gt;, exit status 0
17:46:55 INFO  
17:46:55 INFO  Test duration: 2.92 secs
17:46:55 INFO  Test final outcome:  FAILED
17:46:55 INFO  Test outcome reason: Grep on tedge_sub.out contains "The size of the message received on tedge/measurements is 20489 which is greater than the threshold size of 16184."
17:46:55 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="tedge_software_update" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="PySysTest" name="tedge_software_update" />
</testsuite><testsuite name="valid_device_id" tests="1" errors="0" failures="0" skipped="0" time="0"><testcase classname="ValidateValidDeviceId" name="valid_device_id" />
</testsuite></testsuites>