<?xml version="1.0" encoding="utf-8"?>
<testsuite failures="1" name="docker_plugin_update" skipped="0" tests="1" time="4.62" timestamp="2022-04-28T13:14:09">
	<testcase classname="DockerPluginUpdateTest" name="docker_plugin_update">
		<failure message="BLOCKED: sudo&lt;docker_run&gt; returned non-zero exit code 125" type="BLOCKED"/>
		<system-out>13:14:05 INFO  ==============================================================
13:14:05 INFO  Id:    docker_plugin_update
13:14:05 INFO  Dir:   plugin_docker/
13:14:05 INFO  Title: Validate docker plugin install updates existing containers
13:14:05 INFO  ==============================================================
13:14:06 INFO  Executed sudo&lt;docker_images&gt;, exit status 0
13:14:06 INFO  Grep on file /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_update/Output/linux/docker_images.out ... passed
13:14:08 WARN  Executed sudo&lt;docker_run&gt;, exit status 125
13:14:08 INFO  Contents of docker_run.err: 
  Unable to find image 'registry:2.6.2' locally
  docker: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.
  See 'docker run --help'.
  -----

13:14:08 WARN  sudo&lt;docker_run&gt; returned non-zero exit code 125 ... blocked 
13:14:08 WARN  Aborted test due to BLOCKED outcome
13:14:08 INFO  
13:14:08 INFO  cleanup:
13:14:08 INFO  Removing containers scheduled to be cleaned up: ['', '']
13:14:09 WARN  Executed sudo&lt;containers_for_cleanup&gt;, exit status 1
13:14:09 INFO  Removing images scheduled to be cleaned up: ['registry', 'registry:2.7.1']
13:14:09 INFO  Executed sudo&lt;containers_for_cleanup&gt;, exit status 0
13:14:09 INFO  
13:14:09 INFO  Test duration: 4.62 secs
13:14:09 INFO  Test final outcome:  BLOCKED
13:14:09 INFO  Test outcome reason: sudo&lt;docker_run&gt; returned non-zero exit code 125
13:14:09 INFO  
</system-out>
	</testcase>
</testsuite>
