<?xml version="1.0" encoding="utf-8"?>
<testsuite failures="1" name="docker_plugin_update" skipped="0" tests="1" time="4.92" timestamp="2022-05-04T09:19:10">
	<testcase classname="DockerPluginUpdateTest" name="docker_plugin_update">
		<failure message="BLOCKED: sudo&lt;docker_run&gt; returned non-zero exit code 125" type="BLOCKED"/>
		<system-out>09:19:05 INFO  ==============================================================
09:19:05 INFO  Id:    docker_plugin_update
09:19:05 INFO  Dir:   plugin_docker/
09:19:05 INFO  Title: Validate docker plugin install updates existing containers
09:19:05 INFO  ==============================================================
09:19:06 INFO  Executed sudo&lt;docker_images&gt;, exit status 0
09:19:06 INFO  Grep on file /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_update/Output/linux/docker_images.out ... passed
09:19:08 WARN  Executed sudo&lt;docker_run&gt;, exit status 125
09:19:08 INFO  Contents of docker_run.err: 
  Unable to find image 'registry:2.6.2' locally
  docker: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.
  See 'docker run --help'.
  -----

09:19:09 WARN  sudo&lt;docker_run&gt; returned non-zero exit code 125 ... blocked 
09:19:09 WARN  Aborted test due to BLOCKED outcome
09:19:09 INFO  
09:19:09 INFO  cleanup:
09:19:09 INFO  Removing containers scheduled to be cleaned up: ['2ff1fc232229', '9643a821998d', '5d3e7b20ea637cf56dd21f1fa07f3dc90e62ddcf84eef417fc06944746aa050c\n', 'd963fa272cd9b7b93708639ebdf22f4b6621dd28a99332e5b5a47d2488aafe08\n']
09:19:09 WARN  Executed sudo&lt;containers_for_cleanup&gt;, exit status 1
09:19:09 INFO  Removing images scheduled to be cleaned up: ['registry', 'registry', 'registry:2.7.1', 'registry', 'registry:2.7.1']
09:19:10 INFO  Executed sudo&lt;containers_for_cleanup&gt;, exit status 0
09:19:10 INFO  
09:19:10 INFO  Test duration: 4.92 secs
09:19:10 INFO  Test final outcome:  BLOCKED
09:19:10 INFO  Test outcome reason: sudo&lt;docker_run&gt; returned non-zero exit code 125
09:19:10 INFO  
</system-out>
	</testcase>
</testsuite>
