<?xml version="1.0" encoding="utf-8"?>
<testsuite failures="1" name="docker_plugin_update" skipped="0" tests="1" time="4.65" timestamp="2022-05-03T09:44:59">
	<testcase classname="DockerPluginUpdateTest" name="docker_plugin_update">
		<failure message="BLOCKED: sudo&lt;docker_run&gt; returned non-zero exit code 125" type="BLOCKED"/>
		<system-out>09:44:54 INFO  ==============================================================
09:44:54 INFO  Id:    docker_plugin_update
09:44:54 INFO  Dir:   plugin_docker/
09:44:54 INFO  Title: Validate docker plugin install updates existing containers
09:44:54 INFO  ==============================================================
09:44:55 INFO  Executed sudo&lt;docker_images&gt;, exit status 0
09:44:55 INFO  Grep on file /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_update/Output/linux/docker_images.out ... passed
09:44:57 WARN  Executed sudo&lt;docker_run&gt;, exit status 125
09:44:57 INFO  Contents of docker_run.err: 
  Unable to find image 'registry:2.6.2' locally
  docker: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.
  See 'docker run --help'.
  -----

09:44:57 WARN  sudo&lt;docker_run&gt; returned non-zero exit code 125 ... blocked 
09:44:57 WARN  Aborted test due to BLOCKED outcome
09:44:57 INFO  
09:44:57 INFO  cleanup:
09:44:57 INFO  Removing containers scheduled to be cleaned up: ['', '']
09:44:58 WARN  Executed sudo&lt;containers_for_cleanup&gt;, exit status 1
09:44:58 INFO  Removing images scheduled to be cleaned up: ['registry', 'registry', 'registry:2.7.1']
09:44:59 INFO  Executed sudo&lt;containers_for_cleanup&gt;, exit status 0
09:44:59 INFO  
09:44:59 INFO  Test duration: 4.65 secs
09:44:59 INFO  Test final outcome:  BLOCKED
09:44:59 INFO  Test outcome reason: sudo&lt;docker_run&gt; returned non-zero exit code 125
09:44:59 INFO  
</system-out>
	</testcase>
</testsuite>
